apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Qdrant Helm Chart
    - repoURL: https://qdrant.github.io/qdrant-helm
      chart: qdrant
      targetRevision: 1.15.5
      helm:
        valueFiles:
          - $values/apps/qdrant/values.yaml
    # Values from Git repository
    - repoURL: https://github.com/edlundin/homelab
      path: apps/qdrant
      targetRevision: HEAD
      ref: values
      directory:
        exclude: "application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
