apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qdrant-ingress
  namespace: traefik
  labels:
    app: qdrant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qdrant.oisd.io`)
      kind: Rule
      services:
        - name: qdrant
          port: 6333
          namespace: qdrant
      middlewares:
        - name: default-chain
          namespace: traefik
  tls:
    secretName: wildcard-tls-oisd
