---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-github
  namespace: argocd
spec:
  encryptedData:
    password: AgAL35JI7pOYNVlf4M2duzkjO7oUBu3g3Ebd6svx4NI8XvU3UzAGopXjMGAXLScy4UreBRQMYD7WKUYd1fYPFYCuGDCfxXanLUQ663zLGM9XiXojUbMNVBtU9/Ax+Hk/WIKM5N7s6Wy4OBXUZVHtlvWygZ/mPEljY3/iwpslHGWmY43Es3QwkcHuTcd+lGTcLePke/oQQ3qp7RwMivHcfSZ1VU1EFPD/LSWsoRRhbE8xmgxrastf/MDdzX8YwlEYOQ8XlrIePp4T50xN6C4aDIjyl1IiZNyYQgnRWTvTqsG4iIDbDKgOxdsoOcUnI8WQBx7QDGIdQg6GtgyhnbPdY5pj9pzK3JNMazGYprltDnvC9OWB+FAiYP07vy26IUbe2aJC5ZLIqrA1WHnmUg+8cYj8bb0sw9rdf4btkQVxZEcIMdC6iLRXPi1KzoSac05MYF38Lfjh/4azIpe+kS/k3FybV5AyT+ZfIfN2WAhx8fgX1ibEtmInlsJanlxeRucaCIBNmEPgOw5Hq7EJIHAZWouOeRya/iIHwJD5EactfmH4tKhU/xywUQA9TnbBATBXDiCRYaiRxkFxHbSB0J0RGFkiHs/0iWu4QYlnpJ52r+O42rNKJj0WstRKl70dO8+cMfKKUszuMPkfuvEZUNssmInalJaAVW4/toKoYViwdqVVOytDFUHVWokt48Rnrivkz4RV4qVfKjhb/JoCPEWZZXnJXb7l37l/4SV1H3XzkACmR7ZA8LcLZX0uPMmmABLiZKRtVBDNkEu3G0H6R7bYTZtRLjscjqw1rxvVuZZShpqETAHtafMHPPp87f7mw38=
    username: AgAA8e2Q+KZVvJ009bYFFBwJh/lsPsCMtcwMhuX3D+h9SC+MsW9imNEr0PSTYMZlMxsPD1YwCDg/zFUJ9sBmArux3haG4LpP0yKDRocvduZ3crKXT/xAuymXSu2TdVCLZitWC3WPF3RhQJURnhsPbAlrXyFX8qxdoTdCLf3qK/TMOYaVdhone/ysFMLUdQpe9dMveAqgfv4LJhmgvmPcKQolOV/Lwv25J9yq7xG5OgF1+PTNB3NKKrHQzYSnLZjZKwpp33T52mpsHHFmA5YFcJSIm4vREgsUkltAe/pMIPidKFMR9oEpo96HkNmyppg5cg7lXhLGDlDqywnf/sFbnPmUE4vyaX75hKnWkrVcZR0ISh9DovidZ/FA3ksef0/F/fiBYmmF1QXLEmyewoCYjIZcMj5NI5MrbhKr9Zv86QsGvED+r7t0Wi/V/0THkt67yhGR1AsaxLHID6MLnNucbYB9Yner+00Xk6tbAqj6AQ8dyllFUmhle9Hmk/22JuuEht37cNARFs4QDQRC78VSwf2aLZfe8WOPN0zXGq7UZSVAT0jmfjKfHEsvzI5dX95TiqOmZBRgWu32JSR2022kn4CMke8ry3KOhAmOumgRkf2HkDEtvskiCBubmEjDdQHvKsZeFXegHRMQwAq1rO/MFgTZG7NLX+ff5wYdcu++vPSRQQlH1lSYDMwisl3C3lrA/sDxtV4mkQpfpA==
  template:
    metadata:
      name: argocd-image-updater-github
      namespace: argocd
    type: Opaque
