---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-github
  namespace: argocd
spec:
  encryptedData:
    password: AgDNrF9+IsIyRpbhpaKSbykCPGMlwx8KBFmcyfbVVuVnqZ/OwXmaxy2zesEJR9oR2His5Msjm0xE/ib+VSOEccVeCOJoAOL4J/Ttt+iRbIZOn9pt7wu1V28rXfmy5yqT7QDZcOUPA7DJIddUP/q6blYWRZMX7mT3hGfdVwWSM66xm5Y7KyiE55m86LCs2RRAABe4j46w61Tk46YsUgaJHP/RUhA1YIkvAH/zNSbfqb/6b/N2LByAZxRwzUmIvG5+EvQab5gfeIyBToC88gpcvUY2cfTfvMXDSlIhJ8JkObFMoYE7JcvypAPgUC/pYcbzIPKMYA367CqHx9++W6/C/47AYXLKEG1fFG6Y87avwiPq52tDJVRsxQmbWsUe2UxRz2VkXBPYrTB2AEar9NSt0hD90bcAnZ0opgk1ALcpDdPnD/adqrxoEGAFX6pCsq/H5Zmzv+01U1mPLnMYdN5Z1k/5YCOK79XLwH56crfjkiTz9rpDaxQznScuJTsqDOujm8+8V6tC1y+uDtuh8vdFL1Wj6iGEmARdYPz8Bc5GIuho71/NNt8LntRs5hK0HrmC8tWdsUwq9brB6bzlxSudklI2Ih//p71IxLA6DUx+aGDyXDmAz+HEXj7wsPWUe1SWPycpplZYVCrQ3IsJfr3XyLdmpVh9ysQwqR7hUovPMY08bovrDsY9mq330kF25jvYmpusuVmmUcZOrHc5/53Ckv46JWKMb/aSMxdPhV3SAxV0NBsyFHhVHqYAnQEdrMYcqHdyvZr8fjkTOmmf0KTAMnZIcE/acJK3+y991NVnb7vYVG5C1MDM3tcGam/dUfs=
    username: AgBE5oa4X7RIJK1cux9nSi6cZsW6xnuGIzP+RcoRoUjZ8LtlJDvBpPQEsRwQPm5BXwZfo+l2gSi8erilrH2UwSEJiRTDlRTo3pDncOjWTj0sw60toERrWXMcdk0N7ImfaSjybFE2k2gdCJ8X1rJl3Gbp7ZutJ4d3eVrEQbsL0gtDEzBj4phMb/Phnggq7kgaNfLZoQ4BCrmG8vqNM72bpTRonuObnHAPG+LoYFd+b8z+nk0SBWnCbT5aiRDoq0ovKQNSNd0BekmrKrRRuyZSYm+TZ7mExWOlCi7QkAT/mv2IM/u8WmgjNKjuK5wKp3NsicoGenA7Zbe+XuM1vNUxREj5FMQwQhTmNOPUNs6K6/h+kRUre0eiVAAQ6E+BLU6f9T64NQ5aj974a/A8uPg+9bzaY0sVhAcZHp+3FtT+yJwhw9llq33Xoqb+gMklMU8YtG00PspaFYcxxVM771DC3dzcQTB2ZjE/ghauv/6PwQtxjfZ2hsqLC2dSMQ3p0q5G79CoAo0dWwbl1S44qs5kFuLQosjEdtM1X9zZmKyG8rMmxYCEEK37v6bgGpUiwkqdhXtuxeMb2eniC3MYPMMgRAPnKFqXVyy40pMX3v/8O+pzMb9KJCbJ/FRXqMeLNnoOpW8enFDRQuG1B/BO6fxwYpvArFLnWs3J/d3JqHGJAncZns4FcoJ4QJ1Y4llOUg602PteG7umICC1+A==
  template:
    metadata:
      name: argocd-image-updater-github
      namespace: argocd
    type: Opaque
