helm:
  parameters:
  - name: image.longhorn.manager.repository
    value: docker.io/longhornio/longhorn-manager
    forcestring: true
  - name: image.longhorn.manager.tag
    value: v1.12.1
    forcestring: true
  - name: image.longhorn.ui.repository
    value: docker.io/longhornio/longhorn-ui
    forcestring: true
  - name: image.longhorn.ui.tag
    value: v1.12.1
    forcestring: true
