---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgANj0mu3lOsP3TZcTjTIZ21D/I5uscEUdEgNUbJH6hPSGh8xyCTgcY4p5ist2yOUqGngHIpITREdvuxt0+fLXgKepWn4q2eaUDAORmkpKrDKF2q95nNsBZX4ILI3wJ9dV6SfVsC8VCQv33wZ1W2IXUqZoafeo/CTyHaF+ARqvnnUpvYAlHAjoRFpN2FKHCZBUIkm0n5SWQhiNSyjIyFGMPAsfiufHvpDFlWMkyEmbyLMcwNjB9ixdN2/potKFrLT+kvdQlYbxcw80Esfsj7PMR2XeCsIracsuj+UED+wgQQa4d+fpMQJsRk+AdQRt7gtdyOqJD6qyGjRpIKsB4uoizeEMXVQK8LbnbXVHM1T3t1coKZEcwXMopxtdt0bPkuLEfbIKYEKzdH8aPO/kFyPXbe4iiaD6YsBZkNQdJuaS4XEOiGFOrA9R2N3OS1p3l75Wknnl7EXYUfZXr0tHhkIgB69MziVHRS12Iy8lhyYl7pQvMU15TIbmQsQOFMx2N6nhH+zKRUPQD1KgcawHzcrY68n4UXVOtfN8fE/hKjy3qGvdv4Nboa2oEWgelfsOzljA0Fosq+dPBEEBdLr+W/obcc8AFB2Tck9oFYtWrvfon69NaiKWSi1Itg1zr0Az0WUKLn7AfVQbdt9iunimbMGocMaPHqdHyVl09bsurEaoXUYQYOlIwA1I6IY3DXa+eVJ54P+UXCI33jLL/E4cENv6lEeipck2f+v9uMERi0GJk1yN4lWhXgcg8/
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
