---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA+4lEx1XfZSHlMTE2bSe9D/laO156a9H/QiVVvN7ypMhQnLI01rqjHefYtiJAIZDJi9iwFMROyLJ3yxt2S5xVemXQpILoHtoD9+fFVg0uM7FfFGVTYQHj5P/UWnayYb7wXRCuK9tw6GGR/A0YvSw+oGepvUttcFrnekP8aiypLtCjKWM88xPQriXS2JJlw12Pgu72bRqQwmVmWxr742wSLN7S8VlfMcrZuY3i9+WH+pApXpz9ToMa1WACbLTQb9+t/BwQ1PYUudoW6wFFMmsStupwDYn1hnz5xLIWnALFohQDr7UZpFeO+B/jBdPN4V5ueXE5Jym2Aw4UdnhMIBBnpXvxJhfzq9vq7HpO64IMvQOC9/r51P10LK69w8JatmG4y7HHQ1xe5coHczrJHT8Zhw/QPXGQo/qj41anKk+b2yhcDwbQ1zAZ42lMgaNVVXCcp13hXlTNC84Jf/FQpXO0CsvSncoK55BSvaKGQDVlnFETdc5MJoSIEXSJQ2R6SPHZi8Etgl8d0SK7JMfy8zaOeLIl+yJqWvoTDqw1j7p9kkQKjGRFY+Bq7iDNQSeXOY+lbc17qExK8M+0ReeJ6uQsd/i8a9wrxuMIsxII7IJA+5NYdfsSu/Qatt7C7blsWTHwWYbfCcy2kxVD3mh1yV9V+m6Jhq5AdUv/1Qa0yHtgGvphKSv7ZSMxY3RZCSAUN5yx0vpQkih38aQOkWB/ENOHBw8SG8WDaInAXudCPXCpK0N8z83hx6gtd
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
