---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAH6BvRUBPXz+BTfTT+uSfwvK3ENlnUqOwpTD4uIQia9LhXZxxxzJ4q2a/GoCJLXhL+ify1NjfHisiqtLpXOvdTFHWbFwSCgA/JWM3/a/1ASQ5BuvmrA47X7Atf+SpGLSccQHP1zkTFsC0PVYfVHtSAcifU5YbRCV6eVD++Vi9iX/J1RVrUCnNRR7eoSky7CjfB1pB7gt7rmTz19OBaOpQCFoONB6OUuYNgWoF08CFFj2Oj1rFJRMGuVvthzDzAkAUVKLb+mx57EH5+ym4MmtCJ5s65a6PBaLzPwyJ9LY9b2dVcYp+/jl2Rhm3p8hCLHizk8HUeItQXdsqStRi1xC1eNxyStIzzzf3hVcg3pgG08TKGryyR4D2VYlrB7wrR3Y51B+5nlIf6wTjxDtIqntRK7+Trm5fA4x8bWjhnr7wCMNStfS/SpxEWC/6NxpHMCzmO/km2dBeu8ccjp9sgDMVA8nM3Mi2hvrKiybZXZcHqu9mtIyleW+2y2yuXu4C8H+SUkukXTthWB/FsnqBpFqwoAYPlfTIjJ36oLbCHxROiuWug5A0TMNa2AMB+ZsHmeQvWwGSVLdi/Wj6Ie6MmWOVrZMJBh+3kTqIPBcNSPGztka614YJLMRV+K9JTtoxEV+a4NklZ+opHheha+4XKY0fHa1AgFZ1WKR4PZIwhcv+K1j1QijJ8xGYf3fJxISoYOQqzfHknNm8XqyYmKNI/ZRkXE2V/GPcXlOQQaoLcuEUOMmEv+d9aU4lF
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
