---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCtGYJGIb/XPLLOZc6vY37Yim6cwwMKzVJN9O/iLq8Wg196e9OAFJwgI19aA37KQ7K1LOQBfDmoU3xee35R2kacPjBctBZHiC+mkyQTqiJWaPgalbYgtZ5+mztCpyhY7ilRL0jBGiC+Ja03DeqUiHqPwhgHFXxqnAJOT7FcCSZvEYDHljOT8bA4E2tW0KjaOCKbs0XRU6sKeQPrhiBAg4ovYwcq5mp3tYHfCUG2oz28uiNuo/NhgVr0A48FGgttSz0k6NkYEVwyJvmzEHm5Xy40cwDqoRZgfzV++JGm+wZQDysUF9wfHtbC2d0wsiM1ETmeYPGrqTO6FFYa9obWU5JnXV5PGL7HzzODiJrlbvPETbe6E+a4wQsNPtt9J+OfWAh8QYG8VK00gknj05voKnU8pHncAqalx2x3oR6ozgB/Cnf80cMWnFsnOTC1/7UV/xUtrPjVPHwhRzy7mhva9rBflHFYLSVcMP1fQcL3vyfV7weVj19eGlS58GzVq0k1+nerxTqpJeiw56WMGQgmkuqMd3XF1ab0xLW+QeO+0qNi612Ker6shx3gMJEtjKd2sJcX7bsKbw3idO/lH44+JQPRkIA+Myii9NHiguAQ6793mk1OeKNKIPN8gRiOOYwj5z7lsGJNssM29AUNLn8Ch5zAymsSndX0ZYBQb8V5if3o2g9TJdFt+lIqS3iuo2j00LAwPQupKDJi6ahwzhnfYGu5PVq5VVpbRgMIpsmp4kTmF0AnOZdbf1jG
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
