---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCEhs26vHA/z8218QM01oO+jMjiP3t8wmlN4yUGXcIuBYco/fiWWudUFcm30YVfmnLie0qxm/udu8t2a5g05Efrb0gEMKsfKxZIBG5LQXZSK3ODVhUHixxsWA7PH+kBimcrEe4JSC2zXLZSAjWBLBNOQl/HjuqbwDknJCuGiD1MtUquer9JDu5Mzzi+se5DOa5W1qw+jMA/kUaogKF+2VVeOsJQTxx14bI00M/lX4I/wZFhQnwhHHyiJEBZ1e/beWfQz3svf1i8k+aslrRTgMxLt39000UEvInqmZO3ZrxFP/6yk9KTYflWvcRkR3CWxOs1riPquVWWNLbAcGK876/Ocw6FeVq1HZK3u0jjykwmfxudyDSm/K8FlyGUfnBL9GeX6a+098uxIfqaTAbu8j/SBU83T/OVdAlLruPMZ2kD1ecqNfYpWXHBKeXf2GB9jpPULzTd0t+A1mSPU5ye5Zqy3t/ZtSq8bhdefnESJblLWadvi0T1EVS6WKQLxHM4c2k2HAJTZFnxMlkw86GejgqkWRefHQCsrS8GB9wdAgoHtvoqm49Q3ScpI4bFPhavnmBZg/uGP98YwZuOzpHZoBWP6g9E7Ow1CFUlrqROSen8v5BCDwD0so4J7YrI2mQeJAW0i0pCMgPKFkTA84Z4Fj0jQJOPV9ZGY8r5NhKmPDfYUXNESlxJTbXKdPJRjLZlD5o3ETyAIZTLQ16E9I8gDM+7CYSqylw35xnPNiiAXG7/dCklxqRzZahz
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
