---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB18+zykZmot9HPjLJipFdscFSauP0NE8HCHIlmKLizczb2TSLmllfeUAi0pwWho+52zsBXZ0zhRi8n9EguX9C6EFv2iBj4mL/QxFOuF4eVxdvYLbzai0Bl/Ym11t2BEoJFs6OQ0toqZpj7wQW6VTOb2Xj/+j6gFvBujaw3G1r51ncZpepzgu6MDBN0X+CbFCtjMXBAOOxPcm5pybc8hYdSNE0bp/6zAi+qSNf/grnhIsmIwzI6UY18B4VHz0ZojnHxle9NPDIlHRhTo8KIUL8lrlOC3hZKbGlp5cathkedUTnS2gvNj6+hUz/bxGVNNDNf64M2fecovggMalCjPRDuWrv7vDosRGl3wnYVudt4pa28Le3D1qaCLM6UkldF9Efb8BhUyF6OrqXecalEIvfZ93hofPDRnR8s5o9cK8jr/fRO/Cg9aZrjldPJl1+GgG0qR8CtrP0pmjP5mV6ujkhtWiplz5tAk95gVvvPHYpwDyVXOZHOrCS4SN4ThPaRRldMEMEkdUkO05fKwDrO0dK+F5FnDDnejhbdiSQ87tmJknsJ2rFkgMH+9BP2cEUu0Vd7XPAhCjD734ATSXcZ2sDPTK4GY6nBv5saS2PLGO4v87WgVntY1d1TKda0Q7+E+t8CI9P+9+L+d9lP9nkLv1PGIootnFhj2RtTvkAHGTVVBXbAyAz708G9PVnrnPjB19fqcXjdNiYqWTm1m7DxPJwexT0XJHS2SZVFNoL88GEtlc/osEuUbVKx
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
