---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCgWxeo8m9KkkqA2h2IW0unzKaI9TaSAfAFqtJ1FQ8Z9lVfYg0OGgb2U9YQqyN6sVh2908U7VFXhKprLv9aZqkMtxed3pY1tKuDnls4X9ii5jN3DE0/nPlMFU6kBh+PuI4WsvvvagnIjkcnKhC38pp9QNcDII1saP6NIdHO3O3jkNTFy3idZhAANv7zM8aaZjGto5ooEI0bPMruCZPZFLrIAJe1j+vmWdRDTVIH5zS7Ws+YU9awKN5vcLxctI7nsAfbWF9mAiuM2qaNW3jsvM2jO+BgrryaXrkD+L0a3Lxs2b37MT3GGh3ozJkUKuwP9bQ28DxFz8Cpj/dtIDXOql0o3aU4BtkNqIu+3BTxqZb7CQn049AmDc8XiVQpveII3PPLpCVfqp69wROt+vOjVpViV/olzDIJL9EpTG6S9G847q2M6FKNGKzQBZTsjNWvuWNndZxbCbESk0aXTjxepZlctTWQqNWydjpV8ujAkJUN79PImAV9s5zSaa+cnKtalQmoC2JYVwK+CIm4zn1GLTkt74lOXoT77oY4xQsTyJK1d0tmm2q3fMeudcZvyQ19cabtM9ulcAEf7auOPdwW0CXlbq7zdAdTcjFpauwILFwweTMwp3dFezq1Y2+WrnbheTiHW4gtF2CI/H8dvAg998cqSvBcNIfVVBVuk8CLIQ9hi31I5LJDvhkFq/db5cHVG3h690b/5sRvuoduV+dDm1hP+Sr7+5z2A8krJVn1W8J/2ZzTNzpFSUSi
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
