---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCMrEzKdMRrGwQnkVlNbmUHfTcc/kPXjCQK559XfHvie7yC2pX5hU/3Tw/G/ltixLQLL8VW7xJiK6pAuI1sfzcdua8bM2rHEI+RdXpeOM8XYESfbdllA5mTzUwPiEg7yXW9/v86q6ND38YlCKa2xtJnokD/ekaItUNXrO6tprznP8z1Bht5cvSNRu8ui5eKlvV3oJb8l8TNNFZT/rDmjC0lcunvkYYY6UQ+3dF5h3Ly3IEyyysgr7Z3CRlZk32g+0KVoQNgBMv8+NW9jvYyh/C09c1q1fENUfLLFNdgMljoTJVCxa0VJ4cdcjGd30N1XTEjFfaF1MDpomHdO4LGxGiLdFFCGIsoKwWoBw3Wx6Vii9wOUla9kiYv8ZaR0QLldiWl++mk+wH61LfMqy8J1/4nkK6DmQPm0eMiYQpZXdGH27ufSYQFBj7NYG+h+e/C/5DtjfUEhh6c2a+yg665/l1ZvahEwkJzlyB+ahObr5YyZubcRqJ/5K08acf/fWRKiSwvspDjxZSba+3Cdzw3DxG9rUXJk3+wRldRodwpfOhKSuWOBZvoS0Z/0yLdps0ylMj8zwR78wjvue9faKOFqcxOzAUyiBm8oKLeIhjqpajM5+e0WToxR/mPrkBDQyCLXFjVlsbDBzg2ZL9dOu88rks6z+Prpw0WxN5K+C9UBat3DA3/7skYa7nTBP21Q+21fb/JZICJrNnpDIBZGXtDQRS4hyGeVuRCa+IMT2QKcgM/Qnco1n+cCjWW
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
