---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCog5GGwfxqIOqWl2V0DGmqbEBsyHlCYS6EvcNDP+XPJXD0zLAol1fXcliGRWjZsCNf4CWckTM9eIUh9U2jG4oYlJvifPO+XdCoJjFrm6i3Dddn41PhjwM3P0vHmzcUD9YtONUL748aGWGzcO4bJFpovAT9oCEcAAbyQDLLlq5iJvpfb4meLjXWqMe9v5LhR6pkLCkehcHSTaZ8bRvvRY19iHAsxSWlbDnvAZdcLIQPN0i0fZqMf2OoNEpRk+g8R0pCbbVQcJuglukRnlSF+FNHySkRXx+6VJSAiwFzot5cVC5PTqq/b55dksKTxeOlQvqBMKACOgmzRKelNu46C4BtQaGRMTn2j1WE7B+zRoRQv2R9za13jDljNSAKJH6mCn0HjPG6n63aD6qva2CKw7Gu5p2Qf0/JNYG4l1LteeOSR6Bk8TDZoGAJemRaP5eJAb2EVAy4+utVYDhpdrod24pVABoMfuuxmM7GiFJFq+ABK7R49a5h442KEq/rq73Y2NiFJHCTvVszmEBep2A5sZ5hx4gyDHwE6IEHNvwS2KYxRSkAzE0y/ZmcSuZ+VYj8gaPNaOc0nB/MKS1+ZVaE3xBlknO2N747QysJOGxKsfELCrwHTKhC3IxQ5CWMltrqRXI1dK1UvEr6cW5OeOPNAvAU7h8mrB2d/jRnJfv+H4Cksw3Y4JoA2LqUzjBEV3NJL/mjJ7QdedlIjgOwNHOt27GjhF4PKYJoKL0G07PJiKou2li0+hui1Upo
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
