---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBKYYHIrtvFgfWs04GtUtEdQ/4aHFr41RhC79YFx204WpxdLADCEt9cIT7G1bnNZW30eHegXIjD5REpswvKIrH7DZeo4t1fQmZsH93NIvEb7XL+y7FFpeXIips4lOeVwcJmuHS1cFCrq/Kt+dX1MRMdjFTEL6fTOeeDLiKf+RnGk46pR8Vl6BRL7ucOvPa//AwmMFXJ+Knyp5h4Dou0rOpDQU0Fx9bjGcGtVLRKHIJC2qct3AHBV2b6DaxgnAncuS+LAI0TP90YxL5mL+uX+3y8RdDYLXmMySELc52kanZIZ7KHAd6NU7xc2/bVRKxqh91tqg1yXz2bIjHlk3xPAPjEzG0aoMO8g+1R0BNEuPYscd5sPQF6PTkLOj4rMjJoGzX0hGxsazhiUCZ1XcDOPQ2/nRqOqD7D033uhc0zsEPXEgOYQtnoZIATX+EiL+R+DbbC908lsqhQHjg3lBQT/EZdZZieZZjg8LhCO+qesgaP14ag/ySS4+LESM0aTx9XKqW3NyihyLkefKYHbtU/hGMDPabQfzV1yg8bnv7lA2lS6o7ix0t0DqknPNlr+hO0SJV3QBJySHPMhYHZJHP8qP9f9VmdtqxgOzL5jAXuPxLzQy6PvF0wvrSkNrMXb3MqWtQSTpPja+9biJryyjfw8Kehirtt8tMBE/WhEEkx6qMIoa8Ms8F7gZbYNsQk5gtpmJZdUhrosAZG/CdRskAQ8ynR/9RtSYAr25uE7Uo/+tIVz3Jr4yvqtYng
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
