---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA63E5G0GXyZi0Ngv6G54teWN457/ftG6kL8ZDGVOv7z86nXFXwPsjniXX4KMwe7gef3asOFBJBtK6A/ubNVQ51YVBjGZeQ7SKli8RUhuQgiLUOu9mfU8IrKmXL45NuygDN/0M512a/vU3DzpwhhDV8M2vrLhAaWPhtATDrD/p6SF0RpZsXJ0Rb63aRXxDU23ORpgIDwCBiwbEPUywWa3/Q/A/6df8cmWceX8DzWVKVxOkmxaWjkONLS4r171NZXm6fcmlQ+RvfBFTp8rcaLM8O0kyiQTVyonU6Li8a+rXgQF/5+kPYFr6nb8kWoo+KHUKN0MUdtYcg5Q3QCGbUWHzuEwy6cWZ5h3d2gRctagKtg7oqZwctwYZKNKepRFFbSo21n1MQZPyoWDmfgSes4b6z0APftRgziwZv+zyrn+JOCKf0T0i0UdwKLkYCce5u3DScHYPIQEWyRt/zfc55KlIiSzj4J98kwjxCKqF7P1IhHrAODGxIWH56gIDF8p+tfgdlBvmQLRHJSQKPTp18Lha683yeBY8joTOEKetUD3WCCE2bqiUeoKsUIa0stC+GJp7JmYi4HQfDNvA30xfYbKLWK+846LNZwLtyAEsXnGRPcOPu3n+pU6ECv+qOx88fP839igoNVf0YNkp6Rqa2bXZXcXCIvMOHB84oevJV6K3DovSNVBamCbnE4EFFnNve8D9r4amu9DXnq5aPAMMWL+HuF8J5svD/GnEmJeAp7jGoi2umnD4BrfD/
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
