---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCjBflaajGnFt8gSd4tTCuTn2sO9aNx7QBPkdGG4BCeOTV02XGPSuoDcDJaafxHP32kilp7Pu949BX9R3DEdD19t2Qt/DwaRjKpyJvbMS5uMS4QfV3dlu4/ZMM/lGasgSMwjQgBeTTgDtuKuUAdCUvQ6OGKVmx//o/U54GZ/nWIft5MKxyQKA/28j/GAtmj3Uk4kemmvzhSnfYX3ayFO/0n7+/h+dkb7qqSIQjrAjOL40oGC1ZOenIPayHSrQnV3aqTkRnyZMPF+Fu2LMW8iweiiHQpk+xlO63IlyMGYY+CE/JxMY0izG4eaA4YKsAm/WpRezE+uY3odPL5ObeqjOw9ukGyFmivihonJ80rfbJ2J574l8OBSMrhQpYvipvTrW4Kc2Tai21lvaSfSMa1upX4CHy9zPHGHoVQD6k/lH0+tWBhUwKn7wBOQxXXcXdhckzicvTH8ZTR220ZLJkuF1bUdt8aaZYcx4Uq7w7wGkeKY8x/Uq5eSw/JzFVM2hTk6rjcbHMRH4tRWCM/xzAIhHvYX5lPZ7DERhxDqHSkOI+3nEYoeKyg6qvXSXvKmUJZl8cjI8rzH9+mjXczuAnDTiwRhoKT+1Rs23930LXK+AkS/OXTMVjn7VXq6h/X9rigeKIx3KHt8qLDro8f4EPok5HX3GPyG8fPDR0oM2PHgpU+I5ifLfe7IiQw4ajSQLlrxMYWr1ywJrx4Yy7Ojb+mcWdX3CLM/CDeGKBzdkUHMsfed81z5HzY9eja
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
