---
# Certificate for wildcard oisd.io domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-oisd-io-cert
  namespace: traefik
spec:
  secretName: wildcard-tls-oisd
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "oisd.io"
    - "*.oisd.io"

---
# Certificate for wildcard bos.oisd.io domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-bos-oisd-io-cert
  namespace: traefik
spec:
  secretName: wildcard-tls-bos-oisd
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "bos.oisd.io"
    - "*.bos.oisd.io"

---
# Certificate for wildcard s3.oisd.io domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-s3-oisd-io-cert
  namespace: traefik
spec:
  secretName: wildcard-tls-s3-oisd
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "s3.oisd.io"
    - "*.s3.oisd.io"

---
# ClusterIssuer for Let's Encrypt production with Cloudflare DNS
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: edvard.lundin@pm.me
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsNames:
            - "oisd.io"
            - "*.oisd.io"
            - "bos.oisd.io"
            - "*.bos.oisd.io"
            - "s3.oisd.io"
            - "*.s3.oisd.io"

---
# ClusterIssuer for Let's Encrypt staging (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: edvard.lundin@pm.me
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsNames:
            - "oisd.io"
            - "*.oisd.io"
            - "bos.oisd.io"
            - "*.bos.oisd.io"
            - "s3.oisd.io"
            - "*.s3.oisd.io"
