---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB7vwmf1/iGJKtGXzzF0ylAWPYOiM8wEnaRNgZu7sECOT9WtisZCemRHxHJ8rv13bYFMIgcsG3BTp4N/QPmUMutbiziFIdqJXD/OUZMu+DhbYtc/NWiyOsA8HBR6UWq1HbAXRIIzF5dOQdFmWjdqZPm6reCdSg5o3o8eZ6yR2r8RNeCoJpjhOZdr8mx4nK2cJ6r8gx1ff54iW/ZoXJ1UDjvcLQkMxH5wBdZMJf3Qbl5ES8lA3U4on2QfyJ7DEGeda3+qNFo5RPJT4w0XtdhRdrHvKMmtm4ALieN/Z/SVKvXFjxFYNQaPAcv0yP3B+5WHZb2dMEhQly8cTd6QZIN9HfX94xyfAkwxyxPL6/7LFb1Hxsq5uABvyVb34/u2vxPlRT/8KmF1GSecZx+mCm24yoSmOp1/OPk31ETEmzE8SsQg7UjPydCAFL2XU5Fjw+AKFkP0CraeyuOUth58la0HdqfIc13qnXrwGxdTIeQsR8pQatXhwHOhRe4V6rNVIuIHKAF6s0kZHrHidtt0pwwF3zeyeSo6x9n8J5NnKcoDHdbTliZafauZiPD8Ov/PzY68DHldKfeDELUcxoZiiAef6FUOaMG3XQy0w5hS8mjST/vpvq1LjrvjoVXC2SegLB87kQBxepFqG4fuG4WTD1QJDsnB3BK+mlhvIa0GzsO5jwOMAc/OZVdz+mzG8+LzVqtW2CRxAF0PHBPurHWeHicd5vpqJW5abJg+zqCofGfBz3ps+FkUK+CpwIs
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
