---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAyJoj67j9jEqrPqSUfPJvmbTPV8FvtnSi0APjkSOPGvgxhi+SC8uuoogeAu7/Ak0Pd3pWLbaIQazHYP7/Dz0evXr/VDdThuwqTRKqWWoQnuj8UFK1vM9RR8aHN5Q8/Ccord9VBDBQmSLO2mh+Iz1NCKyY6PFHB7CniQPZiogDxrUT+dHJqYEnBC69x1eCeZULbq+pPQGwos53/nBdocOrgzgNl5H3RMitQhfG/c04WZnKR4iYLfyM9nPywUQXzlRgKqwkmaAwo+6OcRd/aS5gyg73KPDO1T32Ezu3YVpeOuVPxCzeUpMvfbxR33lJRd7QV2xe1rJBZXcuyaaQCVqi9ahlgo5rl5S7JimPNyx1fBhUV7Croc+dPAOrSArgS81A3af4bDjOsq2PsTxXIOUM7u4/p12D13cpg8fuS4Hm+eo3PSHKl4hKauSNSOA2U4yehyrtE1/SEZ22FEAkHWVeq26/NYhjflzW19IPsTwe5FTc4I4VPhXXvYViGPMKFpaBMPWvVj/hd2PKFJ/4HYs2iNQh62dhudayfb6sTCAm8iJuEWRUunSla2FkYwcVrEUfNDvupolEFtc0dPrTb4dHLwc9Is2wbiPUIhdf/AZGTIiEtBjNvaesbc5PQR1Mwj68YatxAUlm7qWlU+vHa0jWKexclqHThwkwOhPBeJOLeLg7K8MvYh4vri1IR+xpgMXkHlJu/x+Fl/BYlfP9z+L+dVdrjrbfSV53h+YDlAYsxtlfZN6B0N+zu
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
