---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBDAC09I0bKViE5QgT/K9xpz+SZdcs1tPOg68zqD7c8kx+ZmblCFeHbatuRleDxVU5aOhgr4cKM5L/31dzXV2ZD+PopekYIX9OmSmX+pBjFJ5u4hfc4h+T2z0FYYnJz94Jc8oCet4wT4Jyoa7VhbQPAHAkRLWVjm8Za6Thf9JRtGTeDVZgr7u19c8oikg/7LalrfrsEhSx0ctdOuKBz2kOu2QGVJJhPNNGj6yauOcyCJt9X3lbVGQQjFEav51C61D3lvd+KX+GZA+rJsS0ian8aGSh+PMNmF49kbtSDWeT7nbfH6h6YDDqYhuCpufRtYx2jNvwunOZFvholUsj0FWEAk+SqXNX8T4KVHMHZRiKZ9gEKUdFtC6qg6Av6yRude1qXSlzrdjmoGZ0Y4hLXW9R2pmgLz7HIk+kSJt9D+HBGbn8Pi5j8bgr6SW8t1PgUBbUb2KCTb5OA4rSRpS7KFW3gSgjf8gz6YAn33hx0+WW0MpYtsmYB3TIy3lYAenoa9ISU0wkhQ1kNkynHm2f5TvKIHKz9XEo3tx9rIFGlogfT+Hvf0px4tVe76B95NbJlASjyUrGouOwG3882TlE282JGXciWwme6n9u1EBd0wKNdnTPRcxnWld0hnPHck1L2bT/KH2vJe13GUCNQP1czVc+wbmHyo2OFK3FZDn3PB8tfZmeAM/y19KzazP0D1PM2F5uhMQzmMDuA4RSkoGMidGsU0AeOUCpZoK5GmZJBmEJmlhwniCz0SA6F
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
