apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database-bootstrap-job.yaml
  - database-sealed-secret.yaml
  - deployment.yaml
  - ingress.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/iuliandita/digarr
    newName: ghcr.io/iuliandita/digarr
    newTag: 1.17.0-debian
  - name: postgres
    newName: docker.io/postgres
    newTag: 17-alpine
    digest: sha256:9beea1b7f176d67e49e23092c63db9e98db32b303ce1b510749379ef46a3dcdd
