apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # Helm chart source
    - repoURL: oci://8gears.container-registry.com/library/n8n
      chart: n8n
      targetRevision: 1.0.15
      helm:
        values: |
          image:
            repository: n8nio/n8n
            pullPolicy: IfNotPresent
            tag: latest
          # Basic n8n configuration
          main:
            config:
              generic:
                timezone: "Europe/Paris"
              n8n:
                # Hide usage statistics page
                hide_usage_page: false
                # Webhook URL for external access
                webhook_url: "https://n8n.oisd.io/"
                # Editor base URL
                editor_base_url: "https://n8n.oisd.io/"
            
            # Reference encryption key from sealed secret via extraEnv
            extraEnv:
              N8N_ENCRYPTION_KEY:
                valueFrom:
                  secretKeyRef:
                    name: n8n-encryption-key
                    key: encryption_key
            
            # Persistence for workflow data
            persistence:
              enabled: true
              type: dynamic
              size: 2Gi
              accessModes:
                - ReadWriteOnce
            
            # Resource limits
            resources:
              limits:
                cpu: 1000m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 512Mi
            
            # Service configuration
            service:
              type: ClusterIP
              port: 80

          # Disable chart's ingress - we'll create our own
          ingress:
            enabled: false

          # Disable workers and webhooks for single-instance deployment
          worker:
            enabled: false

          webhook:
            enabled: true

          # Scaling/Queue mode disabled for simple deployment
          scaling:
            enabled: false

    # Git source for manifests (sealed secret + ingress)
    - repoURL: https://github.com/edlundin/homelab.git
      targetRevision: master
      path: apps/n8n
      directory:
        include: "{n8n-secrets-sealed.yaml,ingress.yaml,external-secret-*.yaml}"
