apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # Helm chart source
    - repoURL: oci://8gears.container-registry.com/library/n8n
      chart: n8n
      targetRevision: 1.0.15
      helm:
        values: |
          # Basic n8n configuration
          main:
            config:
              generic:
                timezone: "UTC"
              n8n:
                # Hide usage statistics page
                hide_usage_page: true
                # Webhook URL for external access
                webhook_url: "https://n8n.oisd.io/"
                # Editor base URL
                editor_base_url: "https://n8n.oisd.io/"
            
            # Reference encryption key from sealed secret via extraEnv
            extraEnv:
              N8N_ENCRYPTION_KEY:
                valueFrom:
                  secretKeyRef:
                    name: n8n-encryption-key
                    key: encryption_key
            
            # Persistence for workflow data
            persistence:
              enabled: true
              type: dynamic
              size: 2Gi
              accessModes:
                - ReadWriteOnce
            
            # Resource limits
            resources:
              limits:
                cpu: 1000m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 512Mi
            
            # Service configuration
            service:
              type: ClusterIP
              port: 80

          # Ingress configuration for Traefik
          ingress:
            enabled: true
            className: "traefik"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              traefik.ingress.kubernetes.io/router.middlewares: "traefik-extras-security-headers@kubernetescrd"
            hosts:
              - host: n8n.oisd.io
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - n8n.oisd.io
                secretName: wildcard-tls-oisd

          # Disable workers and webhooks for single-instance deployment
          worker:
            enabled: false

          webhook:
            enabled: false

          # Scaling/Queue mode disabled for simple deployment
          scaling:
            enabled: false

    # Sealed secret source
    - repoURL: https://github.com/edlundin/homelab.git
      targetRevision: master
      path: apps/n8n
      directory:
        include: "n8n-secrets-sealed.yaml"
