---
# SecretStore to access secrets from the redis namespace
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: redis-secret-store
  namespace: n8n
spec:
  provider:
    kubernetes:
      remoteNamespace: redis
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: n8n-external-secrets-sa

---
# ServiceAccount for accessing secrets in redis namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-external-secrets-sa
  namespace: n8n

---
# Role in redis namespace to read secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-redis-secrets-n8n
  namespace: redis
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["redis-password"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding to grant n8n ServiceAccount access to redis secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n8n-read-redis-secrets
  namespace: redis
subjects:
  - kind: ServiceAccount
    name: n8n-external-secrets-sa
    namespace: n8n
roleRef:
  kind: Role
  name: read-redis-secrets-n8n
  apiGroup: rbac.authorization.k8s.io

---
# ExternalSecret to sync redis password into n8n namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-redis
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: redis-secret-store
    kind: SecretStore
  target:
    name: n8n-redis
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: redis-password
        property: password
