apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "traefik-extras-security-headers@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - n8n.oisd.io
      secretName: wildcard-tls-oisd
  rules:
    - host: n8n.oisd.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 80
