---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgAGrR4lmorDb0hBI8SpNLDdCjRkwzOlNnylxrNH8+QOBJGjoMSxGAhF3R6cNE88g7i4CTjGqJ7Di1RMN2oj+QHP7NyZh7/dWNVZRADSWNmyvHPIbtdoTL/HnuWFInyGXYpCUdS/nwD/ofz4qhRaKsJ7YnKAzyK6JR74AElBIzpsDlV6f7u/LPDAKUzFDeDe3QV2VUX0x9NHexWGyuloxaTv14tkHIyxaSZGf6audVmvXkoF4+iUWoCy7o99LUITh0C/p6n5TaoSX0hKEzvSDTaP4SWyV+VUVdeBosdOpCEfCDq3R2748Egq3IauCYmYsmL0xV0xRGguZWHYYMp4S2DTZOtOgNnxGoTvgVOajZtNvyXNIU74T8ZZoI9Wh3F7WvBCTCfxx6PCE23jyjg88pV3LmiFaYjbixdScvUdQnV6o0O5qkXHb+3oNUSAG6IbxERLaaBMNUT5OX/KFtGFx28V8uywnss/lf8nVT64n+XpK3zkTJ5r6w6G73QcN4ajCUzqP2LtAh0ZQKT3f6Q1agCRYc4pgwu7FKc6M28DpWZjmj00HE1urJQzBCJUYs3oS+pPhYTi3QzdY7kNiOf+PXWCBp7aqiNRX0iHbkbVSUtpND7fb8gF6NkZf5RQH08HV2qtuW7IYdsIevJn+jkIJLA+AxDnjS55GGgJ5uuNl9eQzzjwMP4dcF1wjcgg6CToOtid8sHuHw7WF5O+tJILo/x92wKM38/vgukUqoCivfeAZsPUZKlclCM8bYRWvuHRMEBYnyMkT09FXvZD+uen4rea
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
