---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgAqxNs8Z/SPz/zlnGWuYKtQWODTQiYxeGVE9/A3UCt4DatOLLXbWH3U3PRghG3gCsi5elmCCyxhuDl0u25lZ9D+9xyCC8Bc59UPAav2tZmNxGXVuDDUC+vLpuhAftU7INv52Kj9G0Z/XcmxScA/F4kSfZgICtPdIYaa8KSKlErbe2Kf2Aumu8Vrh06Tlm7tSmyNYBc1TqPROikrie5bxN1rjGoC0HXWxYxlFTDlSYmRL9NsfgqwnVDZ4AtQheaAaibBATU35vEXC2Z9gXulUycAaO+3h1fuBvTLn+ZEsK5ljhaAlVarAVnqn+4UPJGADENZRNtLltTCtpZe+FArghRtoClraGuXHS/wRyupH1oTPuBwYLGTnGDCPrJ9t9bWq8m0kj7Q4bCOA2v815P22O/SZXmc3V3gTeC/mdjgK3pNsIBnRbgXrjXVpWmFRg4Pk3bN4zb06g2SMJcm7gpEOVyq4VIcVtqsbyUPcJAnU0b5F4SH0+exGxk+5j0aCqEM+LrdkI0WXgX0bIquOvGpEbrGDaKGJDbabdA6J3wyR+qtETUnRKUzIWWLmFd9yIVMY7yjCj8BmVfc+hplmWO2kln7qXYFl/Kwhh0QJhHjrxOWh/Y74sdpDjco0NAhQdBlD8tO2BlQd0aaM8scCE32JGo3NOu+bVqFwc6yqKGI1UL+LF9lkvCWGIFkvobweJsvjpo918RqPKU1u8eqxRD5ETjTdBxWRZR1+/koMJRIpmijW/MJrknC6IpyAp+FkfxmX2+Z9jLbd2NlBWYtWwK3m4Mp
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
