---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgCqTVcv1d+QTKXk+GfZ8uALSsRIWEPFfX5ujdiYWfFS5B2IVC5om3aeWRXwmLDG8FIqEuABXZZVw3B2B+G3b4LQ/ZJR3lgmFcom2rISLuj2daZVWafdXk6Ky3D1uwaontZmjLYuiTgQtOEerc7gZpRp0Y8wMQx71tSeasncZhxemcNyduVXY1tEnrvhdZDaXmsbtJjWuDycHyw0PRb/pHALtXuv4A6w/ckLBZ3R3iRLbVrzDdZBrgDTCMjVTYhUqCxol2cTwiNPhdCFIKhgaTiKm7cs0seQ78gNFS4a/KH0AzTQ2DyGPOdqQGW+pjVaHMdozuCq1oesTOYm2sq3viwtXUJaSA4KrNR5Esx6Lvtf1VC1JiJP003ykg1qVhGUB3jzBd9gql+XbYlLF0O37lTbwZRG6cbulgOFhnMf0x50+biNjmhbUTHO7eDOuPf6eDOzbMTkRNh3KPdijb2QXVP7ijcOJlmEEYJMaU96B93//3Ay+w47AQFe7MXe5IIrzGwDQgtGbZt86xGixS6/PZxQfFEpmOw28P9y/2eWAXzFRuPFdOjQM3zW8GFgGrLs5O2+dG9ZYs+fxJq/Dr6KUE2di8Exkoa3QkpDCfUThBfZnVeE3d7G8hK6bwZU54N+rm3gOC41Wtnv/cjGg55b9LCsC3OB8Vh8j1pwjh1fSrdHM7ucMzeFP8Y0gKSSVqj0gdZ2CMTTmDexW0Dogk9ug6Jf4PFrKhC3CM8jwrIL0/Bft8UTU9TNT5uA+nMQl6mc8Tdp4iY8Ti4wx2Lgu5dFlUyt
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
