---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgBkXFRD1892WEsbgMRgTHz+V84ibh70HBvwFyY494lKOEe3DMB/c8dS2wmkX5llH8UuSAruI99TgY/qQoL8QSvSfRoYYdULq29fwdNBscfOXVaDmYAPGhpXMEwvrqltQVWQ/nH8KG6BozorMGUZsspohEvyoUP0Oslgy7qtheF31nrtxS0Af0sG36ufTZIvPj4jtA1M3KUZofC+Z6+ZODNgCNaUoWrnZ6Kg53FuaO9MkvMHxh0b/89/tVD7o4v0XdeR5MXcG+6douiA4xOxYLBm4hXT7qYXk3W+cy3iXdDOZjG3oIUAmWzgii8E85/cPzR2iAuZBsKXyFntY8Rzjv51lGFQwSI6iKThTG/8dnG3pG9h6quN3N5fHxg06VHM3T1ty7Og7eOcovL/gI24ELN3QOe5pdgMD61yZqnBcmOBfDI3BDeJcOd75wAUDANH6/KpBkh1Dk+Ab3E3S9e3fQcXnXJlqdaHM0wgocVJcmo4OrXfOl/xNeBjcHgATAYx3xTr1MjKQfnjbhPZ3ct5+tL0IzwnSCOfRC6Fk1sG1kSzN4uLCE1MP279s+NQV+u4qypkumg4stp+JTQjgYQp2tBA/XhLKKN78n8S/k1XVL94hPRm7DMDCEMO6UN9GVbUgxjqD7hM1kHCSnwsbfUvXS2EwmZxkbEF7mpMesWL1Zoupxoz2eNnh2Vm5oLxMD2K6K6dhvoz3uLU6Eo7YlItBcAqB4+V9tztzEZghAx6mo0PLUi+ahJJnyCDkb3m8z4EA9Op5g/h5zZOA9zShd1axzba
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
