---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgCFEOZ6ngX3gDEGHWqPOtXmcYGsHkaCB4eiYbmPOhecHIpLancDqb8FNZUMSMucieHma3EqyemuR91qgILcFTttJRgVHxSW8SSb1iVyjn+GZkjncZkLMe6FrKdXB6hDnnyrx0TrWgHzHc4ng4U33BJkNIbBAw7APhpvA+HI6BxEyH+yAN++PEMbrhNl4P9yG9onV/pqYgfCIKbi4NPSDvH43/Rh7W27auvQ4Csoki52DplhYWQdQqlJaYmH/EJIhSzBA4A7YZk9kWZYa4b3lCisazsFa6xts0qy/OWfrXfe329BpdKgE70uzIqPaFi1KiBwjX6ZeTuFQTj0ENjpBPSnXM53+hioz4XrptCyXyARPimAe8IWS7xsdYRtZyxQhFGY6Q9JFKv+rbYeokHhR7z5UaXnaSu5NgkzGLAb7eORrCOeue+ITWkrznrrKD3gBUhJodkr2e5qK2DWz7xfRhYJvLH22LDZRGBW4iGpbNvLSLSdQNCfY/5oflhSHp23giVsngMFuYmXj9ceVIrl4P08BTS4mUp5LggsuEHG928edlliutJbqeqT0Z9b2CiLBhuFHrcs74MIvg3A7RKJcQfyZfRHoZoEBkc6E+UHSTg1rBLQkox1/gnboowFnvIvEG8eGi46cgCyTSeD+sS0pX4BiyDP3ETrt7cXwtMp0yqCO7kEOog+R+xdY5ebHiR1YYZKuGtuliHjH/NQpt4SeBiGlKQWXLJr8GmuAJFtaNuq9AVi/ot8Bu3UILQyAIiD6ZjNPGgosNYK99pPnNtuokJw
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
