---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgAHGV2Igd5TRwyFHpwstau5HAK8R799TkKw/07iyFs2VN5duGzIL4Sn4qTA5lLMK3VQSc5VupMhc4ROEF0ufFyLV3oBZvFNkfkqgmIWOmCzWbz/y3Pv40C+LMkycXcmRIXvUIvYOHWjHzyRUQs0+wdMxMPxDM56x3Hw7D45dYMoifvlam2Eh4g4YC4tTrQ46gjgnflBg87OSzhQG3HjBVNKgK9DVM2C4bx5T+q5etc5O1BoGKn2Q8BeCfn1hi7PG05ePG7u9sWA5L+0aN5qoDsG8sdV3HvTPGHMqNr57Gkfj/dJoaBKnF3Vh35z9m6nmgRvYuQczi05V1mIQ0djW95ToNW3/JP/p3yWbOtsjwnVRsGqZmbzi0z6LaXGuHlC5magcHjF09hxGb2d3HeTu8gFiqRsPFZIh2xAsW5UTMkzm1kl137CeTGXeHEmrELiFsub6LFElfC2WKdy6KnBhcfOU1UIU6yrxnI1y0TtHPLCMxDLdexcedKLo+hmpY4s4TZWaQP+UF9+nZH4ARO1G7Xzn21cSficKb7SOKQ2C0Ag5LExniDOFwMoPXk0h1Ymq4C/w78hayCZEdsv5s4gFkC+qZeEmsx3JK7fk3zzqfhmVmWu+filVeadeMtAKrADgWLyGrK/E7dXWsoL5vv3T6IRXDPf64bUiANsdIKQiAnxvWff6JBrY0rQfegiSXaPoO0kKeuAMFVr6MjFmf2sqIQoi20Ts939XDSpsWfHIPsLEBz0lyUkgq07pZKd3oI8Srld/pxKOePfT4U14H2KaiwH
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
