---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgClUsvJk2dlViUB229z4ilAQHraBHrEMb9zxtBGE1DurjSbq0JhPcrx6B3DOZ288ysKUQxOu5x4Rs1EKWAsqFNRdMzs+aak4qOSm8MloemZsIsX6BQjR/NsEXb12mc48A+ip8Cjanj/pOsteNkJkyC/NRmiY6n1L93VoVXefPUxsNmS0nNpjMv/f4IBYrYh06iSwbGJwa3cc0MzbMIRUwsO8lLHNrV55KpfcJxFEO7y3KhTmdbBLto4uOOs1SotYsbsUEBNWgncFYvksxYtP9+ULPPYE2YheZDxEgI22WApFDigVc464sDoi2Dg41w/IDCHu6OzeJl+CZY/VFRoCAWOFRZLBu7z9Rnor+adr0JtZdkssrkAAad1H2wihvk4+xx8QlvpzCZN28QKB7cJvNLWwxVb0ViEplnw55BXuQQL3Uol5CWzQsx9j+VNq3LS8FPYWLMI/TLIjRRYOuTKwXO9+UMjCEp2DiMKjrZ7runXVf/KdvRVabYrOhxTvZoNqJFEN1E7GcBHae1EX4JUzko/Y6A/ZmSGFl/dkB+AvpumNqGFfCIRU1uBGXTD6UCzuBYPlqx6BnNZiWu2+XneBhWbE/fvPinGJdpDm9SAV+acMIHgLLAWB25KZn6SekzDG0nz694JvVe+yrin8OvdRo29RkulHyerXYW5BHlhRmelbHQLsXFCiQvhYOexu1pCeoO4iYsqHBoxOvkN9ub3rPEgRetJpnYUm9siXnutMw3p3Pmr1ci5qluPVwuyAT/3Yromj619TTak6shlGWklb9bP
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
