---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgA/MWgB7IIzZhDZnyN1ti2FmqsBrs2rxNDcqBmi7f8m/ikcq78CEBG1bcWgL5EeKBKOXlpHPBJ7nKPIj39yDHBz+itM46fa4Y8OvQDRoTm79529KoFb7dqvMWbL9OrmNSkduU8EfwK8V3F+3DApoEOWN9OSe+yvSvJfaH/lmeA9ocUKXP9iZJEUgnpRlqU+QyjWTFxiE21LIBXvAlaiM9vB2dE/hPGH6rqmX1hWSPMq7EQIrEck7Gv5r9g6FgwldZwwdwhXUDcxQeVAoFfngsTwvumzHJ2bMfYY7Mrlq9ManvFtoCQo5qgsfkMAHBbKMyqlqE71BNhaMA6/3NYj4WwJ/Scv4JfGYAIbqOpBZllX+fpcwaZtLM1Yl7/cfz+u3EmpWEP9zmLL6VyHH9bpIsP9Hw680uIohFu4i1NkvSVQn5v5Ihtprb2MxbjSmg2yuqrrzTNtvTfybj/0nWWrOuXe2JI2KVhMj/fwyWD/irEZwPGKzHIwd0/3MIlsRrwHGZ6V7kxByJIW+gSBYrmoQLBJ2e7IQLrj3o2vi3msom3SGpjfQJfwFK7YhLST2GjBNqQtonecA0qcMQsUe+JEB7pUnipH/t2NUiK2/uE0eDKawvk7f0KEhtugla2SxYvk5YnTn8HLzY82eG4cPMgGiK5BKighDeU/wVPTuVPIWFmRsFrB1GeXre9JFKbHyepD6VXWIjmcDzNi88JQkuaiqATOcLd3iTv6J+5s9diR+DJ0Dybgy2ZNDmyK+SLPiRCok5mdnpMKrUYEP+cp1ZRvhxb3
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
