apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-data
  namespace: actual-budget
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
