apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subwave-state
  namespace: subwave
  labels:
    app.kubernetes.io/name: subwave
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
