apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Use TrueCharts stable searxng chart
    - repoURL: oci.trueforge.org/truecharts
      chart: searxng
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/apps/searxng/values.yaml
    - repoURL: https://github.com/edlundin/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/edlundin/homelab
      path: apps/searxng
      directory:
        include: "{external-secret.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: searxng
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
