apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searxng
data:
  settings.yml: |
    # SearXNG Configuration
    use_default_settings: true

    general:
      debug: false
      instance_name: "SearXNG - OISD"
      contact_url: false
      privacypolicy_url: false
      donation_url: false
      enable_metrics: false

    search:
      safe_search: 0
      autocomplete: "duckduckgo"
      default_lang: "en-US"
      ban_time_on_fail: 5
      max_ban_time_on_fail: 120

    server:
      port: 8080
      bind_address: "0.0.0.0"
      secret_key: "490ade7c3073a36b9a7ffd5f3f4e228c93fda403236449adf41ce5ef52d2bd4c"
      limiter: true
      public_instance: false
      image_proxy: true
      method: "POST"
      default_http_headers:
        X-Content-Type-Options: nosniff
        X-Download-Options: noopen
        X-Robots-Tag: noindex, nofollow
        Referrer-Policy: no-referrer

    ui:
      static_use_hash: true
      default_locale: ""
      query_in_title: false
      infinite_scroll: false
      center_alignment: false
      default_theme: simple
      theme_args:
        simple_style: auto

    redis:
      url: redis://redis.redis.svc.cluster.local:6379/0

    outgoing:
      request_timeout: 3.0
      max_request_timeout: 10.0
      useragent_suffix: ""
      pool_connections: 100
      pool_maxsize: 10
      enable_http2: true

    engines:
      # Remove engines that might be problematic or slow
      - name: brave
        disabled: false
      - name: duckduckgo
        disabled: false  
      - name: google
        disabled: false
      - name: bing
        disabled: false
      - name: startpage
        disabled: false
      - name: yahoo
        disabled: true
      # Disable some potentially slow engines by default
      - name: wikipedia
        disabled: false
      - name: wikidata
        disabled: true
      - name: currency
        disabled: true
