---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-searxng-config
  namespace: searxng
spec:
  encryptedData:
    settings.yml: AgBLC4WwaCPAaL2TFm+ssCcd7pok8nzGMkRQApC1WVt6429B+Np4Vzy5Zqhtt+M9Wle9Kbz1n5RSzoJcoh9F9ki8SN9upoAvbaUGgpDmIlVxdrVglz+U3H/9hWb2JRXnzjDKowM7IClWL+qlzYscNRSrw6nRUob/nhTPoc4n8ueFtccxY1snQk2/GFWjMi+WfG5ZOukckFzJ92M1P6jSCYpIONme0+WFR3k0fyGwKgJ/wIRJB1ejz6E3T65ac3TkijLwWQ75h8MUIv79vIYYpME/shBRrTX+KwSTtlIKnHFkUqISrEFhsiN6AVcQcBdN5kXZ9O/vgFy51vlQZCwgePXjG9mlzA/fDyao15RIwgGMsx495zw6tXeBzQDO2Kkg0QglIXGPRb6Lvc9kWxpY5/Qg/BlR+wCXAXQW2YTztVmQfeOmirRqfryoc/gb5m8GnZ5gChMOg7VPL9jSLkZN53AxJj0p/6plPg8hsesbmUNpqkCJe4YaGYbCpHidQ8osWA4VTS/TdHsz0BxIA2i4J1omVezzXatcpqGkbWzr1Wichj9YJYEiBZkcf+VdhEy6UG+zjNLOXOtgeF5jjHYmxHgptFAb4P6ufoct7qMcmvgX/avTtGWCyvpCb9nhkBlUrIZpiwKwL56pthk4Mkr5dCoWMUPdcRQGaIbMoNsUtNxaIFMFvWHs1KYGaBkRZV7Ia2MT3l3f4sYle6bOXa1c+Il3F5PnZgEHetxBFPzIOIJ2fgzjopsi71wm28RcwGKVm67ctGwtVa/Ufm+XPXlLQpUdBj8Vx6KxIJoNWxom5fU4HCskoBO8wAfE9x2lEEd02SLF3e8fRbydAUDZOuo87ZJSIXgrQN6AsXeLB6fhmjiSDoTPlYABVruC1aU1rs90RoR35WFjtAcrgmRr/pMQ2pLAZKUz250cH0qgTYWWRMYCCK6/1R9WoAlX/am9RsqWnOsuo5/UAbpZ8erUNSFEEpfzerwhUE9/FKYcy/Cbjf0H/x32eftJ02ABJmmH4qonEogGGe+ZYMX/NrN9j7t9s9aLtS6nLI4bZNMrm32v7AIcwAYvIijRgMBiHBqpXggKF5jhcTUFYoidlJshkH9WoosEZkVrFdmeLWm9ZMjZXSj1SbMnw06wiQor/YFi5I12EV1DVsKYCtcIbZdrJPNUDvHCmakypQyqLeeFJ8FyStEVji2H2vqWT++wBf6pMA==
  template:
    metadata:
      name: searxng-searxng-config
      namespace: searxng
    type: Opaque
