apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: music
  labels:
    app.kubernetes.io/name: navidrome
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: navidrome
      port:
        name: http
  tls:
    - hosts: [navidrome]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slskd
  namespace: music
  labels:
    app.kubernetes.io/name: slskd
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: slskd
      port:
        name: http
  tls:
    - hosts: [slskd]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soulsync
  namespace: music
  labels:
    app.kubernetes.io/name: soulsync
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: soulsync
      port:
        name: http
  tls:
    - hosts: [soulsync]
