---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: musicgrabber-credentials
  namespace: music
spec:
  encryptedData:
    API_KEY: AgBSQ1raQPeC7upwBqV+ygI3CbnfKmwyEHe8dzwavI9sYdjeDwXwpV/7+6RIkGU/zjI8SGkoYstG4yYV7Jqu6eWTFJ17kVfWIaqrzzc3uTMdNotrsys4cj5PJBbKFqY71zkHooBPXqaWjQZdI+EFaLWi94tZ5INdaZA1BW6S4s8R0/4QLyp1OGzKFCRl05uz/aTxz1rofTjSAzzvp3JKKU8tEFUhdvB967KfcpTRmwype9mfsK/lkHh4dlTwHU6uMEOznoKwN17eqkPlopP9VX3Lqmb8/WovYNiK4hv3DgCOEjjjdOBx5sP8Jh4vacSwaVs0HwuYZwOTOvca3g4XCIdjaoFTEQEhncxcrx9PCWPu+St0jeddipu6YCm/2SDsjO7XI9nUpMihGwklXOGQMjdwIQm63pMU4JpOCHl4rM/Fw56FMaXMVWgwx7asTpIwy9xJAd/lcawGXHqxQAbs/GYr2ZHffylR4HP1R+dLuM2AOb0/svZ/738CNHd0TPzqsNnhcHijCNeCa0e0mFUU0CWzN48qNTmZKnXVpvPleRJUcbTTN/1r4qxAqbNunS5aDUEMmpspWU0hhxh9sISvJKhxENocFxRjXJSyIdaekOmsQWy84Pd77QT2zA4V7KjrlQLUVxDtl4WyKpkeiTCRZIlaUqN1HyE6B0srzfilWm3n/TjYHjlIom/v+yRvURElaqD81w2kjkhNw7b6Ex8cJEVUvOYytLAMMo8+9jEMA7TAwAWTF8O7vSlbqkigOA==
  template:
    metadata:
      name: musicgrabber-credentials
      namespace: music
