apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: music
  labels:
    app.kubernetes.io/name: navidrome
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4533
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: navidrome
---
apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: music
  labels:
    app.kubernetes.io/name: slskd
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5030
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: slskd
---
apiVersion: v1
kind: Service
metadata:
  name: soulsync
  namespace: music
  labels:
    app.kubernetes.io/name: soulsync
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: soulsync
