apiVersion: v1
kind: ServiceAccount
metadata:
  name: qbittorrent
  namespace: music
  labels:
    app.kubernetes.io/name: qbittorrent
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prowlarr
  namespace: music
  labels:
    app.kubernetes.io/name: prowlarr
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flaresolverr
  namespace: music
  labels:
    app.kubernetes.io/name: flaresolverr
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lidarr
  namespace: music
  labels:
    app.kubernetes.io/name: lidarr
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: navidrome
  namespace: music
  labels:
    app.kubernetes.io/name: navidrome
automountServiceAccountToken: false
