apiVersion: v1
kind: Service
metadata:
  name: nietzsche-wirebos-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: wirebos.ison-mirfak.ts.net
  ports:
    - protocol: TCP
      port: 4000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wirebos-ingress
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.bos.oisd.io`)
      kind: Rule
      services:
        - name: nietzsche-wirebos-external
          port: 4000
          scheme: http
  tls:
    secretName: wildcard-tls-bos-oisd
