---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: atuin-ai-secrets
  namespace: atuin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    AUTH_TOKEN: AgCX64vdBtN4WMVO2TTkxT25u5pIRNnZF5AUroYSb2IjjEN7vairdDsZpTnBII9bt8Li/S1+7xgXK2xgN9jaoESZYKzHeGCPKP/7Hbpf2OdAtG5hLynLYEoWMdis7Od7BbjpMAyu9ytKeOpD3RBh3cDXxVecxdHzwdXq0mI+dpD0+DCz9dCGjWlUUfZxRTNOnirXSCABH9Zynhy/01CsHNyn3cxiJLImbJ6dW3z3dOJNtyTN7zZKgQZnAnKAuLDAsi2ZatbRMZ2Es9PEDZgEcytRHk4lTIkHUI2nAnnmTfhN07VfmkMfr2WXL9urtAmhG+g7GyQpLDMlcYfQ8OVze9htUkBZDU+ZcM7Q1TgjN8YFnFA9ZPiZMbFV8DDIILjQUIJQQliZ8Oo4Pj1Eedk8hCEqaaoygqYu2sqPh9X6fkf/M40iP1ki2eJXmupQlOtNT7c4tiEZq+v2mrLlbhfnFP7zlHTXaxLGBpZCzGjlPKlLV7KRg8oEk0u8yd/IeFmtuk5F1WXCzv95WEO3c+k5LkOA6OJ68TdR8mNQTnIMGXOeKECl5f9hXyOBIMUtse1WUUbGbDAew8XiueUqamsQUlDWxcsCGPWrMbsBqGRQ2FJL4rqAvx2uBziEeO9XbfKtZmN2c7EYjYw+1EY6y0H4uq/VX21BDknBm1V0vrbOAePhciZWd0r5S+BB6ETVeQNpEDcCKJWWaWKRrkv/08ntF7T6ahPmpj4kKG4F8lzdK7teFeHNrNfWiXyOgIcogOuuqvRhskwQEKWkcAwuwvBbX9gO
    CHAT_API_KEY: AgCsE0o3xHlAgLMpGsSu6ZuPUY7xBUl+FrnUAj01atjjtNCLfrgRV21/MBey1ZWzccauaASZ9SCNyRBLfM3YtVsGEgBfpj3NwwYBeagMfnIfq3zX1DJeJaUKseorBvSKcZ5o5O5UBdj8fSoSg5vL4heLqJP3U4AACU7qHIY+oVZVN5G8TlCFF0AUa57OwjLxM80iRoSlarP4PxEFFE+vdAojKk/iCxffky2/hBmTe/MrSahkN7/eand587Qodbq7++asjFzh+pQrTKt4gWDV85MDdGKp76md9WDx/WHMV9n/TX46rUOIPEOyoC4OfkVi/7v4ZQYwmkt3kzUwodRFhFQMc9JLSTwaOKqJxUH72tlVP/ztwlNZeTb0dlfvzxU6YJrYn48sIGtC6QLydEM56Y7SWnJQ3PlkxDv/aCegXEwbF9LTDmWH3x5neTgjZWOysdbQdH2ieE157vUaWJtUofS6sU5J/jDUshEnhpaly+tbarYQNHsirVYE/nnLnJ/RvB6R/Fbh0COOLfHKVJ+p8iCcP46Z92lJFRs38y5HtWbLmGk3U5hZ+SRbsKJhIY6E4+Vu0zdJPuliGWrGVplrohF6vF4GKe1ClpBLECD+itCI58a/WTGGki0Kfu2vQCE6wFWT2n5bfIv7xrHBnaug1OQ2Sgt/4DIsJGlPHCDcMlZJG99SQrq3HZTr/zVLBD1oTHQqnQsU7f0FtAu/VsEC0UAQ9ZP6UvBRUzG9bAbYj10o04iWUA==
  template:
    metadata:
      name: atuin-ai-secrets
      namespace: atuin
