apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atuin-ai
  namespace: atuin
  labels:
    app.kubernetes.io/name: atuin
    app.kubernetes.io/component: ai-gateway
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: atuin-ai
      port:
        name: http
  tls:
    - hosts:
        - atuin-ai
