apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: postgres-secret-store
  namespace: atuin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    kubernetes:
      remoteNamespace: postgres
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: atuin-external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-postgres-secrets-atuin
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-atuin-credentials"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: atuin-read-postgres-secrets
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
  - kind: ServiceAccount
    name: atuin-external-secrets
    namespace: atuin
roleRef:
  kind: Role
  name: read-postgres-secrets-atuin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-db
  namespace: atuin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: postgres-secret-store
    kind: SecretStore
  target:
    name: atuin-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ATUIN_DB_URI: "postgres://{{ .username }}:{{ .password }}@postgres-postgresql.postgres.svc.cluster.local:5432/{{ .database }}"
  data:
    - secretKey: database
      remoteRef:
        key: postgres-atuin-credentials
        property: database
    - secretKey: username
      remoteRef:
        key: postgres-atuin-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-atuin-credentials
        property: password
