apiVersion: v1
kind: ServiceAccount
metadata:
  name: atuin
  namespace: atuin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atuin-external-secrets
  namespace: atuin
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atuin-database-bootstrap
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atuin-ai
  namespace: atuin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
automountServiceAccountToken: false
