---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: 9router-initial-password
  namespace: 9router
spec:
  encryptedData:
    password: AgCD5QYj8MmIIAaWxSIAVFuYWcccKHn1DMvKAQbJ83K/32bvcK6X/M0aRjZ0Fh9aBLv9xk5AixUafglIN0vvOiNZTJy57bWS8wBmA8LdGEpP3nGFmgvRF7Rtel6x6ztasibLQT4IsmC9jILZoDbsUvYaC/2BRQBQqysDr0Ji9cG6Eady0Q6jUA2eW/IK51H9Soq4O6/o9Gzh8Q868H8thAR/1FZtIDRVAvXy57+feoKXBpu3Qz2GGu4o869EvonQWN0I6MyyMKKG/QFmHIXNopBY/x56CX3/HJKUSYV23wswdn9VH7imrnrsKnrTEPfcQ5UxwxBA4hRite1JAiJBt+kqDoKc+y7IYhKrjpcedKZEDXv/ov+9HiX34JfmLk7DFMBdJmpctJLGnduAgj97FGbbwYxnMkCWrfUAmtvFliBjluM3fdEqZOgPK2cGlkhlBMW6j9FnHJHrYJb2e8/ePqkh/rkyJR3yKyGgpkV8gnKnmL04DUHoK5lCtleKZ99J95h0bpWGk70yYeQiUPB4BE3uWwSDzEnI32JQD614kJ/T0Pb96oG73zy0MhYZoSOSVOj14EYwbJJENN73POQLycvTBF51QQUvkMJQKtvF7hVtUaJlBgZFrE3+Lx4gUW+rCHWb/vftxnDQw4drgNLTg7UApDODDfuImPJLi/kFLvnIFG1tU/3I9fHHu366GkxPLnqKQwdTcNs7AXWK65knI6EiqZvZ2aiXUoszMo7fgK6PE4ZsfV2n6XtMNF5n
  template:
    metadata:
      name: 9router-initial-password
      namespace: 9router
    type: Opaque
