apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 9router-data
  namespace: 9router
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
