apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chatterbox
  namespace: chatterbox
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: chatterbox
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: subwave
      ports:
        - protocol: TCP
          port: 8004
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
