apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatterbox-cache
  namespace: chatterbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

