---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: full
    autoremove: true
    autoclean: true
  register: upgrade_result

- name: Install basic tools
  ansible.builtin.apt:
    name:
      - neovim
      - curl
    state: present

- name: Set timezone
  community.general.timezone:
    name: Europe/Paris

- name: Display upgrade summary
  ansible.builtin.debug:
    msg: "{{ ansible_hostname }}: {{ upgrade_result.changed | ternary('Packages upgraded', 'No updates needed') }}"

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Notify if reboot required
  ansible.builtin.debug:
    msg: "⚠️  {{ ansible_hostname }} (VMID: {{ vmid }}) requires reboot"
  when: reboot_required.stat.exists
