apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - pvc.yaml
  - credentials-sealed.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - tailscale-ingress.yaml
  - external-secret-tls.yaml
  - network-policy.yaml
