apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cliproxyapi-data
  namespace: cliproxyapi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
