---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgAt49D7AJoAZwY7/ULrkgu2az/YX8bW2Se7odouFG2mHBGBhvMONM1B4AljxqOzQu+Sz5RCo40YrMep94OaPFrLr7SDHUBbIFxf8Ekn76IKhwM0vNPRxd8MVG5+T/Hmtda+CJ+rPL9x/B+qXqm1T8pmZIET83BzE5G0qb0GAFoxZwNNMeLl0sFvVqp7zvZ5J5tO+3S1BYu807fH8rlNl8DujNGkHJOjpUU6yuKyPN9G/ANi9DYMyAO6CQDTMH069jC6pDEBopQK4FDPdhCIHI/iRTDkKveDK+CItXi8raBTL5DFC8oFtXG+ReOD9Z3zXEp/VYXri+hTcM/NVT8TwLAP4IMopL7P5T2mJ3+Etap42Jfoq7wHm8RhyGfN2FBEzEjK4BVujLoDsGATzsiz1B8OjqMSLZOx3hYSBdd7zahhotd2LNXFPPGrr6ziEqA6jTfvTfJiLDlf5/KALnHRrppYkejhi97oRcfmKnToY7qFpAs1cniascLalR4EjSPULUvmR3DA7/E8G8EbLFoP+bf7mkY7LPXkNiC7KFi2T6rJbgfmTpz8cP3yDffpYIObCgJlZQphOn9vdlbQyx8RLD57QiuNWMoBZHgneLyZbaEdSfZbOLIwsyyg2ccljUA1Vxezy6232lY0bovITQA7s8eAMoDOfO6CP3U2utLXp45iT3WKMKaboqjv963Acrgm99bycLVulTm+zIBnjDTwkYlnESlVB2gkYerRR11DTcetmhTTTtLkqCBrXzi6ufs3EH74YzrX8vZJf38M6rg=
    server.secretkey: AgASzS0v6jD6HEY3qesOAL3oNqpuaRHC9qOUXWMaEH02QzELacoM4Nf5KVqPiIuT2HAl16ZDzX6DkTcojOmgdzbgq3vaLqYYc6+TaPnW9qHX3RnQViH+yWWG+NkPy4/32IVGi/CIB3iVeMfkjpL/2moprx/gdq6uAFNz5/Dn9xIU1LCalangctBlqjnxCxOSVYWLvM3yM3+dVuxwscjrKDwDQFguuyi98ZFzJ/OsjyOcIYyxr0zQDUfE9eDnKuMfB8lNBX8S/snqwIIS7Boro2hHmok/DjtNo2BajR7FeFScW++qatekw8SssiMzRY8u/M91k/KqSlIZ+db/XPiBFbaekTg3i+dyCvYO7fT895YB5p8U1EtMtxJi/s1j/hxk1ghCjrbjGGvhRKH+aJK/B7aM4ZEwB/DNS1CFRSPAEvpa6BHfp4WMjmQ3o/IPzCp6J3lT2Afk20idyejg3rei/xkfTHAqhRDup1M6QfV4R1nTe63DCn+tCarNWDLoU4ss04eA5K9Q0Hm6LTR7HG0tdT6ZiUIrkv2ZPkd9Tb88Sp6qpcSOWpna4++gVh3sDmKxQIm21eUvHp1rpHtJ7aftxTdXGG84YRvod9weswJ2nFMi87fQSrB1AaBxrvBzU5aXSPAGWQyy1NEK1wxiZs8FbY07o4PZ0FS/H9e4Zegqlmfivf9ByW1poGmxdwox2gjMcXhUlUWnXcF5IUtB7zmX5AX6kP6aw4NPHGLnPGONnfJqfTRKF15SACZEYT/ERw==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
