---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgBxYVa6hF582qzr35qcrJrZEKWArgzmTQZoj96EoBqMHHp/CQI0TQ4fDMiwd7gzl5hRkcUoVFmnIUa70y1OJEMlQWyNBVVMpAUnp4GF1/AiRXulCvD1pGVo7fYQK/a9+694OrxjYlXfsnkJZT8cEFji9qQPYDRpuE9UKRRvL7nGWo2nur8YOnh3XRiRS7mSXfelv7bA0fnFyuslibezfnLi+1d6U19t3O+BDy+nIh91/3KB238HOwf0rfDYvJ5HVoNo4HQRIXfQOuzj3nugRZWjQsS3wyTHfbG1qTLgraaLMrZ3CRlJkSZvLGELOie1gUrUp4yNjB6iRfuYqcif1URSzlG0MimTOfwbCaaqc2Msg9u2ixg5DtEjhldusXxPHjBUlSrCnDBOgXhnNUdfwCBPUgr+a7zd60OWHul5MSvR3sq4s8VWAGputd55ml5RSHLOmRp29jkVOIEPaVjYUmeUOaafoUQfzQZkcfXOhNncAjVaWvWJJgBCSTy+dlnDQlbE9HhKlr4DbgR/euqu/3fwRa7f/Ib67s0H6qJA0WhzjdXi/wyZO4H2bjg1eHaOGQpwEYhOD0ylJt3fgpZHHD7Jz3j4yosTTFPtiPPMEs0ljNntkSD4dJ+02W7ciW55cJN24zxGJv5SbdF1qz+8csD8jTNvookvLJnUOF2M92ZgEg+Y/FN9qnYnGC0htxl86SKmWJTE/df85GgFZhf597LZC8tp1FQQwYycd7QNOwhr6QV+3mMrKScQDHJlMzVdeOv9ZYLf+zUnAnJd/mM=
    server.secretkey: AgA8Q2HxRKSkNQCPV4CzV1mLVn+zfBfBosdhm9zcWbk+FAhbaNWhEUe6bxgT9/TYB4aya8qyLL6weZ5NbdsNMPneTygmqhTGLt6vrHOc0RTABUGqtWJKG5KvT/DpnOqIzJtxtLrihYgYw9MITwAwMuLs0urHqasO2IRkx2bvwbqOK7OZPdcJ8F9enFu7yv2RoXYfB0UU2O1/afJaMe9Suq1vyuy+42PWZ+QHYbkZMaSHRDCY8Bh0/pVAl1l/+hTZSel+kiZNo7RW1Azt03KrJT2fJiyfoNQr+Bc6d/jkwhH9KgkUs6OJNBTEM8d5rPhoEjzB+NGM3OYg72isu2HlUn4B8NDULVR57LLrQqVSbgRpxJlEjjBCjKZ4kMJX/wn50wasuRQ7fAv/NibRXDO/cD5u5j0l4vwc3OItV3tyWzRcw69sef7bJj3HKYo+iQhxhKPzMu2hoxnhtKqQRdrZnw1A8SooRdqeYZCNHBNj5I/quf8y6+4RW1O+d4wmc5HUHHBhM83BpNobTnhSKrH3ojHW+SxviSIqFjCVQLSGyfUa2nepHdMjx1Q4S95bUJaFroPjKNJFKt7zH5RqTZ3Ja4UvLKGm6qKEaSn3qm7DAJJSJAF3WeUOZpDf/z9GDjDCyzYgfVIdZE/5oghlN7dmNheVis0qWRlKLTpANhIeMN23Ios89t1djFkZRG7Z4h2OXVtCB6acnPOdc+q004QbWTMmpoyg1deBJt3rYCVZomJ38NNSC6jTi75MGDzJ+g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
