---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgAY2Nskp46KhNB7bGAsPM0Gbf1KPf7P+vgyCZ9fhYCxhChV6VwR7juydodmb26+oHdnr+oN2uvtDvDkNU1QbMbGvGY8DMcmQnfxOyJpRVxBk3w1R6RPQttSZFMJCoAxsTw3fOcO5z083jdQuPM0vI4mTVaX24AWt2/AwqVBskhxqCISqFmpnGFJdDF1CRqifZxhO5oHw6DA8rIC8Ns73iuZDmiwlzuN1w9LuxI1ET0JjyJFemJGLbviD+LD4hPThRfcGtGNsJZY+sOhA8tz9j1iKVTNd4nv1M0AvprSy6EyAr4RpnEio+zbrvmikWnClHJLQSXpIUbJV8amGmV7ZYXensYz9uxMzHn8WfiBE0B0TfmSH5qItugEVwJvdgWWqZYYMMuDcaGo3rkuqrmzyk1hsZT3OOP4a3oPGd+qqxE4GYSPzEAKg8belZacICZWCrjzf2Scypv8iSjYHcWf1NHcRgCD6e2sSwo7hO2MLFNRbt0pfxZTqT4OwppFKhVtG0weY+HvGUBuIY57vtqCZGoNlIDjY2luLcgpIJMG+927aikRqlSvvLJt/l2pGS+uRpxMQjFmpWau5mU6fCnUEyhkwP/oMAhXzNth4GxBAgLgyb1DhqPjW00kTlrU9klY+aGJcyj7H3wrcfMhvON+eq5d5yHgxIIf5xuE6Q2lczLVOot8DW22MWQ9a3IJNdISZf/k2b3KTUhY9zuUPn/tOVPT3V5376kc5uN8C4JQqBh+MwkvqJehZ/4YHrAXIFhac1FzyyrIIgivCRCD42g=
    server.secretkey: AgAH7JteTxbiCVrM/WJW18b4TNZ6cqy1ojFJHqbvWubMky86p1CtaqdbUHuKmZJ7mYUms00GVTtJkjqn/f3zonquwQ5LhhqBuej6MiTMYCYOKjcAIOcEofKAUe7ibLq6GvblVq5Ef2PQV4dKrtwqTOyH6yT/TvM021UfWwo0H1M+KJxV4WKXuYUYy9NCKMjrglPVN9tsBUB5MKSZkUf7z+0j6Hy00XtqW3MCk1wvRIgcov5zknBJxdcZ+g1JCfwUmZlxv7KMt7iIleNYg+xkkvxQ+gaPbC3Nv8BUt9u2eoYsdZzTxmwB6+ArUGDX+yEXvRsTVBT5luOFbXG5lRuCwrg+WHgdt8OVxTCXcvmmb7Vj5Wgrh2Vgy+9khGtT9SEs80TYmACUSHIwUDOCRNHhb/EqEdOHdM5ae8JyA98GpoeTvzWNvUEBqJ1+D/RjVH0Zi9sCwfIdJvT+YQPB5cEfaNCI9QBM5TK+fDw8oIDxMNKbErWg8HiJUO4FPTLd7+HblogvOjyFF4DoAzHtPECqogbnwnhFHWIAJ4HhBbiZgX4AnFtW/jcSrTKNG7uHfCR6wF2fBmmIkqrw49p/xQw8E4k/vlLSU+rgSY9OjJ5sN0vPSMwmaA59zoacgXc5W66vJvzNhq74RQrOJg7/dNIMEezbXBjKoZ6GQwrfh/UYkuwOhhuVuyn2FXVPaWmQyGmb6wvVDkE4wCtCRAtada2AJNUnnrSucRI81Zl1ef8xgOilnU7gK12BXgO9YTG3tA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
