---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgC1Z+Bsj3QSa+fDkNdwVnZkpxLOFf50Okvc+kdz88z5Iz4MrpBOcKtjFH20KcvGAiHwOz6QD01ojLNSDSe6o9oQbkSyLcsJKGQndd6fKHnJmlYbplgzJeBTnltmLVw2BWbLNsFrIEwdMc4gYk2KXVaHNXwQ6eBt7D3YLTKQve/snnvLUpMFSwHl1gIuZMK95la8hDwmHxdArCg6qbeB02JSy3uOGycZ9YPL9kHSV60ZIyrfAFGJVtat/GYzBDExutH/xgWtNChImh3H2CbI5tVLbW5ryVZDm9NSv+zBWu3hB9PPEgRVvwhnwQDmt/HhT/66l0ubPX6Mo3HvkR5QW8Y6YKWCl8OFTxNDQ8+ko5PyVgLiZf4bqb6sWqaaei4IyxpNgCDUTsDhqdZCE49uR7SpDw6AmpPm9NNbFD4QYgjF/hj2O84tNpu/4EsmokM7ucjF9uyZ9Q68CZse/IMX7yFfy/B5a3m67iHiLn0ejLkIrTdJ9iLKVYFDIPPRTDgXXvzo+70b+AWl11UCCNj4jcwksrFuyxqCqF6msfxFxjReGGzWjSva56ZIEAeho9b9bGKBBdv4sKnLjZA704kF+WlDBSgtJ2cBg0ff3u6KGWX7VMtoI7uMVbm6C8RmZ+shCyMqKj2oxHejeZZuoJRlAEaUUWjs+ug3gwobm+fdswRbGDT8eqsjRNEDeQblGSMlQN4JiyyGMwoVrXBZuczaa/9Px+CKY0SiJGRHuRHxc0d0HOsM18On5WLhGl133r9DALb961I69Cyf3l30PG0=
    server.secretkey: AgDGeRBCu5Qps29tE2e0pQxcsH2mLHYNlvDqvbs2RpXfaUF7QfhQdVeTWSzmK28QKCItaTaXRHQZnvCHVSFIjATqsvhRBPH3+vMgwozW1HNzfFf11bBjnTIQq1G2Y7X4LFySGGdrs543Hx0Yi8NynEJFCm2JL0cWpA1qgzaYAVwwZbOfrpPSca2buCbDEVI1kSPGXv6O1BBKQ/VGQqhJ7CZs8JMtn3BSiQvXFLo8LIs5gmxrIwYX+gQAwxcQ551bAv7AbJ2PtbB3GLLbwB2is7ZWSPvON79bSmqsnNG4Tg5fWfqsPCrc8RyAHHHR+QRzXuvV5TEeMYl+JysILuIKUGqbSp4SpgLRbFLBiYNKqA1366qmpxAzUi1fh4u11Qyt64M9H6S4a+jUTlgw9XWlDw+qgMOqaZGc0c64ZhcNk/+6mTBh3Bvs+RGLdr+Ov3hhEltywXnyWdgs9cURKGeseaCfKLo8HAVoSEoF5Ty3t3JkUpusJ4kBvj6IXYb8HJ86gAFu3viZZ8Yc3L8X8ztJfhIcNnJJXOyoCCRKuVc+gEyiS4mVToFVbJ5wiqbKcTZwdXyuN/KAmdF6PR7Ll4D4qyhgBVVF7en7HLX6MEjV8UYoBGFH9vKNWcff8R9xOGZRVA5gX0pgcl9I4Zl+uPhoU6IjVd/rMjQeLR0TLhZoLP1gvbGCppF1KnKKm3/K3+R59fJlU6/NJ2DPTviW7lRYrk0l+VkCJnLpZyTfstsElMZ737WUCfxk9DI3Cn+Ong==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
