---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgB88YydYDhGEjel95cp2UImkyACkF3upIY0GtyQcx87fPWDrz6QE1PdEHSgXlX4+J3m/p/cyyfS04NXuWCmczuQA+4R/ucnXV7VCgUUxqvuh07aLvVpQQc2+8CwIAd3dUGnzvchnRlL+I2Z0xRTk3FwhGKhnLBtxB12pLLRV/6+SPxj9cgtf/r5sAHQE2p63DsNEqjq565HzLrTPJttOqN/dEfbbFNtD3Gc0Xx9WaznZrcoC3j+nMYe0wt51UMptQslwoiAY8jOv3z0E62ot0nKm29XN2oH2sYqCkxw02PGAR1xmgg20UkVwgO7+LrbbwqgcJ3bO8PtS5p+M0Xe4wBnRkZOhbrqZ+lTcQqnAWKs6N0HKoQAl17OJUojAGEjASIhprQ/EbSuxsJU0aciaXQKsFlgoLW2a1bi9YbCP3kHpLx9L14uZeP5w3IiM1KOSPiO/idmrZGJFUQZ86RBW2it9ANETGYMJhEvQmi5tZVCKGfq/CtIMn0Ms2sYsOZp/Wbvj2D9naJpu+ywU3Wl703Je5AQC0MweFgcSxVW8s+B59d82DEOJpogXj+vdzb1rPiAnZi5baP8ctg0BUttKiBu+bTxcMAqlz5jDv0yYPaaANJczWXCD02NedtF10GUtV56CTZhaeOkXDngtPdsZrVxn/mtiP3gJ9hS9oFMf+APO+f1jx/12koPUPqCEDTGCFx6DOAzXxVf3nQapeLQP++QVA9xdruKHFu80TT3z+ngegbglKa+WsjAwIuHrd/wRbV7hVFVcG2z7iFJi2c=
    server.secretkey: AgCICH+/bQHBKiUk5v7dqsA0IlkjupmfPD8PfRjnYB2cpnVJbQ4xVQz5tEzpBmngbkIkomnDVf0eapw9HT5EOBGyYE3jzGVZrDTu5OQjaCpm+O6x0+CSIzFs7NYjELMgM5Nabjs0DMetHy2XSdAiUqb9d0t+VsuQDD/SExSWDQFq99GuG41SaYekDGSSKbdS5YJUlk9i5WY8KbBTCb9BJIXuUNnSpIR3mo/8jaYZynAQH1PvmG0q7OIHaAVSChwul+OgG/DaTdG9R1jkIWuDbZvSctglh50RFeTL5+iVqyBcmwO1d0HUbX3fMTLCCphtpKeccSOjqqHEKhLLFUuIGFLGjnKsFLyx636FQd5oB04uxXRY7YcyRCIdENAtPQDPYkwiBhmKet9zpMdruh587YP+ANa+7fSecbEevQjtBvZuvdYVo8Sj9HiWhAFSyoj7guw7nSgOR2hFU6U/OkJuS+jm723oPlY+66EPKNp8FNuFVNZ3y0qs0CtxQAc7ci8Fs1+bOa+LUnD1tCF4BA5teggnXXdOhpvLhX4AqcR4JpZfyunBEtsi6eqUQBNYxeFON1oU612XEVKN+m1CVYEhZfE9rJcuE2I9fsplcByt170LtPiWHLe3unNvu4iAbtYeDOgDRlYX/e3R4N5/9rez7ETje9zUUi/WQX2MNeAvvbyjwA5FdFd5dVKCKcApBhw36pGA3rQKOcMde89gNyrgk2GbnqycXbCAZ6Y6B2H28I9TGu4qiqKf6DPEPDdwOw==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
