---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgDraOof5KfbC8MPfG9GLb9SDD1/hmEVhDfog3aBeCBZQnEISPqJCZYkKg63NPArz9Fra8SMNneuZr8GXRvoFE57RSePxbFVxtvo0J1ItJBzwVXbRSddqmv6iSk5zBfL2AAg3P9+8ORWE/bBdzGJxiWFZOkqI1KDFXSPhhBT8TyCyN9REZ8dwZKnezIdEZIqCMR6lilgrpvRfY7XmLAC/kzLA1ka08RKUPpz50dvvxaTByEsIOW6pkmyP9pV9D710VJk5J12ET0MTtLJEo6JRKX7nDmZS9/u5QTjMIdKhjfOLX1j8BUV0kAbuqDU9rbuGtufqWOEMjlNLyjiPtje8DuDMf2Cb/8jAnvNb6WfiEzOWkdlTI4N9xyIPLN0azEshJKN74GdCgzu25KJP3ATYEcKnQQ2pvZc80yhU57IkuTFQ8KHGRb8aJhK4aYT2WloyBfKuDXYYxQG+ckNYqPVpNeZJ3+4o8sARWyIfNKhUJbO0JnO1P/3+rSvE9HFzCHp/4iTZi3yHsEeo7JQfIWpqhaFQW44iJ28/gvk+ZWgd4bKweI7XnnY3azK0oz2vgzMg+OgE+QAgUOc6Na0aS4+vzHUGhA500BC9Iw0ppSfqmdZh8K0L/8bVZ6jjA0rWP0e5UU9L6k9m75eFcrsNI5HZiVudTqvisa7/JFLVIbKCcU8Ffr2/xMnGVBvA7a8MCYL+x7hHYMEwtkgBiHtP4juoTq+E1sibRtO2lrSQNXMsfsssST9n/RhBs85In5wIEcobSCU69FMcHfw4tUnp20=
    server.secretkey: AgDshHI3Zih9u6KL9qAdu9eQKgaH8p85EDQAjxt2tWbtvnBs9YzgbT5NftgODMvdstJYWLPJEVMl72Dbk7Of5Hueg7myuvHRI8gMxjR6+Etn53TspU86x+i6ph4PzB1xqrhWbn894UF6ZuFYSm99TKDsMcVj5KUt/nmOy6XaNLw4Dp1tkKG3ntaU932A1ICLh/0iT9hl8gBRwefoAHkCYjJ81XNj/C4UGbmzLP+IG2ZkWpAkiaI+Rpy2T8McsbA7HSB1TU5aNWP0RO3ihlJj8SFHt/YB39blny6HPrB2TvHT5LpbyEKkSv58sfmWguOx4JtTSLcVDEswAdjXy9qS0yyvZnCPpfYRwJgVSWsykgSauaBmxJRkOgWgtw26Z4kj0CJ07lgPgG3PMzrinsjeLHMheFXZpFczqLYHK2IMWZVR8+iLvjUs5n+2XpUz6Q9YlOixBAQD3Ak6fYIWL0t1pB6Avcr+g7AiPCgFUN3/Xb16tubVl7KL/Q4gwcPguKo/6+QDT4RZnb/UQbBwvQkUDdRM7oSw643B1ry2QzHICbcRYZuZ1lFO2tUqv5aiTwmc2z2AOz8ai7y5lWxcxB8ojXQC9MDeEcixP++00hcERqibkI9EV+7mssXjSe9cLJZOM2J9bB3BBPBYmLHEHiYg9JLg16FEO+jX7jfgUTdblOG5+T6mTx3UKo+37dtaGXNF1HWn5js/PQcWWk+nZjdsBOlE430vGmiPP616xXAUfERE0ZcdmTYuagyP1CyS+Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
