---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgBrpscRDyNwFUn79n8kV3tD8eDIStKSamEyt/5PLWWUuu72ck6nkHbLDivTNCKVCcltq2iMs/XpJwEP9nTxJ5Rom8zIk1R4ynPr3lDxhZYA3sHeFLWntYh17dGuScL7I8hasprDnvTp5Toz0UJH85syEYOJ+IxH/O2kM9tSvAA+UfnxENVCk6VkHnO2t83nBW3/Jiimrktlgf/HySoNTaKKF+69JI5tERdZ9+Y5AFaBh/kvSPg7If11ekW8ZertKstZ3IiZqK9auUwoCrDExFzI8b+yOTEZbp7doVdQ11WegwlF0enLK3O6Vo+VbQgueNKMEOJ8967KwRK3TLM00ne9dstsNhhMB4a+j6h4EdtbOE8i/OeRIM7RQmTDMMb80S8o7nDtlSnA9Yoa3ibwc38MtQ0JjznQQRra728F33az2MhWvaGvxi8aAJtkJx0BsXl1USGuIC/76m0qRIpOmnspDgvlmfNO9kZs5u6YV0HKZF+q9KvKBf2IWhektkW0tTFp2lKUf5Kl0Jp155QP8ARTfxGJYfd+wSYrw59SqG3CkJl/Ipqw5eZjD+gnFWiH9CYT78NuEgvx3Z12EobxRxzAnOfZn0fTSwkKi1T96ftA3OxaTkQHA+HoBJFXKTWxk6V3dN4yvIL0A3DJs9ysryiCRcIHUujT1E7LJxv5MW/ksg51rWU6Dgpo8pw0wLrRPenXQxnquIlcU+07ArVsu4sBl6I5pX0PR5fearQqQz9fIsXhPY9ZbuPz73H/JHv9IeATsa+vOvlIHOUoous=
    server.secretkey: AgBs9groihj3dWJuD0Dm+JynLZB4ynE6zNHI/E5LV9JWhC48hn29POpBnYTauoviDf8rTsuGSbRWEIwGcP0m7TwYJYpczzsnuYOQek3BRID8que7HZQPeRUXttI6EqgNGvF9//HnuxtK/tj7ESS6K5VHT/2zax6pwNYX9kGsEAT+G0YIeURc7NXyaJAvsxYG1zHwoS8870rzdZkYZDlN3esi8cDAnTdfpOdoo0L/Uua9l7R1m66cxfu9dxPrWsgxbM/F33Regw+0lu8JGuTTCQqXXMNwRzpai7XnbRDVWRK2lNG/xd7SenuDWiBKTPOxQ+cG/V+i0pG+0wo8PbJVTyNUF9CK8rr/SM2tiYsalcm9qFyCGhkqJZVvGGN//9XtxPlr51FL7qoGp+eW14AifS/uECzux9FMEFkX3/nBg+URDfFNM0VSCmxR0q350pg6ntK2z+0mVYPnLwDy6rxIssQU89wztAySxC7eUD6nT2Zblb8EJYeb4GzdqzBONAcPuLWsK1g5xDKbm0zmevdZ0Lo5tP1jDs/0gTpUettaunuMXlqxPWjSGOyM+veln3XB8mT2hvlwkx8ra7pM+xkpElW5J9go7Z+oV2DCd54PQ0fVA3gCRaTPW3j0ucoGpwAoTLtppt43REx2CUwEHtey0aEzWCr0wy4YLe7sWMzHVWs9OMLeogX0qNmo0vpIjU31hpVB8T+5CKNgwwA5xVOgZ/yQt+4pSCDBsx4qacf+I4+IXCUMih3O70J5ebG+XQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
