---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgAP0TatRvA3wY3ptJkbCzkFBMMrAUlziogMbMeXdLBAtcoM8W3IE3bkLAx8MK4/XTIeOr7gqkqyILFLXexxxV/bHiaAl/7ivhONjkw7PMEPZdY7DNjQAFTXeXgVVWazqFdVgJCnYAE+qtBhmbGq6kLgOPMpUnsix1lK4VlfNNYmMJMs6fS2OlP1tcDdzgpEnjz0+H1H5cuUuOyPDoiXLIba6Qb+iKyUHoSEe0duvTgdZiLOQnHUu7zcMmrhnqHir2ETOF2Fu9ubuHze7P1zMk2Lcibsy0oBRPqGmw63kqCwWfoKeqfPd4HGT006CCnEMOOywNYx6EgaqbUaXG4yzL1WMT/m2VC34zBb6PTGVwuelxI97lvhyCLnP+fg6rRqnRXpDUmHec7Aml8rlMsIQGH2ufmwReAMkaGMlXB5DVsFAGN4FRM+13dvqHJUKR8aPOvRTJR+ZTE4R0s/FFP6UBNz7/fUdUoDTGdeuIdjgvlmfITWxwXR262vjYZkR2d0MaaDmFsJR6miXV3w+PzSEKL4GPqKh609yBnIumlkc0zCJX6gKBAByPf+fdO1PK1y9IkmEJmJvCdv9NuiiRfMwHydju81c9mRYHF/vC6801gQ87uNTdbcI6xsVUdNE6aAUHIoMZg20EYfRlomdermtHRPMqPEjIAXDXuDqnLvv6lAdkRaAaXU4IY7pQH1mNFyKBwHbGzjaisC+8hhOVjvO6xLxDdr3KzXqMhRAsfTk5rlAkfuQj1XNcQs5rOv3faAv4iyi15NlIFcov2Rwyk=
    server.secretkey: AgBcq7kVR0e6ATHA6/xv6yJOxCzU1Agp6yJ/+M+FNN5icGslBMPVmirn9vt5GxzYbG+WhvFgT68D4u4Kd1JUtuoBr/fE29wscIQwPLAgcFMsR9UyfMI4NPK8KbTjFU08Z4EjjhvhOq2CNbItCXl7GmIQ1nVWwz/YGwjQXoSb4gw7QDUkCqGKeyOrE56vEjTVWKPC5vCG8Eg4CZQvaC8i++48/tMjvGwRGvehAlYbvNmfmB1M+n9Enhn3mwKz2YsixOj4EeYDCP7oeddnEwSbC7sFyHjkc4f2QefdRxESyehalxG3WHce9DaxuO4vwG8MmpqQtrW5ExZG3sy5KrdT+ylJ4V1bbA/jdFOiwZt39CK0uIRCDokkLA0LJ7YrLduxnASjsVasafMQrSPLLnBVgm3p5NYZIbTLgJwbsvuF6gI9emtJqbkEl4n3fRQUT1LA29C6O0OA9QWZHo5lKzp5LmGJZn2XYsAarXHOvBl7bUrwVaLGlmF3b2oHsMavnZkTb0bEYYxgMS9fZCobITJeVUYTT/50bPMilHciAn4OMh6Upu7YFRQopl/lDXII1DvH3e/Y3tvHzjcd/XMx3nkPyVn8YRIUKlyjjN4dmdkD7T2kuFsvC2LJDWmfcZEYAWn+ciT+ZrNfgUzJzoLBYy1YqxrbezxHm++8IMs0OrubRtsNBqc2SpLOPZnFYYdUjZigcG5CwLn8nl0ZW8nNIuweBm2TnhwkkHcg5qhfj+8XO3R4L/lp2sP5a2yMLTV8hA==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
