---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgCvgWQ5OzTXt4/+Iw1eUp2Wim/MiWCBJ5dzH6eO94N397PYKeopYv6hnaDw90Vr7/2Ca1dZoEoNqmbsZ60HiiXdlhcvTgA4ThhOvYoDphI6MiURMWtKci2BxUQMtWYiJJC37S7kKcYdWUfw2oBGer4ICCqz+9eQDOf1O6hgI24FfCBTLX9PVxzkSPxM+zUWVNdP4ukDHsxTCpZ/BH3Y2k+/quCi9WemMRog30hQ2e5cmhi1ci7pLeTgfW+5rpsW5KYGYhXaQavnOsybCkRezGm1r3l/WzT4pRrvpTyQi77vINmHpUDgelp8FlFuR0weUI9JjVV0JjBbytmdIPoaSP7BtdKLOjtGD98m2UB0qN6aD0VrQcs/OwGO/cOmYmcH+f6dBHCrjIzfKWk6tuEZuunFSNP9BFDxagM/6yKCnj5gy/JyAhg8wiVbryRxdZy6btKrolYJZTByOczVY+7XpMLMY7vpFR0JZSVyuBuGbExmtGD3aY50WQS2aoSdZXjMThu2Qxc3A87nYV49kptXuu3YoIv84ThYlHPPRi/N0ChIkuDtczU/v8UCjileMONk5C48oH3tANvCVUBMf2zcvc2wUvGOUngxn1B+bYANNXkdtTl9jbNpfVAt0D5XwlQE6k7CvoObrZS9ZQcGBzdx1i1TdcVPndzSkM7BS0xvM86+4iWm7eXuwiEo5IW2+q6rxW2LAhHtm+EJmbBuPdnLsJy1+utd7vNWF9LsDmq1uhbFhmlrSrSwCORYSiANP6nTTlCSazwJOir7STOEnlY=
    server.secretkey: AgAU+nEP7RFsmXR8jdil0zrFfzWSUdi9Jl6oom7mU4lb0L/RDITcHVAbQWO4ulQiIdIAJNV2S+W1UeTP5aePisaK0j5PoBVthAZacciDfUHmjaOw+Zpd/vwEmBgF5toDIeYUYoXMvTm/mxcz9L5O+Id2kck8mwpRwES6prYzfIZfU3ufYWBc0H27Pp4p3TBvQD2aYLspCzayKPMetBlw6TpwBZuHAZ6IKg6wFrcGX3Vr8FftfJQDapn0BKmtXaX0Lfm9JaYmYbxZIXktX9gfFSbWJI8kb650vb9+xM/9n1pDfee8iQPiraHZiDM2/QfQ0A/fFRkBy0+h4+jxUFzP1X1vpFqOtyf42mY5neV94svwiMsJpWgp9G07XEkrywnC2wLBqblLjSohI0IrwmOitJsGItXAr2ToeKckbrs8S+IhyqETu2Byn0o/NJwfvlvPehX7+YMurwrsJICxrrP8+14cAIorCsa4S3G6iOJrCpeWTviSBNxd7x5sRPtokPXq6BF1/IFDE7Z1VAxvF49qLaWzkfoe2FfMGa7o5o3BATURcT7qCTbzjmcfHTwSf26xhcCzv3ilw9tEMLesDzOqogIHVD13raUGrw+lLt5s4aN4hI1gA5WcTje9q+y90wvuQVrNeBTmQjOH2hIgPmQ/v8Wm89Cu1Wg74qn66xuISkQMwPSeWbS87OqBSnJolhNV6jK12m65iKAaPRtL0TF92UFY/n4lNcUBbblkdfcGpZIm/wQWiNmJ1yUI2zlOpQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
