---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgCMKQOMYRxuunayZaRD+Of7ECHELccu0mPAxZz4htdbfIyS9jDOuGEQg3XUC7pMYgsSjYfqj3B3t/ErvQIvbsUEWb/cFFFh4rYObymE8OiOQja55Si1xl1ocMEXn7LNa7BFOG6mDYvEhdCIrdJfJYdC7wzjuo4o2YY0+TfdE6JBww8usEXgHG02zZox9XCLYxrCFJfIc58Lty/HZBXOahTTnQY/6nKIY3xwjIPUd2DOsO+zo63zuFW4ITPxtdFDzh7nEWLjHETWSxaCnpNF2PeZZOSZzhGKqEOuz0l3XH9mS5bqfojQMumh9lP7q/cW1rlyaldEheVdwo6R9jhQDIfD2CQRIDfugKSc4zYZFKp/e2s1zeskt6uZ9u4FG/jTxsHGTAcfqasiK0YPSAPF6TIOKbckTSTtZR/J0ly7v4K2wHnOZgzSmP5x6VHsu/X0uCRXWJ93mjzhPW/Qjs9iuGVVms7q2ASkL/edMpt41ljDOqj1TQ/mr+n60cIA+UCHC0FUGA0+6fnN9fD8VlQZ0h9UmHhRRFdM6y1L02tlvwijPQUPRH/zdpwHY3YNmiWyDVYq5C62HC9LTfE0bO9WvjMlSeDAT5KkARQtiWKxz+ie3Pwr3nXLwrmsHqyKcZw4HRJGqCe4rw3NISvgmDNLKdAnV50/pY0AsaLcyD0J827YPrljrbGiLfmKC87bneex20zx7kMD8c5lXJZw2IcJOwItxmGnifimKmjs5NCfHs2tiJXbc/lPe7E9wq7sPbadTgxCIa1XzPY0TCGS/fc=
    server.secretkey: AgC6wStc7I6sqqLLwsM5Q+AbAu1qco0ZlrbrNkgBKgvSwQAYMoa6JbcJK5mPSHsRSoGU8PrrIdVMMgWjPXQPjsrNxtYmsNO4UelafBfZMacXDIeUMyUFD/MCXbsCws14ifaoF4rM/qs1aga/dSSlbmDF6lrYIyjsJXrdWjUj6jg5NJk2nrSm6tRbtK3uBB0zXlU0XWZZVSxfYAd+j6ilxrHqUaCk6OrBvNA8AH2lsjqWQ/N59/KmRgMbgRsfKbjbR9V+Iavx0aZXV8wj/Cpny5+TLQPBnu25VvivtoLt7X5OhOyB+RdaVcX8Qk94tL7RKaGxZslxVWq6FgkfPVGqr89zWWmvr44eHxV/ONCujoWgX6ixOFkDqWZwo6hob/u6B7a30RcubkQp6aSU6uIvsPPJ/tQ9kQhVUWedqmxoGIEoy15FGwUgauXJdJodHcWtrLK8izs/v45Z/wHMOC2/t30WeY3fthHS5uelNYcDDBd4cognlx0nGwIc5Ehg0CARjsZw+OdBC+VDis+ZNyxnv2ris4m7j2Q7PEwwPdZC31IgfdGkKuQrp+4LR+MNCxyexMXbFcPBqnOZY3KNxNSkaPcC9QIulp0JoaNti1O3/BUBQ5XMEHNnkcKFSupaphH0ZfgM2aUsg0EMQXSYwM9L5LKSxY6+BGr6bkWGDKitkEsCxYHKaFVkX+Z1nrfKcGBkbF3axM3/f1BX0VKPE7WSHhtMcrSY8jYT6MEQ1JFKMqQujgdBkn6KEHdWf/UkuA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
