apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: pulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # Git source for manifests
    - repoURL: https://github.com/edlundin/homelab.git
      targetRevision: master
      path: apps/pulse
      directory:
        include: "*.yaml"
        exclude: "application.yaml"
