---
# SecretStore to access wildcard cert from traefik namespace
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: traefik-secret-store
  namespace: pulse
spec:
  provider:
    kubernetes:
      remoteNamespace: traefik
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: pulse-external-secrets-sa
---
# ServiceAccount for ExternalSecrets access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulse-external-secrets-sa
  namespace: pulse
---
# Role in traefik namespace to read wildcard secret
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-traefik-pulse
  namespace: traefik
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["wildcard-tls-oisd"]
    verbs: ["get", "list", "watch"]
---
# RoleBinding to allow pulse SA access to the secret in traefik namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pulse-read-traefik-tls-secrets
  namespace: traefik
subjects:
  - kind: ServiceAccount
    name: pulse-external-secrets-sa
    namespace: pulse
roleRef:
  kind: Role
  name: read-traefik-pulse
  apiGroup: rbac.authorization.k8s.io
---
# ExternalSecret: copy TLS secret keys into pulse namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-tls-oisd
  namespace: pulse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: traefik-secret-store
    kind: SecretStore
  target:
    name: wildcard-tls-oisd
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: crt
      remoteRef:
        key: wildcard-tls-oisd
        property: tls.crt
    - secretKey: key
      remoteRef:
        key: wildcard-tls-oisd
        property: tls.key
