apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-synapse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Helm chart source
    - repoURL: https://ananace.gitlab.io/charts
      chart: matrix-synapse
      targetRevision: 3.12.12
      helm:
        valueFiles:
          - $values/apps/matrix/values.yaml

    # Git source for values file (encrypted with git-crypt)
    - repoURL: https://github.com/edlundin/homelab.git
      targetRevision: master
      ref: values

    # Git source for manifests (sealed secrets and external secrets)
    - repoURL: https://github.com/edlundin/homelab.git
      targetRevision: master
      path: apps/matrix
      directory:
        include: "{external-secret-*.yaml,matrix-secrets-sealed.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: matrix

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
