apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-synapse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Helm chart source
    - repoURL: https://ananace.gitlab.io/charts
      chart: matrix-synapse
      targetRevision: 3.12.12
      helm:
        values: |
          image:
            tag: v1.140.0

          nameOverride: matrix-synapse
          fullnameOverride: matrix-synapse
          replicaCount: 1

          serverName: matrix.oisd.io

          persistence:
            enabled: true
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 10Gi

          # Use the bundled PostgreSQL to satisfy chart templates
          postgresql:
            enabled: true
            postgresDatabase: synapse
            persistence:
              enabled: true
              size: 5Gi

          # Resource sizing
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi

          serviceAccount:
            create: true

          livenessProbe:
            enabled: true
            initialDelaySeconds: 60
            timeoutSeconds: 10

          readinessProbe:
            enabled: true
            initialDelaySeconds: 60
            timeoutSeconds: 10

          startupProbe:
            enabled: true
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          # Use existing Redis deployed in the cluster (namespace: redis)
          externalRedis:
            host: redis.redis.svc.cluster.local
            port: 6379
            existingSecret: redis-password
            existingSecretPasswordKey: password
            db: 0
            tls: false

    # Git source for manifests (ingress + external secrets)
    - repoURL: https://github.com/edlundin/homelab.git
      targetRevision: master
      path: apps/matrix
      directory:
        include: "*.yaml"
        exclude: "application.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: matrix

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
