---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: matrix
spec:
  encryptedData:
    signing.key: AgAZklilHNXsTH7ASfGAasDlhgYNm+I1e9K5pbi6PTxv0UvDM77hySQNOC1rR0+ZMXZsWg/cEfE4FQCdP7Umrbm8jo2lv2Tga+XgOft7IsU5/0tWkACKcmHrLYozr055WmEumdb3X/FMKx9WpVASDy9whEEXUB/e5m3EcMUx5C/ji4dJi43hAqssSIkzhZ+vjAyal677+d4Nca6ziLenf82YJzRWzKkAqzwX2m4fY8irbG2yUFZK5Fc1G+ar28ycq17v2BhvWk5WWJWStZdPOECWXeQzZrcaMF23GwqtOTvD3qFTIMPjx9oWtGTfmnM+lupFMonXN9mKPkSb+46XyGGe+IArgMrZQ+OAjHceXP8etv1ObaVtDxk7+TDcxhuCItYYB2QZpMkEMKk1G2aqyz4Wvs19usxfzysl2Miz333pipFjC+mie7CtnL8En/uzU2jwoZe+ktXtzqsr06tl2J7hch5Nu6BWVp55brtp1HjhMydlEdGCOiAj3+ScjtQW4SbrT7Ix+xy00wmk7MvTI6OibzLmWx5rUbozwEfXcln939tBqOR7AxrrmLlZpMB2Cf7uVV3dcYXHauHFTC7XRlVdqEY4HQK3QrvFgo1QnbGZvsBgaRqBYP0FibuYaVZL6xV647ag/az8weTEXg3AxrM6Eulsd6wlTKzx3VnOtdn0gkQOpF+JXQQSyHb/D9hRuDYlnmR1jkOc1i1Hc4gNb7B1N5Jf9ZlbT8rAFMbKCoYsQn/zAQOkkD40eFtyadC0sufl8HjYSM9oLh+pNQ==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: matrix
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-secrets-config
  namespace: matrix
spec:
  encryptedData:
    secrets.yaml: AgAiH3yr5koSJm6TqEcuJkgbZ0IKsj8kvdoUmO3x7NT8+vkhbNTfA+pCLtVMFDbcujLB5Ee/kSHP68tLMUzj7uS3+Rl/WIREXpf/5dVk0q6ZpYSAKoBtj99x5LwFrEe/lttxUF7jR4Bky2cnjLrEVQBCvu+xOYsRuRm+gcXKrjlFLTn4+8WN5E3lv7uYElk8FDanV7wC3sU/B7nOgnbuin1qv6H6CjskKn0aS0Z8n23qpr7bmTA7PekSdmOcclPhRU4XISsn3yoWaBRnxz0/J3dMecFPimyZL4f0kTDsFqQrVW8gkzV385pm9Q52UdXF5v8btMrtWoyD+BrXnPgS1hYGY41L0yl6dCIFbkZTtwcV/dzFk9EmdiO4MOJiKugZrp0XcXJpyHBy/p/4oT4SO4jcj8+w8FijLJphQ4iwnOuq+55TFiIez2uXeuRt4ACqqOapTcsz4bpYZaU7Xj4fevd3Ov6P44rdWMrEYH+04Rhobe4zOPYIWiLgb6uDTLv7U2vFr6Wy4ikaBN7pVE9t4OGvl/eI5uVv5JXRdmtW6hFfIqBmLQhSb8oStnGFHW+iZfOQwdi5KCvr56prx186mrBTXa20yuATLnI07l/ucGy2ECukS30njO0JUMXom3M3suJtQ2oyn+IQWEScYz4fdqibBeidnDvpBR24Xtm4PrBmHgrKfTvT47vsownqJg7swzdW0yl4F2yxNPnf+9XRi2fP8H4hVX7VzzIaY1jfbwlVLyr0VH/z2Bxx28Zbi2gQ9a6HmbPERGn7LhdYe9HgPYkI26UU/mWXXWG043vAqYh5hujgIkzhIXednCTztGdjqNs0ZKJ9OLstBUaTYIKMU0skVR/gGNFgB1e5wyysuAlEFYy75eYMEGNa93wmmXkiUzHB7U7jFm9yy/ipWKxThfrIJxCJ1Qsbo1BOax8SU1xxaK4a6Q0kdWgei3BZyXA=
  template:
    metadata:
      name: matrix-synapse-secrets-config
      namespace: matrix
    type: Opaque
