image:
  tag: v1.140.0

nameOverride: matrix-synapse
fullnameOverride: matrix-synapse
replicaCount: 1
argoCD: true

# Use Recreate strategy to avoid multi-attach issues with RWO PVC
strategy:
  type: Recreate

serverName: matrix.oisd.io
publicServerName: matrix.oisd.io

# Enable registration with token-based verification
config:
  enableRegistration: true

# Raw homeserver.yaml additions
extraConfig:
  registration_requires_token: true
  # Path-based secrets: point Synapse at the file mounted from the k8s Secret
  # These tell Synapse to load the shared secret and macaroon key from the
  # file we mounted to /synapse/config/conf.d/secrets.yaml
  registration_shared_secret_path: "/synapse/config/conf.d/secrets.yaml"
  macaroon_secret_key_path: "/synapse/config/conf.d/secrets.yaml"

# Traefik IngressRoute
extraDeploy:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: matrix-synapse
      namespace: matrix
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`matrix.oisd.io`)
          kind: Rule
          services:
            - name: matrix-synapse
              namespace: matrix
              port: 8008
              kind: Service
          middlewares:
            - name: default-chain
              namespace: traefik
      tls:
        secretName: wildcard-tls-oisd

# Signing key managed via sealed secret - disable job
signingkey:
  job:
    enabled: false
  existingSecret: matrix-synapse-signingkey
  existingSecretKey: signing.key

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 10Gi

# Disable bundled PostgreSQL - using dedicated postgresql app
postgresql:
  enabled: false

# Configure external PostgreSQL database
externalPostgresql:
  host: postgresql.postgresql.svc.cluster.local
  port: 5432
  database: synapse
  username: synapse
  # Password from external secret (copied from postgresql namespace)
  existingSecret: postgresql-db-secret
  existingSecretPasswordKey: password

# Resource sizing
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

serviceAccount:
  create: true

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  timeoutSeconds: 10

readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  timeoutSeconds: 10

startupProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

# Use existing Redis deployed in the cluster (namespace: redis)
externalRedis:
  host: redis.redis.svc.cluster.local
  port: 6379
  existingSecret: redis-password
  existingSecretPasswordKey: password
  db: 0
  tls: false

# Mount secrets as config files under /synapse/config/conf.d/
volumeMounts:
  - name: secrets-config
    mountPath: /synapse/config/conf.d/secrets.yaml
    subPath: secrets.yaml
    readOnly: true

volumes:
  - name: secrets-config
    secret:
      secretName: matrix-synapse-secrets-config
