---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgD0wbCL6PGuKWJmI0rSKgnnupSdzO6ukJEpPYf+EP/3qAIm4RntzUVHw+TvhJQ6Twr7eMvCyAZhHGylTJBZFr2RYg+mWtYKRZjBG3WCdazic1jb/yZeXarJzEDG3c673rkMZJsInHrr8hwXTqLZNsm9HDbVM7dnBMH7hhiekAjlO1TuroBVX1dMgqGYMnD+re2iCrRiafNPhG78BHpzOhqGvWKGyHnYXcZ7TWn0Oun7KHuFHQEVp8KlYc4Ka9iuwK4CeXiBW/9D6sSiWleUV87+EbOUd4TwvuqFBg0+BrY0VUImB8BKEOzJ1JcpTJ5xOYdhJNCmiF/HRDVTA75cd5yij+VUyTwHoEaoAM/HmJh9Ia3kd7mEuaMtciPGOOtz2T0SH6ykQXhMmp1uBThw0jFjTHZNfhrD33/3y872aAdF5vZRib/M2yrShdE1XNjLZmq0/h7zbHDB/yyq2ME+eCJdcufH+SyphK1lALnbWH3vZV7L6hrFrNXIW+0Iny/rZqLU167qXAfaJeaCBhA6RWqj79sRnLSTqx/YtaFJBAJHkbXZ+cWEBTvzxg3ZDzdsuyBymdkYyNfYox01BXXWh9haUFLz5tw18qee3wXdVJCHVzFTM4rymAJA5icgY0lTE1ue2XLSJqbjoPmNzOeJ4zo+W8iVeY7IgRDc+vmf6O+S8McI1UfuAL62OY6/hqQt92GGTTVemembobOu3PgNzFktXtOzZr6+Qf6v985Pz3eOiH8GWFIsadtC7S5R8vkjJsIgKnmdazAHVK3p74OlIErW
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
