---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgAu13EtLXb6ZJqYzmapw4i84XYQj57aaQP1AybeliLHhobe+Sdw4zTj+/Lb+F8gwS0LCNuMLCUw2ck/m8dTpXQ/1iLsR6C/XyCyBO+wdHGnxRMdLU60+qyfRMFFaaCX0UFaXOwhC2K4pAih04QNwAlCOgHLFMl35bOLZmsNEOwfMgRtfstPUCamGf62WtKPudePzbzNAt9m7veb+Le2WT0WM4zuFXvsjqQtNO7kHZb31B0Wp+ikzjby4+G/Fg+IM+Eu6ukXIYdwYhvSsJvEbGijFFq21Oo3/WdIM6mGaeJh1o4vLSHro1o17pYJVmuY+R93gumNIZs7u/QjMIBolyo9h7bcjxw0VPGraXemLJXvGlJitDEAKWPD/BN4fhWwTWERxG2/90iZm4iTNYPzwYIktgBbsMtd1RQ3GnfNzkVWe/vjdZTRpzKOSTXAklPAS0ATIyI3az5dBB++zv0TB9Ifj9+rleSufSAKuMoRGpVMnNiTBbSwfBShnomZhp9OQ7gd/Q1eFdTo4j0cY+/EqVEiqzbFetqFXlJi5JQEPAhH/HEL8JMLvG4i+b4dRfkE7lCAbN8Wrywq2N7i76LCUoEt+XzLrAH53RYsM63EasNyi3oyGxu5L/q1E9OdJQaFVD8wp/LCcP6OvCvcVaIn2WvLbPMBaI7YaaRlgG/nDw3tqFafOjnNvvWt0oRbjf0+fWWIwTzVQlu5Y/bE877uvLQK8vDrE3Kj7VbddRj37EXdScX/qPmpSfvDLsRyKXzLXKdwEmtkvom4rbZChaxqdXLL
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
