---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgAgAQ3W1qJ1D08K3Zbfw1t8+/QB7aCcIbThsrse4nf5EQfKvwNKDWOfcfMNvYdfURqAnt4miuu1y8MSaHM/1fCjmQoweDUtmCUnqeLaHC7F0lHeMLFIJ5g+s7QUkL6O0PMoS2MY/dt3KId+YjOhfbyUwfzBMq2ub0E8tLIlYKIKKikX3IfSwcX9XdZCvTo5edks6O65bX9NbV7eRR043Nzy0aH5VFZCqAbX97H0FDsD5OyaYLDdlAZjtcEy50tgQ9/T3fpHpxS1YnaGiw1t+6aMscVNCv2gCr+mFSIKMryoNIM6e/g9/PaiVqbfEKRBE7U0ARTnkqv7txsjgl5cXQezbZ58CGWi58ZaxiBRSPUGSAOYibPt8A01z1o5VUcRIhDdimgUnV1COy+21fdSjdD6NOwajooxv9UnsTy4ZNnliCZWsb5FIwNcdRa6/O1fTFpmqFuhnG1exTQN4uYhVDNipT5DaPPOEdKYnyCh8qwiVI0PeoH9K4xXMAqVNaelsQRh9y9t6iHWJxUfuIk1odwSnop2SKkKyDIXyQtQzwnJ0ubZJ6JtQZ6VMgaAvFdPQrLmJUX2FXyaJv7gYRTXz3FotvjG0mupgk8qcba47y8pM/YWrCriZ/cCvIS666J2xHYOprOEww6Ety1im/UBAcCnQV/1glc0EFgu7FE+dq0RpzAVYw64dHl8CcchS60ZPSs1lqjLV32HfSoebamm3xbL6xhH7NgF7JTYcMwkk71is1r4a7HSp1jvmhFfTvIuVNRXxE4UcIgPGU5qWNDdO/K+
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
