---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgBJsNCW4EJKqdg6x6iuOkNjIWtf6ifRA/ePeTu2t3k9fnElR/AM+7yCewPHqJjxCpnSUaHSK8OV/5vfmDpYN8xRMhb0h46H72Bz0BAV2QdOooF7YJrCL0O89TGh83bHyLqwb0yG2pjBRVB0AjT8eY5MyMn5DScADcZ33y3oR1o4hy8FLbNG5zRXfF5F5ugpdbkNae9rKai1GdBWCWiV1gj1Qcdj5REcNtxh96Et//Ev6YGyUhpIcL3H/ubEOL5DXb0sS9dlhKQsUpZQEn7BCkzpnpWXV0j3dR5hkB9opO82V68yt7Damo0QtHSfLbBpHXjuHmWy6XjIYckQkyfw2Jv+11MMgmTpfSHskkkVln3jlSavbScFcUeIFJczsGUA6aMoAx7y9Bl9tH0J6qVO2FVsRyOnxsDuUbTfzTp7C9P/x3izzFHR/CEqA6WeAob7v8qo0pBNgvrSeVWc7zTPz+68yJxS3IQFqwyvUbFv4b/BMbIdd82OUjrlh9UlUX/itGu0yHiFuwwoUiicwIqCe2SeQ5DplgFse9COmfFodFgMyjjy4cLQabLT+5Hti2cOfL/X5oSm7wF1y8xHtS7zTDmgCBe546cCbJN6ZEZHTL/rjPqCVRClhFCCpyy5aRi1bjpHx52zoEgJ/zYTmsy7Vg7qq7MNw8ytd2QY1hm9fV9zLjVr+18+WAuJz05k67/3S1SZbMl2xGR1x5uvjrU+mZ6vbx9myMAW9j9tdTVkPrSsMpeDAOSkKm6Ar997tDJ11jLiwHs5r1PixOH7qTbnQFmx
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
