---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgBlrL3Ot4rbgv6Le2nsDRTr5P4KIIHZ5DLFcHNmls4+nZ8hwQHqEFsZgBJVxtIQUCigD9c3D2px8hrixO8G/DGmc7HUALWXZhlvP6ffSkYa+bafr+LKELNHI1CfSen0NZTSt6K9d9/vU2IX4MqziZr3Hz5sdUfn33YlGfjiA6ESj1xoIFSt7guVUddUIZ4h0DmTn/YjPyDOZ0GUIoMU+yUU0Km76TFp7YKglwVX4hinbvThOBk5DOmTw2xr/2S68QbrL7bD7dymU3SWab3m/kfPfsOD6Uu8vNuJX1IV7P4chxxuuNAq5UIboSTYbs376tEPjgpF3Vupzvz++OrPVbFo7yxKXaCnOqUq1sCFjTCX3mCAcwU6xHVygtFBZ6zdlVFOxWuKyXl4mo6mZSf2iUhSDyk9Mykr8isB5DHU4Ojb84VKN8nLgB68W5J2gkHXiHnBBxFEJOO41cj3WZLiajgVR9yLAWrwF2GQ0Gj28KckSrJWktQ3f23Dq7vsjqPQxfZJbDUav0q5bD3reQA3MbS2mhB8d+Ce0673YbMWF6uDKAt0mJe8+mbrW0/WkiFtJkhjXUaZRQsy8nQ1Z6tQaUBjEn2141sxm302b3NiDKapFxU+LuIkm2pQxjmAf6D+3t8XQIYgeSz8XhU9TptMH/cH8DLzxoWMRc70ikNPrkc4g4M6z/8f2kL9u1IF4DWF8nD1v5dSrzLxt2/Mg2WrYrduTKvrbbsoITRwcL4y8q1xwXUrJeo/iqCE7Knp6Z/xzlsCRDjIo57LuevI9rxBGHm5
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
