---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgAW9wReqdXGu6iHPV1gEfd1H5pbIALPH9BYsFP9AOv0yJD5cZp6zybhxURsgVuHGnYT1jvZSsqdqrOTkLxKIiUjMY9JnUKxKLY+FViF0e8lBZiRnqJs8s//M3s4mShDnzl4iOkD+HNpAywn+Niz8uomK4KqrAq71u4IOCBjf7f/5ceViZZ4lBYyDHwFbrzUZ52EnuBMPsygFJ3JVEjTdvw0+qNJoZefMt0/Dn0zprN6j4O1OB5rfScRAokmnwRkxIiBXESEKn5+1hr1d/tbmmJeO+OZ7KBe3BgIArWX9GNfoUOP68Z9rpqRKzaRx0iK3tCZcxwtBSk1sK1e07x0prjtKDq0iIYx0Jz9r1HguNZKIOKSoKi0r8hvlWoCozQUCQEJnfXDiMLPInWNL6OQf33voiRpbYxvh9qJgyv/WLszGW4SDcFlEaONBUnbe5ujBmEYNWQ5dvMb2ZtGMueoR3x7LEORifvu2HqH/b4JJc4HMt5b8mLwEXv1NKciqnhVpS6QEcCAyl36r9074tH+j8HZY3oPGDn7661rUcPTXrCLD62LDXrX5AXoamUrCEOussytkKst7UqYTJHBGuzqmiNKKUiquiDp2ZGeK8QbgpGi6Q+1OXaZgsrL5bYuyyvqw6+vmEru9ChLcENpgkDjVzb2zLxHO/v1ZvYYI1tlsVDLw5IAUGRJpPJeL3UktQ+HtFwqx6eOmoXjaijFPy3NqqB2DyVK7b1BXbJcl+3dyT03rapyj56qS8rLHiZ1H9mruuyuBtnAYZgDyYhMrE9PaWU7
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
