---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgCaMwAhO8jS58lVqjbWJJiBy5sDhaAFltYDibix22QkaP9NMLQn7UYTxKqA6V14oMpAZsubSdTsWhcokteGgxmejGQCoi9D9oJuAGxvi7cqpjWJ5QvjllWhFBUakLBxn7tbkOY8yhxr1/rt0xsUBPQ6PHfFFTAAUMp+wuf+eN3oSBCOXRofbyOYPHqSahSabndS3vv4SxcVwZAyFNPjokS1MbqxY8hwzf8f0ym4t46yvj882xY59RxeMZjLEvAbeSlUvdyPVSUDY1VESRugQ9ru7WwROKxihahHVwOQKoZa8sadf2kMy3ydRhbmoWbj74Cb9wmV4pSrKljrRUVTBpqDfz/PeWP8pbSvopXPlC/xPEO1yRMt6IueFaVbcFgkYGpaJ8NhOIFYoRDr80yxMWoKBNR/E60wksKSibgc/tk1QDXbQcL0xN65Fc/1SpXjBFaAowdph8fUKD7LWoOBxHB0azGK3SCdz9DpH36KTLCp8dyWrRjyswuwhNc4uWAJuqPEm+pgDp5Gm7lm7cJ4t6stj7vqaTaels190FuTzniuDtcduIHcrHNwU1QqajFPho+sE6x1U/KhChtK8Di+A350QZITAk6qefO/EiNMOT3J2nUj6nU5kwa21JaB7nkPMJkakcQfffmN+0iUAe5Szai2wpbDHdQ8hHG+RxquNJbbbxi9N/srOsgbPhUagsdiOOtBKj+J13U4R+qttUmbsqDbcRa+Bo9lIMJVRx1MBqYTrA1UTiJjhQn3Sx2AHNp7OCSpGk/jgDFLnDsGnn108qzI
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
