---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgC7w/UULpQAa+TPv/XCx9LCgFIYiK04Ib3+EIu9pEwBcNyKvzk5/hvP7hwkRphTKDPzAOm1xP9iFzb31arPnWAw6ZLlq8ir1vwBLDiLiOG7ypdBioGQyClvEIxyrJ0Gyi38oA1EbO6tkSKwZ+Sfa/nsHtBPM8ei/sz58/YwhowlumE+WSv9H8EShpKd+w5mt7dIadqoh7cvudy+qJicXL2uQXRsAq6RWcVWiwzWupGeoyEkJ/Fxojzjw3nRzyhePBK+BpOT7rIrChU70onwaUf7blqWxPWRE7OPYlbUi9Eesw/N8+GJkFIV2qenHfgXblfBhQl1j7TEEnVdzYCG412xT0S36tSFlZy3ZxNQDX8TKFZVAqIvwZ6Il1juAUtlRB0gwavmxnm6CBxjfgR4purndELzJuRTA66A4CCdEDzLNaPrDw9LMwFqpnMLtCaFHtg3/ixGSjUrV8j2E+i8DpTrHIhlS54SXyCmZ0nIlOxcyXbhDYTem7yiOy5Q6uJCdOkxG86G1fN0Ux4ttQx7xYayNCR2MSeMqHXnR1Gty1iLggQrv1dLxm5JJhfSpRS1TjhQLcavdasrOPpBUOtkfETFtZfyqqoLD9T+TMPjYKAgUw6F/aQdj/ZfPH5yYJI0T/mDVGtL1hPVOGTQzxK5OwDqaIatZAWY2ow2bDACjvqYeYTSxDY3RJqoKBKFRkZHYgAyJwE2Az9iw+6wV86kTfUxyWQqhL2IcKdVbzClkF6soR1TLLw5kkwB8h6jyArV8KgjkKb0DXBqDQhMneql6/3O
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
