---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    password: AgCZ6k0gEqJC7/O6ATeMzTbss3enxUXjRWqf8jqipUQ7lh3Foy4ni1aunB+6WNTFYnXDKWXAV+Wqn+nVzzjdVZvrQXJ9C3qkvE9E0NeC+6Lr/TtbxcL1QuTVhz6yzuns3z6IkaKc+33pmtRm8MlTCXnHGsakKpQZv/Xlsxi0PtnrK3JX5vwoWR3l1PVXq8oocuJxtkZcaog3w9RDBJaD8hsmb+i73KhR0W76dBshoxB6UUGFFXZsfXHfHNJfGndvU5zVIleaVh1AIrLhH6Fa7zDoaX80X/D0e9oiEO0iwcl7v/JVwS4RzqpqED5jRzQE5YRK2GQI+Zb+2o5YGTnzw9p4bJsBl4KQDz3gNwVciIyXIB97ZDn1o41Qs1XtLL051MSnkG7I464nvdRKq5nUOV19r3zPaK79doCyxbw1VjFudmzhTSTeA+c2SavyvzVFeV3SQkr3Ajb2EzdBDgxY7Mp4Eeo+wgKZtgz69FyZfYKUhFWw4TQdCn9Xryp5Kd1pvvKXhVdOMdZES9EfN+zKsCi/dp+suGB6FUPOPTH+zHN37T6qE3YBTyZbuhyh4txoR7z1QwLpR48JRzv/ZdRUOF60EXalobzy3O3g0jLiI1/cuoLhRmTvOnFs0lCjEXgcVhSE2/KNfiOKosrK9QzbLJ/XJ7S4911eWIoM4ePG0zD5ONe/hyMTWj66ozUa+Uqa8j4IHsiRPqaQN3qmWsbGIN4dUzjnXOG+E6ngLfR2ZaPD9wjTAsr+i6VePOLZ9O+01TkVkvNpxVwhYLk65PV8Em+5
  template:
    metadata:
      name: redis-password
      namespace: redis
    type: Opaque
