apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: postgres-secret-store
  namespace: tandoor
spec:
  provider:
    kubernetes:
      remoteNamespace: postgres
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: tandoor-postgres-external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tandoor-postgres-external-secrets
  namespace: tandoor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-postgres-admin-secret-for-tandoor
  namespace: postgres
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-password"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tandoor-read-postgres-admin-secret
  namespace: postgres
subjects:
  - kind: ServiceAccount
    name: tandoor-postgres-external-secrets
    namespace: tandoor
roleRef:
  kind: Role
  name: read-postgres-admin-secret-for-tandoor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-postgres-admin
  namespace: tandoor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: postgres-secret-store
    kind: SecretStore
  target:
    name: tandoor-postgres-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres-password
        property: postgres-password
