apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - persistent-volume-claim.yaml
  - external-secret-postgres.yaml
  - external-secret-tls.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - tailscale-ingress.yaml
  - network-policy.yaml
