apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-data
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
