---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator-extras
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/edlundin/homelab.git
    path: apps/tailscale-operator-extras
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    # Note: This will deploy resources to their specified namespaces
    # The sealed secret will go to tailscale-system, traefik service to traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
