---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: worker-only
  namespace: tailscale-system
spec:
  statefulSet:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
