---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgBUeDj4woJuv9S3cjzrxE+tBfA+PLA4i0tHZdbWr8AIuFlgOg9TZDyPAIYXL4iUVO9hVB195kGEsOVa+zb5m6EM8/p2Yzz8l7m8tgUNUzPad3KYbIoTNMj+mxTwgRBk/DstYLsGlTYg7q0eAOqbunWANNUDjOuTJXq6dCVTTf6Rh44GnFxeR4M4gozFN4jZKvhEeI4IResRYml0iDsVl45zgenWAdvpBDF5F45atT6CJ35jHrXPHDB1YFNcxbSviuGh/1PM2bulYUd8muvV5/Xpq+Hsyl2UJnXz6tRNsUkiVQWgLIjVF9etxgIq5d+En2THWUUbHisTNdLIIHWCI4wpqGkScc/fOR1q00l5trad5pPGGlQGax3gGAN2pu625AY8VepiI/1bYwZtW8MKq5c8FGcv9CpjV/Ktlo/f75v8/B3oYH1b0RRfFaw8EaLs1CtXSkNlYL8DzgjRpDEtcFBE6ZKr+5aFa/XmH5TuXwYG9Bf1Qy6JdRdtwc+s8SfdNRgxpQt6L0jOxdGVXXdrYxZCFJvR4wT3viZ3BtSWVCdVRo+xn5hY87Gjrie02ZjePxAy2DU66zw9d3GTiL+4PmqF4jXzUuuGnfFQ/qvsQS4iV/+XwGgRK1i3GrhA1L4x3kbqvoXabpAtjcduSCk439xZyeC6GCnki/R84tWW7o7LkCWh2Y6BmWd3v00YuIVxiHmsXFjvnBRcRkKNyRlD7UaoQQ==
    client_secret: AgAziqUvDrWBISn42t7I4NzXleMBJVwkKg27J0n6AITAXTE1YDplXcRepobJonHPHhdIgoOU63fhzugnWUGOc1kZEfonfvR5AkqBDJg2fL8XzL36hLhL7QXHzrV1g34HexGOAvIxA5DOMGkN2WZwfxoEhJA/s6FzfYk5EBKFOOAunmZVkl7a/pYIOlgjWp9/6KO/qaa3/mrLkpYKptG+bKXN4iFc1osR90yhUoiy/GJtymBbE3inzOXpsRvU5FPhvvD5vuCkMxMbkJAE30+GX46CHghvk3CtFYMhn2QoGVetnocECWECLqOngULaYBkZyQZwfVmC0ytOs+tPd16OOpPT6zMBKvhy8yb2kAURAJt4ttFgw3p2a9wq1/W2Y0l7gZ6zaRCTUKcVQXONVBR8rYRRv02p7j3YiZqh6PsZizd55U+gaH7k7lYccHVsd6votbymCnYgWD9e42+Vbb47wKhOSX+Z8JE5SP+QceKoBs9bQAEv2GTEWnhn7+qRrDUvMfjb0peBejuOS0TwUNiS9S7X08Hp5NSQB7/vfA1zneNgK7LGz2e2dBJz4ggHGU1Da6SI2zeUUHTRzYMHp+qJLW0n29jnm+Y2NvPj8Fl0DaPzpFXZ2BQVSsa2RdQIthysp7NMfqIPZDC4KC/IgC2880tQhM1FhWs3TBl129uMFtXljpstrKxUR4D08O5wfFDgX4oHeC6inWNTj9i7D41ZA9+yjpvdI9lOurw7Wy81A5g+9VOEgqhktUF6plv2OquMugcDyfa+34YuvIab2T42fJI=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
