---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgBnZZKhVogk6bH4trU9a7ALh9Vgd4ObJs1VHc7+N5/dZV0JOzth+jDTrZthC+J8Y5xnzOb1CaFwLKJpZPs9pkRTu6pMk0aCVWzXEpgD9PzZ8WlXr/Q0Kh6ZzGG+CMQUoyyOpBnOPEP6ljaLBQH2NmoP/o+F8v7pqfR5gY1e1fuNep9SxZ344Fac13RbsDw6mrPingJurPS78rWjOY0QABq6jn4E8nAlAkNyttwL+uInjLTWr6lXENosIXHrrmZ0oaUjvgcBrjbkFw6kgIdfrFNckVG2wmPuxDcodhLYy5YFiCUV01KuaTm1A3F/SOgphduPAj9nlEjs6XV6/FjbAiQODHJlvHyP4ptdFQY1jXxHYp+svBrD8obFTmbtLkUxecf+tn3now5AKDgEHfP/Jeliuoi4NW7m8aosYm3FVQH3WAXoYvdmqutVKPit/V3FR+HO/8CUvHrNzHg/ZpqCyauRx7XBwUUxVG048NaMfyV/3igQ89Ow6L+TbmyxvrLSUBvyhRfa76DkIpxjNXjziXv4RpvN/iv00qBSdFvOm/2orjU+S7SDfLrz8yMTqdcmX9lavLb2ClsuSYJ6fTHi67Zh/3czwLhuI2DbyXaJDggkNaWPBzkXH2Y+0LP+U+vJ50FysLTg+ZqEq0lIaSyXsAyyUEag3H77R4u/Wk+DxEgHMybyUTeSLpPd0tUaIAYJvSp8XbUqE/jiNfJDPBM+9ZFeZw==
    client_secret: AgBk3emf4IwhhlqfERvB6ruxlhqF6xp1rYXFDOcug0Oo9DEs47jizL9GIQteHoTkOqDwQRFdVQ9OYk2gbWJb7r5iegQhJOzjPBjxx3/vrEW3V9vd1iNgSScc5WcDgNOy0IMw1qeYakzWe1Vx6hEtId0q1bNxOijzjO/5wuPo9ilBrY7qWmbG/ZrXrls6xlhVvDtBujFKFHfp+E4teM5GbAn8yMBkFlV8aqJUZcaXHloEw4UEwE24YKnEt69odl4iknn69f2uwIyv42M+R2Bpyv67B1m3Qef4+NXp26BAoN019iyPWPYQSUe/R0JCZ82ZCzCXWvdJ6HA7UhalHMsZl32xc9bYN2jfTa9cWrhXkG5MKsrMCwNBeaMCPiF0RMsB8MJf3j2X5AG5AEsBFKQm2KLqyGMKcvtUjzUpiwWd0hX+QPVaXFI0IdBO072kn8jI90+7PVnX7M5uc6rJoa2PcNhgyYSRyWnWPztjQYW0Mmkl+f05SYCXBHvMLJQzOBjiqZyRRGnpVs/LvXgSfOOeWUrhi8GA2BizJKq9dYfoXtLLM6z7OLrow3ndQy5AOaOmrK+23Zs9auyPe2o2GGfERVeU5avKJt23irDYvCEJdofBhseBaisllpfpx1AgJs3xklTpsj+/XHY7g5ApbX218bvHawpBdeinCCLeqVdoRU/b8wtgueFGWrpQBc/X/EjuC1kCFFIEjSKMjGofLzaKx9B1nnSKVnu4peENE7q5M1gPUiZ1jMT+TPBziXG7+sB3G3io5xi3tfpzP5xVjcHX46g=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
