---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgCR2rjU1bAz/lFJi/9e5cLesngT9EXQxf4sEyJGoS5MqFOC72eZNUcwSPbY3VEjJChFssa1/xgdauAQUlilPa2XtnId2c7bPdD1Po8H6ZRSxGqr/z4eKjGCplm5slemXWuld6szydQm8nk/C6AbJOp1o5N0Rs7Xam4/13l/CY/B4kyHA5Ns7gs1zADCHilhwogwgxdQ5YQO1ces+F8MJ5fKrRj6Uv2LjaDaU7OfoTz0XPJH6mLm/emOrFwfxoXiO4jgAWYWaZx8fysUHZCpmReKsx/7sQDMmqTZuANMjXZdHRGELXArT6DQb7xAbCMzMA8m0WzUzZ2TNFJxCECsqk5MlikF+jnztUzeh7PbT67nych++rLrXHi5oBNVpcDFL2BoaqSBQU0BBttqxY33JYBrNnsGcrE/RjNijqDuvS97dAQ/a6/nO2k4eD0iZzK/al5Fb3F0dhtyRuKlAhEFG+QGaPSajwLSDYAdwSmadOKtPnQ/bz091EqBc0NQC5p4QMvqB/9xo2t4s0XOynok6El5cQHXDN4VmrZiucPkd5p0jUujxsCBk2ypWtk/QM6tVd9V/sNurETkUtJUIaEj1BamRDkozymHaGqBOAkXgP+DO8OvG8N+XGY9oDb3wxxMRx5xVwc8xTTRKEk5ekizWMNVzpmmMI/104Q5D1J8arVCS5KiKRLSHbmxnTpUpskoZmhzWoqbWP9PSGEQzW80SBUuyw==
    client_secret: AgCQOt8C9vNAiPOrCPxIN9D0BGo2w5+t95YIJk6H2JXCfBFi5S0lIz2/U3+EOVadaJhie/mvBNqxLcxt9f5Zx/cRKwdDjeizbcaPkLUcMxoztA7FYjyisDjgApTbSz1OzYoi3IO8DFQMr/Oj2+wvUSw6zFmzI1BGRK2TrxYzpSY3XANA0EqPOYBi08HgwUmSWjsEQvwgGu1ZdXgFSsW3rZKIfZwckWmmyMddmukLzYx65fosUvlKlnm5lTPqo87BZddBSaYFUMoCntnsrrtrkc8UW1jnZqm8jkHGnjb/rcoPv1XbLubL2FxUVKRcwzmf8hckO9P99V6pq2UDAYZ2m7u58YsPkax+GKFwSmTyPyCTc6hB2Y1lqBaFYV7c2TEcNsbBIr9uagYMu2MqfDhzxVaAMb+N6aMhCMQeIx1yM2K0uWmkr3mLVBAUCZbOtW+NX4ipLtz+wifNDAPEyQwXDsZvy4rLBWTYSxlIFP88DXXXZbNUzVvpUhUv3SvBPbTelIiO6/qpUoRFNhF887qKOGfPz2OC38VFd0pRT2J4u4spQ7D65fWAdMSIOxzO9fx4vE/nyMULHe/eudmXn0np3CfkQ4KjhaVOl9PA7FfEzNY5J9qo07+AFZcIcHITQTE/mNfa/hUo0sMefVBTHfTlyOWL+cCOEVa/il+cCcLUfEsCIfZ7/0zs/evVnr9AXfRM0SITSa0OFHAv1Tzoc4TLk5Dl8yyxvFECtE4saMXZu2JIciQc47+RSLA6Va7+2jQxVOp99qetLcEFtX6hIVhETys=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
