---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgB9ZWRiClIFYRaDka73jhtiLvw5IRdyXA+ljKWWGGpBM6TNXrn4Eh4tGRx8eOcHSCFPLBN9buUkZw7vWEf0OaTWP6jRiQBM82mJFHS6hqtBU17TUtQFgxnoauXWigtQM9bNzOGI/hFmb+gjMa1eiqr1q8yknaL+DXE3rGP+V8LHTXpHrnCM2AYaz/L24yUtl2F++Har3SxJFEGUfmSBpxDv0D8BjgJ7m1XZa9jmmKialyRhitq8OjA3aNGYCiy7QvxKUPsYu3mrf1yRNmq3KlYy2f4iMyxwcsXzAIilTKp6VBa5kdD4CO94tAxVK2vTFS2LZS5CmD0PlgNgyEAgvKvze3N02ujFjinswnl02/CUSc+l1lG2cepZH3mGNC6uXqbyX1f9sDob9nZjCQ/dS1vCCXZhIrkh1Erljfy7zrkqINnjg3WU6UPaTCqhtuSvBBN+i9I63aO+DhoFiJz3Ma/j52W22B07MXe43xa0/5QsK1eMOWnUygsZPpWY66dM8K2oeh3uYJFKHEvreTbzsCdPDcRKMo/ipmk+AiXZMBPHr0u+BgzCi7oZt5Lefy3XcWNANtVbRo8vaYfSeva0INcPIAcGbTkG0oPWtK8NJCWk54nLApscI6PzSmYdxkmS8CU3iGIHRBl/C9WhipIdFb1EmJDbJ8bJ7optdxMAx/Lyv2QEtFUQBwd5wqC0GQaQ9HxZybKq9ZgEVg7p6zV1aQGtWQ==
    client_secret: AgA16/Z33jjh6acj0KKSJNlDAQDVjAT40/lNCdexvQTpHZBenBo+0XiFulkWKcH8XklbDlEgMzrKWRZNeQtyifcRguw7qDvg2671eF5/fCAD4TEwMDqcNynR+wOPKN7+GlK5HZp0rln3bGQWwOL3V6heRApKP7dkD+VZjj4gyGIBBnfpfF1/uNXfMmPJpWTc/FWY8taMsSrzK9I1hma+Gw2vsxG3PpK/+/wTYCRPpn7WACmvjjh55SctLWvSDdkzj4/T82ztkUvPfIklOlWGpu4S/RqIN9cngbHfNjEcObcmag3sqgSw5KgUg7Uf0e/39P+C+5PmwmC88i4FGfgqlsXL6jIMT1JIBR38czM9Sa6VbCiUeLWxpcEn4Dtn84DQHlhcTefIdf/te1bn1HNu6DsjudwuUKAaeb64tFusgOuQhaJdpM6jGbwdCjq6yMuv/WeZwcqT0+pzIDSMn88X8A09v7S/FQ4YZk5scvqnY2bGYCF9LBAtgwoO6heWCZcbphKAoZl5E6afjA5NwIcAtWi93Tba4UP2mn7Q/9ovj2j52NSzP4M+EvOgYMfekL/YE49nGsRttN2euIrlGCBiUxk4RKsWCm+yL8AAzv72S3lsOVBd8w+KduNZvLzzwRvbehzNM9esj5T68+ne+n0K9DUdwupEyyNdXN+30z4BOyP4MP1zXADGi+xyL6BxBXQHfLQXBjMm84fvDXnp/k721BsYbfZjyRkx3HVGO9EkzYQIlcLYF4msglDfL3Ru7I/da17wXC3LOWqqdiiIyKs3ZlE=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
