---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgCNm8mHKi1I3RZ+i5q9tWmEpTHBqbrwoNN/HicB9xyti5rERh4r0XjrqzuddJiSH/YLm8LZw+faqfNe+t+k744ALUedTh+scRX/oDuOe/13113X2RcBk5KNs7IEfXeJT2PZ+dPngq/fXfQRqicjP2rPNgPjYtwteOs6xkb5jakCUsVLfe/6Xs266xob3CUZRf6/g5w4HNaydKl5KgbOLwOlZ3PRSykC3V9ZZCDK8c92QEjwWf1NQjinXWLlLauHErpuRQYR925nZR+oLfTQS8dSUI8tWYW9Te2dAs9dggcRnAW/Ln3q9E18qjAmMser36nwG1TWoEpYoLSJQAx3IQCj1xp4O/Xr53tePCEpZqv6vly1mSTQAVNb9ySaG9cAgm8Fz2iGVQxbiSnTxmLVNqyRAqmzN7/u8WSJ0qJD6FZT8DEQXyJPV4cvAR2ylSO8DeEB9TfGDJYQAgAwQKhD400I8GpxID2vZgCSVycRoCZ33EO7AtCsBI4Wekslps6IXaMYkejpoBKD9CbrJ2WfEgaUxzIcPB2u84QTGyuqH5Z/SKN3EBd2RKMhC41eORYMzZJ3TYMDQaGGeAqbM7YlKe+NfL0QSTWGBUzQ///MujfAnIEKqhsqRkqFwQ5slQRMgptDyYN2QzRHZ8UwRB4KrVkSc4+fovl3FfQpK36+1k3Pdfx+fRLCTMkHIsEdwUJk+jQ5RlE8W7wQ1MmNvQFAcZ9wgA==
    client_secret: AgB4s2IdCIfCgmNXbKi8EW62IHJ0YTOO6D30xJUfVC9XUrMa1ids1yYtyv5+aW1GkY261/SHM2KBrNs8xNERJUXAIA76a+E8aqiHntOV5BAgEPLz3t6dx9NFlWfXC0K7sXxC5wiBWyLuBbDpnpc8WHayLZ3uVhPmdzgXEy3SdflHTPAS6a659oP9akIn4m73gaSYTJLEiwE9QFW5Ln4UVfv8sz2nzMML9pFa3eqwvOg+GV7XehM6hqoU8ozPCxkTh7qNjW74gnVselG+qA937IOH4bIvy3IKGee7Q8YYm/MQ1CqgXrv/++LXfhN+fqPGrLZMpLntQeUNZFhVYm7aj6dGDJ400tNQru6VAD4XcKKTxlzkxjhQIFEdoYUfczSrvXU6W8lDm1YjJq9NG3FXzTIbQVhMDxuOgRddcpqjUgNrdyUjhv99KSHivUhjpnIZB1i36IglNzPgPtYrICL9NqzkUbEt5wAl1MyEFlz6Ov/yvw8PMccQFZGTqFtPDEb6sdHsiV0y4tYopMANF0UPPJNGEuDzdQ+F+35pgvGFukTKLGCLFyA2BcuoV7EsIKLuV3cEKx8EYl8/2ZYWG+lH6/ZyV1wAm2UwWQTwTqdyBsyzd0Qzlqx3kFHS9shfmY9ScE4q3zrPQYZnUaB0g5T1XuT90juIUNVImOs2ZimZKzr3jtbJUkH8s4NKYnU91nNgGHqokwPcP+cdf9eggv1T4YXkmGUYFE9ful5IituXClhYCeleLSxQPWiLDBcwQJm5PIRu1UmqQ5fRgnt0NLmzkaI=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
