---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgB1tmSvuD7ycWrMx4tcIrIt7/VfhVZxyNqu/L4rJay1HKw+2GjZ3sux2TLCcf03bOXLm9ggNLfSX46jnlKkuwahhq5lVVP1xl5CRBJ0JFSSa2PtDKyRVqsjsVnOJ6iRZ+6LZDbblONYiDsBA1HZ8v9CyUgbl32Y9iHlaRhRi9v/nGEI/VzSlEv+Bq5WEJ8VYfYZ/mXVjDlM2vRlmSaH/gVvqKFtYAvEqwlnpDcTF6x4sfiPbxrlZHMG/ifSIKxZvWgWJ07Z4AGL8az4CZFQRNzgqvJ1fB0GPSz3UvldWt05e1n64FL9ZBlqMEIG19/QT3wI7Vz/st0/J60VQhM06CgwFgSoVgdsEwTNxXHJLAxn/uj4WeWAiKVj0uyNTpCyYyWtmGTnJX7e8Imd8IkfdBTdxbYpgEXYVjw4+YWRUcK9Y3Oqq5dNmH2r/lVeWexHBwwGnS4LDMRcmjUBFeKlOOADqsPRJxG8F6jLYkTSGbZkrjQxO0odKjjeLAeDPihzCOeMvRmIp+Qcnt34rnPz22YExv+IMGHSVxfjiawNsj/kxQr+TkO71qkiIGoN13HoRF2jfo9kD4hsuFb3xyBuFaTBSNr1bdMAZs9bx/uxs3EXJGXHS8mjVpb3CN66ronILlgYgcnaFLTSzojTPee01/gDWzOe71eeqM86uBTdAqCGcDxwedE7beltWswLFFX+3dfN03+4fvu0ETY9SePJ4i4mkA==
    client_secret: AgBAXWKRQr9kF0kRpPK6WFR6L/hkYquNOBcneGToQ02kLkkCIeRO1nCrmposb8GnZtO2mnAd5j+4/x85oq39Gna1swkRcqcwTWgCAbYTQQ8VYtB7uE6vYzbYqwR5ovJHmzsusyKBpwOmAiGi5BtwXCSh8MKxWC3zm/iLNGqEaVmct53KfkKvVS+Uip3GRSnPJ/G5ku5JIObYg58M3iXSCqNf6qkYiiYHTE13rafK3MOWmnBu3JLE5uibYmHcUROCbivuKdgVji3RpE+VFouN6e/GknaM7NpASzW/Y+fl81zHDwgqiYXcoxqtnvMS6aLY1CyNqnRC9KzeSZ/A5N67ZL19/MsBxUdQ6k6nU6k/G1hn/Nm701TXORdNhsvFyBYxopR+m28Uu8MJY3t2pbDp9qFsOngqNC+hFioxVWs/N/bJDvKvh1rO7irOoqRjkfQ0lYIRTy0WMYfmhrUcSAwg9wmQiKS+D3L2pxXlo1iNJ6FYF310W49RvRpwHEL5hGfmDC9lSxJieNBkBTBq/EIcnjwl4722x5YBiWqU5XIlakzcBuVXH0lJEviUXDZYm9W1k9n3TX8kQTXUdGn+PPXjhmz1uSR038mHqtk5tB6h1mHg2UichAv5xv1KeLKPpGV3T8XqA+M9iiGwRdXzcN6WjpGtA8mChTVa+DmqTanQH5NQogOixN9bJk5CJADvyOtQIBLSZX2vKUFZ75f9mx8+0N8AMVpoUWaRXTH7IIUMNlTtR4IZwJmbN79g4zHuC/YSW7a9j1YoL7ZE/en4I3IhCh0=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
