---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgC1/Inbjgbd4wxaRiY5ihmS249od4v3fXsnmW5mi71En7cW0O3dzh7YRrdc5x/XBGgE1zDWnhyLfsw+2vtQsR2so37JHU1L5qik5il4/EINbp+8pFbD3WXYJBIizCrW9cLc2RXxSj/zEnfDb8Rvz7/LEQD2KlHKQUkRawckagpOzDyFQMeTZhNDo2osVVBvamDYicwwS8MoOKLRMf2WeVTFa2ONnulI8vqtIMMd5Qg0f90vpEHDNnEzWt+8mLVOTWpGoIyFEbvVJV7mYLbG+cUVshPHcu795DMCfdgtbCUAkGFS9Zm60nfhnmeI/bXves2QI8kfXIDFNa6nnW/Th8v7yYVKB9WdQ4Zj2MFjLmDIyoUa0g6hkg15gg+f99ad29CYPmPLNUUwtTJIXtB9uXNqRNlA05ULf1Qs3w8wtYOoa6ZL0YnTjuKkpWZdMDJ/vp+d4crLdFm7C/PuD5mH08q7HWue8GRafsssATAOgsH2Pq8DNLC8jyaaIg4azr3mG9j8iGYNvCcduPY7X2Pp960Ofuf5ssHwLPzX7oku+2PsHef26AqT5eOfh0ZV4W7t2kv6vAN5Uc5VcP2gxQIbjdYr+7UwC0v/tDeA8KN9kxSxg5iO8W1wfumWL+ChCyCxHV/0GRA8qLNPwtjqdyXoLMXzIX+XyQBLqurtb9CjV/r3wi/GP5mLe5ctXjCdTtAmc42drX0s5VSKVvB6aPuo4NLtKQ==
    client_secret: AgCL5tO3mFmOeTdIu5QOOPSM7QuOflh8ukI7T40JVS6E6o9cbmtHqw3cryOdNNXgKr9xTrdhOo4H2445ri1VelWl1hN09VA8Q9ktbcbARZ1i08ItuLudfrX+didwZSxhmdinTSn5yVILfpfhOuQHX6O0tjNtstt9oyPsVxMlafNoo+7wLV5irtkFFTk++PvM/LoZMaVl1elsB1dLHCStte+lbuoiKaoA/5D7319xyRGYIrGF3NnhndpcpyZ6LjWmJ+AhKILucT7QjckjEyjiQBlU7D1D/ZBeVpLRw1ell+B5Jm4XPnjkHUSItVkAE8f44/sotHnQdU2D6H42FaNlFe3dU7ubVzHjLuFs9KM0Eq5ACYLkvEw10jxKKMKRlbBdKLS3MxKFBBuEciN6wU+95FsvFhStCsetSOtVFf5fsnhMWDCdZ2682nQaKUkMnwuKkGwE5RWLhPUYpGitEhRpBa8XCsADgsfopWnccYLx8Uzvu6KmktiwOg1r4CuDjPl/aIhCLBdFnl0pNH+KAmbRnlDbj3Ne5bDgx385TtzSEwVVg4A/O+5DaPocjDp2CW8NubIOhIuZDjIFNwzEOuYhYox+WWeXinnUEWGP3pZxVVBGFFsLRmTwjDvCVP1DBVTbULfel2xZmTloKqzST/7n/yHOH6FEGFnW/GN868qJA8TsdkPC0HInAv1h9YEZtVWUlJqiIU396bZz6i+CcYfKfDVKSog77gxnDUI4mOUofOEfPS4wf3yKUxIQF7F2FMeyb5pF9Eaob1U4fY8bpwB+FMg=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
