---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgBSE7rYAyWlFWR17j0+4GtcaIOAiMNF6JFd3d0nx987D7mb6O1pJdrmS4nRsOJxaf8wgO9dxECcGdfiA9P1DGD8nHVBlfAqu0euDtbBdeum4Mi5HWAT0Z/L1RgZzV29D/qdwVamgOZcHDeu8IHkl3eROJBBp7d+KNzpPe4+U01NyLLPqKe7yY8rVhHAsf+FbWZihGcuXsWNUCSmKRhA5SPGwyWbwNKBwWGhhAPK4oL18rEsyADkICpX3T0492ei08oJSBEKBSI6DuUdWOzNj2Q/NsTf7s2gciqCvqVag00DWIqxx+aPFgDIOVlunET+RF/G/2cYD1HXDsoBXaIvuuSZyqXrqaP7/0h4kWlbjfC3tqSdXx0W2NNMAlmJDgIreHfvy2NhxAlBEXrSiH3JvKGC97OPPUUX3EqC/IZUu3lavFGrWPxA4TXRyurGlbkU0wzCz/QlBEp8+xZDNrcajgw0gQAXuKcW0iKn/2ffTEbqcBdDApvZj3t0QLeGGXlpsTrGzlFYq9bGDkcKsN4SUQqHKrcAgo0Dkk/6d1BJpiaLbGxpaB3guGdGUaEVKhr7P73E5MRCJGhEqDr71XgTDHTbJbQa8Gzc0NgYaLuvcDjIEZDQkdjQIgoJkv8Zxs91EB9g1R5YCubull/J9kQ9HGjDWhI1nycrWcmqT0q3lJzgyqXaY8ttgAFJ9aMU5pVxAPlOvzlZQNf/qUoXhEJLCjCaVg==
    client_secret: AgBxizrdrV+sD40KrZ89dbZ8ExH+xCB49ZWFlznw14uKSAdG6dW7l1TB2MuQgOqpTiMojJu+gBvJFmpkLUJJ1m8ueDFxCgvx7L8cWTbDQ/bF7yOZg0WwUZOgW3Qr0jIOs3Cs+gmzzAyIQP8kdQWokUFmOcK8LgW5GqNd1lV2ks/ZjxrUHHDuYUBmezcPAbQLzRLl1aSH2VlSydAhAimbgsir+RmTsDdAUGUh4Il04KRLAhxGKf8WO4aVBKbltW538cvbQBmnNHo5/ezIOkBGMcC7F6U9r1S/ireTOgW6L0/tIOXMfyMo8FRuJu1AZSxy0qr0rU065Wq6VBQAWrR2qR875xiPDzaiION8K/RivVcDG2tkPluxnOaTDz8QFkfL/bWgWTM/Dn93vkX0sNAZni6G7ThqZ9TAPaJ20xKAVJAS13Ea4/0ALhUGvkqx1VeMsZlDTUrsP5y2orLbVQWcejjnpE3gVT8vml3UuuK/sqk+XKBf3+RpeEHlU9HUzmklFcChdokBx0AgX4JaQNeZGiOEJjSsXxCdw6jtGtU2Z7GIrvdTqT6+mb6P6HMtinUKucRnWqj5j/nlONsblzUr6JWyl4FswHP6myytvdw74J+tVgvJxDV1YX6sGAycZAZXYwISde1m8KWwmHQYszTTr/iVsBqxSu3DI+nIgAZEATgavlupd78k5LlldviEBYanbcFvWykuE6nPc8fdlfPh94X135a9I8BwfX3m6trWS37Z7RQVEtqpJ/nJoVwummmF7xwuurqBKDCXQPSHk7NNJrE=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
