---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgBUJLzkq8Aqsi81USnY+tFeu1b5PwqFrHEFf1jE0H+77M6ChlZPuD6U/eNdEI0ElMT7wATniEiKoa14pI4esI2E9YU0FWOS1cHXCr8MxTG0PQ6k5MdM46wvlFCDZWIyJqEU7LoEcJ39JbijIc70xBpTBrWvg+o6hVzECyNqLfqkt3d7LQhiJbAcjAInnNTyOvCnQOM9rvp5IiHOo8aRxW9rxfy4VKTHWSOqfzyNlnXKcgb5cK1vCQy+uEOjTRlyQzjfY0Kv13MHITYsu4TGJeDtTh6lFxhQ4my+5bhFtV8DU4lbFZHWDt012uwIrVQNugvLeqIcrl24t+SiLd5Klu3NMmiXeV41FAzxmlXn4cuSRYwlw7NoprQGg3CbBbzJDmuF3aCYjX3yXx0sDwTODOAkMrfvLBHEgngkTfyRkd7VHqgj/NNi59XXArMoBUICHDajQe6LxMDJUzMAPKHYqyFVnbZbCO9cwthiOfV2hQfprRRXOjDBMTdKn+lgqkNmAIEH3YlCV0b+ilXRgvShT0uaJGmJGVFJJ3u+WxU7CK7erEO6fA7SJQvbpcGV79kNQVv/n6DCG7Dnjk9TTt/W+ctk8d2c4HRa+vsAp8FCgsbaa7WZxnpPSg7Wf/U9kGozb+DXK9uzBgkRKOlQVdvm5N3WXsk+gMFi8S51PfxRbPEtpHgpMiNkUnn1ei3iPp+0CtUCvVHuVm7ZlngQ2S3E7aQZAQ==
    client_secret: AgB698+Yp7fy+iOr7QjTrnJZWLyvZTbii0QxVnhnqOmm/mlSax03P4EdLG67hBAzB6g1UA9GHRtuUXqPIw+AIA02UC1IdKi1Jzwvu9dVbwhMrXCuFw2J8uVN6j+cnziO2Rl3iLH1Jyv74Y83tW0XRyxx5Qh8jzwpa2C5Y/bgXGJGNLIrmQyUudDhCv+at/FEPIuKU1H7fEXhPTp+/LOrRO1BruGBsLJixJVy1QMFrBqnxuW8v/K8KlCipzapC/h9T/a3o9O0HGNG1W4Gvy9Kk1nguPQEMmsohI4NYHdv3zkgpcDPmL99lPuky1Qlf/BiXSsO5S6ssOIKi5/GVCvtLtYbXqN9WrW9Mno8jz512LhbI7JrNRPWbGYVJ65oEYpmD7xHlKVFGoa8kSgcHBh08MLPSVxDxvnMEgODG0v+pYLUpPgd+mGUxUDr5PpJ1Pjb1K6EuVMFS1qTfHdg8x4ZdeIbRlmUeG1F6o6aiAka7psqUpNkZfboAmcIiIAgsnjpLI75f/od4rEGyp4V0cHnHqbh17ol3kZ7/soqNSIOOZB+5ozFIn3tstc7/V677uZobpXk+qCcOkz0zfU+XBfC5ZHpf4ron+Epr4FZLx8gT6OSZYHG6jfSoWY/GCtZQq0dzd7SndOb37yr0Ku/6ve28+LVOowBNh+lqULSDq66IZgco/flhzj4nP/bz3ddJv1j2JowUlpkHlmtudnnkpxiX4rHZDH6qlC/Zm/G2WasZqeQS2hqmyfKZwJu2eRebNdhvRsSJOdL2LMFO0JGgLAxXV8=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
