---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgBUTGCXVL/Iq1xbt6XjXXmnmWm5tXJivboamtny08mSYI0SdD1ZKEYWmNSA2IPXQeSk7qKVN/gA/vMkfz9V5zHIKpmrdEC6VknRYFWS9ykMEI1WDcUTCCbColKYvu9x+ocdyO1LJ817TYUS2sWC7Pd/QEhCbcuNuM7b976oohfxHqr79UHqrGwGmO9O6vawq2wZ/Pf4IEoz/SS/6tGlc8PZUUYxvYv3kiNT4Q27v5Mn3E2SNKatwtLS9xLMAVRciEkOrYKfWINh9ISd3Uuvx0HqmvRdiJoPYJ1OoucbkOGQJMZR5f3xk/WZc128PQHxJknpAEO2Q6iqXpQu6btGUWbbWD8nmuRDxMk0OY9L6u1WtT6qXH+PqSvy2buaDj6VrRIqwapQt7VFJXN4UTQeP1lKmJnmAUlqXjPVLUCIPebDRkNomWJ/0BEzFaU2ocE94eMMPeIE6UTVugWpMyhtQj1EfYAXFi4vfiDXTmQZZdByTX8jZADEoHrmNdf5vyKt1vSRSu9F6En1VpQEkIKMlIzzX0nammztJLeZ+YgsFdQ5mfsU//DbQoIjqpU0816ZUe1QWN3Q4etW4yxHZU5ds5wmWtDU8nJuEeW2GE2noc43lSqtrv2J4F+uZz6OL8dP1/SB/rTyK8yWcnZtUYJzDW4kzeJjyRsi0aoYWeyggE7wGvj90+IBsp+RB/5O9cmIOS9a15Q42NLECTHU9lhyWhzn7w==
    client_secret: AgC1QU+tiv1LdhBzB8018hf65WyYtYqx5nEkk6CjTUSPTgUPwptKJ1AJN6ROmyFqMqCwVXvMnMsMiZOYsXjrUW+weJ3tcR7j0dCKSJ8KIOOFz+vQCQhWyCCtAUBfIqlRQpNfUtDotZPdiqD2fsCFYyQjr/sLevtZxZkumiEKdC7FX2f9GqERRDIlTfPDZk5grLLGQbMVtwdte7JypntS5vQ2RHT3Vo3pEXo94t7zgECElcxknfXv1p8xYsWsnQbLYl3OmC4boY8O9+UAi0gjrckA0cQEOoSGSDVP908Q/LaPjvtpsFAHvWIE7HVAjlQJ7u1D2MTI9d/1v1LiSCnqj5fF4BbTkizLCuy0UDtRdjBaV+WVwBc9oEbSMG3EJzO275LoWNirxBt9t8V9p8qpdBLTLHkUNbkNPEJjA8Bib3BSXOkqXP9Lukxw+iWLgL92FptdiId51TMo3o7QPHhh9wN45gA53HpwtweSrc+MpGfl9wGlGHgjSTjkLya/BDltktsoVwhVwovRJkRK3XPLQBsZ0QUIVB7N76Wr3jnq4cfMMoBuSWVGVtz+5f9nBfxgq2GYvJPUaPS2DIyBWGEfqqzVCiePlfKECnA+qPA3pJIAEcEaNZ2yjmFk2U38rMAmtERF9tnL8xf/UhPosZx0BC85J5os79hOZ4NVdN78JBiR66cSTgfZNN1KZ4GOrPnGpYnqsWmPJMFRH3rjCqU16NDqf82Dxo4XGuAw+q0eU+qMFg7DfKKnvb7KgUN/y9Jp9S4HIsRjGdsvj5ZXAOjfeGA=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
