---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgC0RnPe6U8BFkNUTjdEzxtqNBX5yWDKwGAE3U+MBoMXv+4PCts2bBHbBk30T+gYXkuOdlqt5+J+rOTsx0STb8RLcrD5m0Isi8vzdFF2kQ7vSE4Zn0XO+kmZxadb/Np377wyqtEP7BvAE+aw7uMCrzKD3DZU8j3HMUhshZY2Ebd9usUPU8pH9omSpTgUUS9vkS3a8bUcy+eTV9lRiMCqbwZCrqF/5RBwC8wQwONmkT30FhHZGy3HzXKWEGNe/Ql3FMRZByT26fH64ZVcU6n60zcP5ZLt90y1pETzdKuav/+oF482aC5IdSEnY7pYFg27tmIyZXR9ullGXFQNFJTDdO1Cp7/uDscy5msImYvxU9kAPAPkoU0p4W03ci/05NmPoTrS1ZU2fneUo/vDZfsG7vpcQWOYcJJGp5d4maR6m/YxxQMWu6Rssg9DNF9ka5bA4hT6OrX6aH4UV3wHmcbsG1hSF2E34Lnghl8ud+AGnVFpY6iSOwMcIVXlI6QLQH82UWFK6mi262ZRGDIfKXE8bNDXYGBz0cvXMIRSmQKni2X4d+AsJjI3Z+DC5M8SnlOs1+xXilQu1LsH6m6if6Z8ErOHqmHvc/r0kktICXRNrzpfJldZDYq3lqy/iALW1KizNRGLijilNqh1n2Gqm1dsOmQJ2IMhRZjSH/vBqx8UI/hxkkqbNAniXTXfkhDNMcK8/MYqQ91595pRk6c3hsu6WCv8qA==
    client_secret: AgB/i8Jm+lIcEX2C1bm+5H+LUcxQn7GkwZNkanHWXpsr6gArP0pFgxQU/TglP08/BFj7G8UoO0T/D4wlF20+aQVxYT7H3vfdbUMiseOXKpWu4Y/g5FC9+CKFegZ5OoA08QnBdIGs0yXswvIEHrifn82SaR8pZEOIPxXQ9py++oDYRFyo+mSq+RWHTIBj3EzQmn5TXZlWbk4LqIOx1nqsdrKaliKz4cyFSnnvZOX2W5lMUzg5t73aOeOQp1bNs8WN1yzIJu0OD5jT+updvmpuRfBCXxvAc5eGFzrCXFXAwiM12G7sITYn7saxt0GXxILmhpNI5+2LADjdVnO3IGyZpOPt9sARyezzK88ljileNh3Da2HgBQc/FvtXks1URA1F0A7fcaZHS2/ZytxSM+LVbGNATrQf7Cskw1IiqlY7q13n236XdthlzLpe2hlcndpDgAUQFwXpmHGA47TJyXZJU+L30bJnow1yBUf0FDMAGNIHZNiJvgNBzRVmLvb28LQls8RxUhVH9rFkaBwXhKokU+6g/NBhP1GTg2j7Rth4GtSEp9e9URx+yX/1UJwf0CWxSKpgwReQD7+66HcSHJdmCN1YBaKkIZFxs+YJt4Uq7RoRidDuU0ChPaUqzMuvX0168Kei6ZDac29zxsvUJMpWFJ5xswJsc9+oMKkh5VJK+7hyilHMABkVP6F3oHMQmDG1w1nIBldO6HDfLoktrWCvN5EDcuiW4E3BSlkb0Va3EeWYXnw1j9TcPAktFUBQ1FOztNmuoc9BdbIKn0fMQkR2DFQ=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
