---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgAoaENSez8EQWGMugLeTTLTg7cu3Z+tp0NVexF229RVfIGYZ+FQTV0XVcbv1W+sWLIDCrusHFn4fKTk93nL1/K7EKuZ57edwXhFh3SXsZadwM1y83HmVfBR0k/NdEeKR21BBb8j/qi1OQO9srmK36cn5bq94v3uvXASHzNXDsEFFd9s77dxnJe4hwLbc3ZvjYgYWxKwtMgJby/GGBaJjiNe5PxEY1/GweRLGxnXKeiE/P7IjkeF2f6UtW8rk3t43EzQyxJb5k+czndK12Fw/XsouZww8pFOD5gJvBU8u+nrYGNucV/9kQIfl7CXDGX+L1+hjQEEuigrz9kctTCNKoxasrU0jh+VQ1dcCNf7L66mOxXuSN4PfwWTER8ngk+iSXKHuNJRb6KtccoOvQalOECUocevdLE4APH+OGjK1eRytkK414OajkfWPn7smiUP+4jpqSZmIN6CSqEZwImR55K797bNW/2yex4htrGSIlzp7QcZgdm3CA+9PZ3SUVvGpnmMtjszh5B+YvrDgzndxh3ppH4OfC6Q/9j9nUeScvSToqvzU9Jzx+WuGPpflKvXYJJhwcyN8Nm9y2P/JKDAKY+qhshYKkcfQRG/iIcBmlTMv5jSxqcggDJauBTZ/AKUR8w0U1+7ogUxn/8NQ/Z4p3ANUtpY0x+L/dvLPFHUIYm6h23G9DLlagfuJmO5NAL7FbfKxYtLL+M4hb//JVIGBHOZ1g==
    client_secret: AgCMZqir4fh/Sy48UMWv3otnwMDA20tat/CGYBN2GAcnIfkobnzB8AgLWIHSDWkuca5x+jcEc08VOM6vf3nttf73OorhFly/5c/SJVFIgMgZohZTLB8wzxGTYtZ7l4QM12raixKNHDdpuNZexG70LGtoG6qIuJ8jvPWm1L3w3dhxhcjV/ZQeaiRKJi3rXNuM3E/KJTYmcwCclaNh2oz1zOzGp/PyRMRJ1/Dhdb5YpdLWA7AeBubNsHWgEhNuv1I+3t07F99D8t4cYlfVOi/cGkrad0B1JtsVp/DKGnRQznmIiTtSv7hXZhKq5DvMRdnSO/y7Ni4hnjaXjOmL9dSBxluaaZff2zM/6yLBbGgDJzm6zMXEioAm2The96Dhp9QlRF6Re0KdWZdxI3sGtRBrawDY9dbsOlwJ6OofI8Sy29BUx5ehjGKezN+ZrKLcYYYzV4qptZPtS1vlRzpTlVwmSTGurYWJMJtuLxSNmMxTvLk9gnaVkAkvI/Mx/YK2x/qBtXxpCkHeTZAMxxMfnQoB/h79BHQ1WMpF/xlaw24A1uFUiKe/lH+XQyv+DHaVgRF72lwbEqAFGoM+ysMvLhzoYP4yTiyRXhhUhPIkZy0W+ogOlEonk6AuSfn2jwx52QvkhvshL4Mv5vWpXDYBQ9qOJ9BL3loOyiB0CFszblEANHu+RSfeo5J/0uI3bber5b0Wr/pm+0F9pKSP29YQk+c8sbASZhhD9mRKfJCKYsvUinuLCpBW+aGcRnkWp8OZIfo0UsH1RffJwEruzPS7UTz3bsA=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
