---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgBsZHdlERjYkMGozVOzW9RtM3EwLRNM7Tkf5rKDMAORNrtX54A7XoIDUBQyH12G4ueSHvjLlGEdeZxlA7Tm8KUcIPxsL8MP3Bc7dQToXg94fqQcSWcaViHlNTJY5+CyVCk9nB/vmGwqdBG/NdB9poxFqMCSCvFFZbOOiGxNJoIv3LewdJVD/GTmedwgly0xr2jpOJVRlcXpkBUIbJdr8lZUqVtAxgr4HCvqrcTWZb+MTVF8S0S0UQVltg5V1RqXrlPPtbTjFDCIKgEY1Zxamg2y8BZXz/AShuQjwph49l9WNrR8ujKVAKdLJkyjOoiGgy8S+G3wr2tW3J9J5Aq0IXKmbMsaFkhZwC6vG9pbF0cq/DPO5W6G8x59doPAou2hXHqq0kigZbgReyzgA5SxdAP5IHj0se0VGKHwqeu5kmGeXES1yVBwDyJkqDUIC82UVkBglh3BSLw0NkWnGCXE90oj+xpT+zRBk2cjfBMnpBaYfZhOIwfGtCdBtiAUNq6o3jcZd8E90eLs/U+pWBXmorTD1HCnOeCv1mbeQ8nTJZTSnEgweNEIiMyPAU8294EHGFFMdb2DVK0P8lLLOkFDEp8dDQYvVGVjvV+iY3SxQ+uOuhIJiRL8JIeGIoaPOVV3EyemsnuLQyPi8wX94VrLlx3WxCyRoymWtrO1r0J+v1L3cZh/D+mpjefylpIzn5YH0hz0/yydbZ3wl8rUAD5eLKEtIA==
    client_secret: AgC71addGN4LI9llxxGOsZeOBPU29o4dt1tdY5VAncDes22+6f7pqz/thHznhN1qObUuqRZKV2JYx7eqZ23tz3w7kOR9/jdBD9KkKzXNVxAg31IImORs6BsJk7rw/5rfgGc5m9QimtT1td7lfOqtaMhAqRaMJPEjEPzPqpK4m11bmBpAKlOZSFJxq18lVDrl+tNviT0w23pBLXDJyQCZs+t5ZLzyunShIJTHDc36D9ZlJDPqpilLjDOLMFNSOTYIDLPT8lEGd86GKW9yN+L4/FyKynl3boyKCZP2IHIlh6PupqLmn21qja5CeJX/ibITL315+5Pm/asuuYAQKScL1mePJ0UsQY1bs0xlg/EKoRYvYW45cYnaoUt6kGpFG8r+kKri7Fsmn+D7XllCluQ7bcECWuUuQqNgMHxuJryzplzPqxyfycc3ScTQ5wqb83a7PkK8yLmRs19VxLM3rbGm6YVW2ldN0gUOR7lNKTm6vGF0BnfFrYDtf3gbXiwQLvpzddNhrpAmpkTKTj3T1TgN4eTsBQRmL9aE74aw+mUAAK9xWehkHq4gWwUCIFCBrZYMl+d0AHw8JcsaKyDgjQ6ZFOcmsQ19lUQIUlymyPANvTwI64DUsKy8jiFTvrHOrtMsg5+kRERpjSxDNt5AscAaqodAfOI5fFpxM9qiyR9IvX1+8BUnPjAUo9Ik2TFTRFPeA9ulA773/Zh+ith6tOFTRer24FGGE1lkfZsSaHUTo9WdI6f3dCh6/e3L4xR+tRQTnq0pxM+I1CjToE3pYxxd8e0=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
