---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgCXUpW1fR3iAIHjAsjTer1HSt38yjvmotjrtH30wbpwMc4NgtW7jEz+rTu+VXVd1ceffhckwAR0aOCSBsaoayZiJcbUVb04NfsHPfCw+OT0TxoyutXVllsIfdGvEq/KhbX2bjHfaT712HI5vY5uPuBt/ypVLqAgbmfHS24/gWjW7a7u85UYXgXuirfTtV48KQUVzwv82pjujMn+Po2/TUGFwI61iYyndiDyToOkmDFl07B1HforleNPO3ahxKI032n0dr1TMemMA5GKdiVULJnpots2nxMgIi54cEv2+Z9cDAEGlgkO1xBuWCeDaqVRkUTuWIkpkUoHikn4WUtKpm7dlSLPTRblJdsVUugp+QgeCawLHNPwEjvPjK1+TZHfSQZDmB1XtdgymvEQ918sFjxLVWeXnTa4dVL542Hgt+gyIBTTX8MW8HeI4WOxm/hn8SKbUrKmvx4KJo7IlZ+0cF+US+tISuYT1KlGyfOkW3wKDiF8W/7qirAOGyWhu2YAOSwbYXvKtG8teD+/d/OUQ3urQZk9GLfRNPg/1ctPOkjYIv3nu5Agpfv9xRT+5/BPbcAc5oRdfoIP3wT1fS+JxZZLUs2nCbiqjii6ngS6DuzBYmNYCt+W/XCbiN9V4fBx8Mt2GKarH4asKZ1IqBwsMJQ2aN0Ngl8fePrhyt8EKkSo8ZkGkfFTMlIb0PXVWdU8B3MonLUpdf4wpSfO+fDuFvcYNw==
    client_secret: AgAsGcZ+nmbeOcBtAZQWp05r/FjETvqMTLg20oLTQkx+GF/UR5jVSmshbpgxBDPASqo+Ktzn0LF3HWNNhc2xBJS6pT2n39qpV4MdqCPzt2wmhItuHQZi233Wbs4G+rWfhnvY2UzjAw3NYjnx8A0YLEwqKoderiThpvvxe0NhPVus64PBUPILPyrjiqgT1Jpzp25RYydMa9yZtoVnz5aOVNQ/i4SjmNzonoy6l+EMcbgeBJMORttCKLBjjwH/DYVkB5WqmLkmDTvKZGnZlS85D10/wudH8uXvoQdlVcBjXe2bcJK5sUkd91MpQCtykLHF4BmzHvlWn3j1DndER6WK4YSSJjqwuePrykRrNWKjdFiBAbXtutDuzOQvg6QKfYosCMD8LnWQLJ0LJZVIttaKcviu/MG2tjhzaGOc2fk3g+nuzAnZ9CJvnSX+jIISvxa0N2D5ZD1BSStiHf2KucA8AJYjyKMyi4dgc9SkrtkuULq4vDCemJgORebgF3AlEbSE8ISp9b1cG1NnUsqBri7JZNGXQZ4nRLIS1wdiqIf0vYFZEIKVFzGNShb/dVblJVXFYPoXxJNwiawJdtyRySGhxRSggaTnCN5UzAfboRPSbHoF2kjqTTzH7BU/QTCFGyqUQAvrbl7J9LgEnjoHbIhG3E2YcZZBR5nCaw08Nof7o92zOmKFS9AjVBJhiE55CchFGjehAbS08Y3Q7a/S5Dq+KsLuwBoaJ5b34gvpywtezi8EWwuBOLbcAwxan4ItY7nNQK0FKb3b40lW7voveR+OGLs=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
    type: Opaque
