apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: actual-budget-daily-backup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: "0 2 * * *"
  groups:
    - actual-budget
  labels: {}
  name: actual-budget-daily-backup
  parameters: {}
  retain: 3
  task: backup
