---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDJlAVC1OY7kIW0Up1Nq1MsVh2cabscUjIciQvItsu5QMq5dB42QVsFbnHLtKl5SnkxjpRC9QLqonnoJkEMEk01wE6xl1o004wbR01weurg8qW2IIgexWF0BNU6bKbZd0rnoJjgvh35yioNo9m1XW/7V1JJasevpOtK4P+h7SDqGtvRgiTAzSTY1Pua2w7XatrcAIGORK49wXpbjGj0cpDE+EYoP6PBUYD8FPXPyIcmulvivDss5pbcM3axsVXMUom5KYWCdohWjBbmt8GJJD0FMEftZ9OUgtk4rvIn2+G2eyJWMGfNRjYPr+QnDKS+GmANdhVKmF25Lja9ZeMjN5e6RxDnOEeOufwuc3WOD1DBvpCEGZOjTBegLdLGOgQBmOX/ff/wiAFze5uk+7LKCsNO/H4ZhUp176YNhuKAy1PKfNT07CgKBY+MaVqbUOPGgAbSoatwsPWhyny5clN1d2nfgCVUoWlBhmOfhfNpp2nuweyQVuI1R/HyxsaGcoBAUYFU8/V1svU2GRruWc6qjXw70Y3sRteDkglil8I4wG7NnonIxHnSn/HgR94Y3zNNeBosYvlfZ5uBlsxX0bEJSSXZCWNpH/b/lVTILv+8PKuguZJkQNe2kCBhSeK80bFC1dA+sf5WXfp8nT0iY7wK1EVcFPbcSshodTuS65t5LfSN3X8sCpqtF4yiT7gsQHW4JUTZy2EHYInFnpQHX6rHfmYggOwn0BhNA6gzcQ==
    AWS_ENDPOINTS: AgC4HxeUkzdS5NPgZj7f6G3poVnA5P9Deyv5GecnJqpxEFH2blzITmL3GCD5RD8gQAyfROlLIpl5qi1g5oWsSRgdZy9bocRgpGfH/nDS11oeSmu46Z1n0Czw22aUDzHX+ri96+Yi27JITM4UlRmomlcRlr42oPNNhO1fZfjGwSRF/2IBypwd34KnGyvzDrNujdvUU8Gw/VzEsgh9XSRIgopJ137k6+1wP6S5fES5lwDaTgxsrUfBd20DdMZf1IWRMC8vvOVHWwWHFvqEIS5BtSPsArR6QHhKoLka3uSSwK01MbCrZerrgrs+yApN5bj6gxoZ3gbkLKADSawXI/rMamhy+6K7/fYo0RNg7NQUu+PSwXlybbs9Z79eIN4WM6wI5v3Moow5GNz//DZaMrbfDU6ap5tlZ4lmdgHCPcOQ+fa1vwD7lUMide+StcE1DTy1RP3dr4r6SaJSUV4tG4byq1JnZM7ueAvKqmaZZAX7puQN5tTX+cWBi7QJQa3iBcCQY9ap54yjEAvO5Nddkf2cYeQ5VkxLg+cK4ehlrfIw1wuMRtFVRd95X4//Mv21b0znpYL33sVb6guJkm+D+q2aerz3u25rB5IhKm8p95NFzYGAoK7drGIq8FDKIl/oDyKRjQ4t8sX2Pxg3iLdfw84YM0Z2Uuvr+F9Bwp2jAbm10DPP4+mkLbcp5LPq3n/q4V5OUZ5sPjHQW8+J96E1SgY9PVrK1FFZWe7yNOX9HJlZDttb6LmiiWl4fv7dkw9Q
    AWS_SECRET_ACCESS_KEY: AgBCwIBg1zUYfuONATBEYd0HnQ+SefCEoyPwy3cu0e6A2CsaSa/y+/ddy2Ej2h5F3aOTQClyFL29hCKqDXTnsxzccL6Hweazn5XBPb7uloURh+Nez1zRb2lvxybvAS+fZuuVze/YnDVLO6b7LfYqh842L7i44rRECU+oUX7TuXRifEQAL/y9RQE9v4LqLBdSTnL8qFQpm4QTTau2SQzPlkpBSpSCv22eyHjhacdX7obvL+I2eh5U/9QCX4Uz2SoHvzLgD72xzIdAVo8lb/S4G/s8997H6cRIYJxF+iXd/SPJzpgRX9brNlXgqieXWOG0nlKPUvdsquj258zjB159g1i1GXsAJr2mOCHsnQQ5PDH0SnqRQFJwjyKzzDO7+tKcPeAPb8T6m2+wBoQlXvgrfqMUc6Sz5JwHwFWbinOLdIMLniZDfB/UyceqXbi1a+aqfHta+F2cMBoOZaqxtrAdJZR2ogwhj0rmH1dTbG80llOpWlbSDa53UvOgTOZddU8D7lqWF1PxfhcbnwKVJgqAVqmXnj8iNslv4pP7sk7QEPPQBU9mPf6gSADSd1IhJpZv1naNhO0Wq5+2FsBhR4ylHJFvw+Jv3OYMhy6e2wet6pJwaVXuPZgJBc8pS7f/nIKqif2rw5gyM6TN0+9IUD03DMUh5MxHILIgrCXEonOfPQA3oqgleqeUnD5h8+w5aVZMIgwQx6BF8VE3Rege8Iquyg/4Uyq8qX+NcqNQE92EaGepIzhK05sSwCowjCDlzyMb2ozLy03RuQPgNBPjT6AVMY7H
  template:
    metadata:
      name: longhorn-backup-secret
      namespace: longhorn-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-auth-secret
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgB6hp9xEQASwOJfo9C5t5QsUVyBMj67+kGVtl4YdnSwsxk+vKEPSeLcEKB/jCaCl3Fz1x7HzpDOFLZWWiCL5fo1Ak8Dg3CzeuEVGBQpW8e4NwCZ02YwskgRYZ47xng+82gbtJACJYbtD4C9M8sL1NzOg0/liMQXdif45yUO1GZUgYSdx3OoYhsfVhYnKtNCe/RdFpmMjdvZOqh8zfEX1iTZd6frwtFV6yDuZLvWk7++rFX5i1hhacIbwKfkbAD4Ro+mXTHSu2/6Tb8yVIhLzFJW6RgGVoEiR+hQlpScWcZLr99+QolZyOUxvIuOWjHeRrRXvx1FPqZUrbu2HPLeuoc+DcSWsVH0+4JwKr0KjJ461mJ8GrFK3OknH5kCc4LA2zunSYghobOlHqTS6/3CYFPZPdGwyLFtyf93Hi/zg8iYuZ2pzU15yYTMrUroN+KBzhi4xhU6XEFS8PrBJD8JLF4kHMfMlgkaTtWlt8GnEXLzTmb5K1Y1wSMH6JQ+H6MamskojHiTuw/JFZyOICqMu4PtQ64eeSxpaZCoJmZ+ilfyEE6uM3tSGCeJcP1cQ/VNIkmzB1ZRGRVZ9YLrxSA295Liuxk4lktQQ3RkX2YkflBSHLkSYHQ2P8bYtp5RQEW3O2WRmyHn6h6E2dd5wwKPOHGbTSFaSL5gYl7iz1yUzL3RF6ripxVOH3ccUDZLGvCl0jd5uRxW2HKpGlBkGwacMvcUnjNJX2wnjG5zg+ISmIflZrskiUZ8tWj21464VVA=
  template:
    metadata:
      name: longhorn-auth-secret
      namespace: longhorn-system
    type: Opaque
