---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAzLNa7i0M3RkkiNypBX6z8wKD8C9hndWEVX+Vwioyqv/sFICCsgvX9RcZj5VWTkhplsn8YMRIkMNnqtRZV/ufyDSjzCyGQAiDo5OM8Y9fYKdh4+KTUP5bpwyouwnanNDkbKOJDCY9jeEQ1bRcJ/ICXn6hgGFp0GTZWHlNTCNI88vOQcwJU4DbWszFJtwaRBgKu2XZm/S1EbY/O8fhu1+B+zRAb/0OZvN1zYGK9KRootkxeV6tOILU6ZiZOws+5u1RqfA7hc1QXnQauQmWH4jGwGF+8idATp9DB6J3K5TrZlf6nEEyKSXf1JnmFAQ5RY37nz3RMbEB0eGQeA2aEYC0A2LTtFliHSSGmjEqr/FUuLKG2lOF0LlQcj4hbFpNMK81zIrDcRefVkt3GfaCeDC25q5bxBqjgZRUMJya2GkIDCVSABZ/5au9wuqZkxkpF83w+5BdjPBIMZba/6r9l/yR1Nrlt4zEwrlU0n3533FdlrJ1EUj6YAiXbAyIiLZ2SvWqWhM7H1YfxQeV8kUWAw1aGsqNXX1lyCPZjLjpaQtziNmpqU2knd26Ak0IFpAu0PwjpsMEMU8oB6jvruHYEw/JpN9zn57KTWoyMw8kvHJm4FHEiAf9be0CVOJyxff3ncbfDuEIqmocZhuHc0WkovbyTI/QaBhvW1AMYWdAZvWtFPg1v624jPAfxJute0bxLponLtiBxjDxW+0rWjIgybRof4Sg0ysWbwjkzGA==
    AWS_ENDPOINTS: AgC9uYPfLjLuCxrsg9psoSoPC7VfR7iO8sXkpJk1yBsBYpMc0A71Z+IC476L1qMGvEm2jvBVOhmuZz7mU8OsYYkKfgsHv5UL2ppjeg1y7B/nxvsY+qFS750BBFLlM4uVYT4P2xNK4Iu73rnf/du5iitqvqclzbGVFMVPgq5E/HshuL1YBxd7Qe7S4PavJNqr6oRIDXdYH8XYP5AlJ2ABlcty1/lZnjU2YtfI9cWostV3yz3jgE918QfNqx4Dg3RbYn1bm+UHrcU3YyCnfJ3CQDGRw/FiM+egQqzBoPCzxVohpV6aUJxi0t2gJDdPyEjWH1a8iwLbbOFbTbwzc/YkLwvsinQ3MqYBLNi6kuecwa4UQBLY9R8+XdKm/Qzs/izP7nAjAEeEY959CCsDKawaDcr5kJHL9gI9GVkj3rZn9d33q4xQ6MSr+Mik+MXs4c7r+ltcV+k+WivkNQmgefgTlthPtiTEUb/Sa2sJARcql8Cf+55gvor1CNafXpw/IyxhLIWw7KNU8E10pdT3kyqKfsGW/Q0e401ci3bZHPh+nepfLvAmqcBRlfN/lnDBDl8VIVIThYUylwdjnnYxsKdDmuHmgS3l7jgr0SZBcRg/ue/aonJ4ittkIw4cZpuODfhdmWgSKUJp1jmxPN1SebvUWhK9hkuvKNP2ECr3pMSOYv8GHKT4bv9AqlBqBjZu46OsXXEiHCk+H5Jhz3hIbaJCJcUT6cXDhPsOo2LBx5b+UNW7CQd5gFa1T2aKQ6jQ
    AWS_SECRET_ACCESS_KEY: AgDBPXkGLiEab+PoIj5pQqGe/91uw1plRcvbkIbY0X5ymO5Jamy9UXHG7M23wTT7bDc/ii6K1vpnZbqwGEuJ0ep8+G/3pj1kbZ77llDIBkZybcXUFY3u0MNgmiSMhurq9nJaeXzjtzpGFs0k0+PkNKaApPieD6gfZyojNYPSHG0/UGknqotIRkmahh2lYJdv0muudfvqFODH3goW9tHrQ5+yTlTkd3uflaUzjJHmdgcg/mdgHElrXxDv5hm7uZJixNkEuI+noYnrLJ2kNa1GmXmZ+JyCcTaG5bnbJEHFIsaiZr8Rd0c7Sc82TloRW509sr8jD8C99FEtncCazYNSKop7hjgthJDrDWMptnSW2US5Vs4Evg16FnQVeGpOapVu8shRuESKABOCyC3mPM3BjPGwzF2j8j1qZ3rFR1zilBsyzddn1gbt3OltPZMbxPkIEQMKUIRhusPCQpglyD+lPc0P5qP1KyMdFpawvqgxCR4yyHTyjPwX2/xfjgrM0GFx59xgslBKC/6NZnBvO8fKeLlovflomQUnt+YZ/qCUHrgA+h3VNvA0Z/wH1OzCgrAhU+IU6MsYzImdjKNJiMgNlN3NaIbtymd54evpgydm5qltmdz+/d1NAFGlXrJYDi8zUPbSi5/SxSx/oqlXl8oJywg3qhLjmD4aA35l/cg+OyigBF7ki7yMHotWkFO5XY+kZLroGdUhEOWHdPuN9AZa3P0zBN/PZ6FHg4tfUFSsSm/U9UT6NlU1FHp6O1ss98d14ygTw2OaRVVKe2VWt1kU8BNu
  template:
    metadata:
      name: longhorn-backup-secret
      namespace: longhorn-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-auth-secret
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgB8QBkKgAiL5mx/CnIxUcRMgV13gcjVaqYf3cYZfVd+UOy4JWlhnsegfhei7O3KwVc6xlPG5pzgIDU3KtiMeOF+JtZiLNEtOFldE66gLeAfcaFq7I+OdjOZXryUHUNoLMLS39hG82tJ6wDrz/hm8j8EIx8NBiGGFSg7JZTlXg0Y7tPClSb8P63T2Z5F28+9xpj1KinnrfuiII7fdenu2ilzzGNv9QaLnsqNr7RDF50m7U+u3LWPNmd6oBUcVDxpmlXMG9eOvQi2JWv59d94vlmLV+jp4j7UycNQ+3bC0R0K7zSHMzlKr6meVLUuvOI4GtfpzGYhYaOVa2aJsHZDx2WpUrDopOIIUFh+f3biuOptci8ITKcGdl/awJ741cVzneD4yydHVbPfRwqxkFygv0eumfnm6fpO0SOL/80VcevAjDoPXlbDVeV3bjI3wfnevNHlLBSYD7RUcjEPYofnbp7MLHVRqPgJGI32Q8e6N8kmv31rvtuecJ/Q2vnkLUp9/yGnepeM+gwg5GKOIHKFeRdjHsuwsJPpmaxFEV10SLztsWT0HT8OHKeiCMtNXuGjyLvGx3X9M8Emhr2uASj18OHTHwH5FiujApED8gKXERESFq4YQMKg/M9v7Mzx0eu6uF2MQRUGqfwdqr4U2cCiOR5J03ShZudk4X1u2JfJZvYrqaCRN/edloVILu9PgiKyYuKMswFJnnn7eRAy7vhSTMg3S9x7p9ELBQo/s+YhFykc/DgBLXTd2rSLt3Gzo8M=
  template:
    metadata:
      name: longhorn-auth-secret
      namespace: longhorn-system
    type: Opaque
