---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCXPPrINnB4Rzo05NbZ3tthCsiyA+f+tN/Qqhv01B3+EnTpJCqsk0KY3Fp8qrJyq0zWAQ79UDGZKZsxbDzGKO8i/bIGxMbap2lJXebA5dZBiVEAOtB3QkoINa5u2QkUNuhLezz5CAD8JIerk3C7vHYSEmwypq7qMEL8l1snxuNIeBK20SLe9S3RIjEAbwz6y4jQLf3QGh5vqVh9O4WP/HhoqWPYmJ82wjJsSX3djHFemjLm70uMXLSbsU1C7K44DJJzPpZSpO38F2erwO+eDjqjjtZtWewuHuz/o29Wzz7v+UAW92WLUv3tiNMBGNGrxOPv/7GjIJcHc6W6hGOBnhb2xXVUeNvpNgZ2TqLasRj2nLPrZbzYOQyJOOXEor5gIMY1+TCV0JHho9yD/4AnFYmFnwziQK01L2hf0e/V22u1qc327XwnzYxmz2fKG5tfprQKA4F8h+/MWom+4mJap24wde0bToHI9grYeI+dgGz4VTmwGVBtC76deFUMsWKoYMeM4YAfo0XesBXFma6AA3KSNIshAOU530cs4uFWo6k8YGiGVtArYAbaujiJd9KwcMDHvBbuerzg6RCMqO32Xi4oBfaBtl/DktGfty1D6586ctBYzLOa6gdAyoE0cQNJd532q8FsAaE8to29ypGbaFlzA0Jt3lo9MsjimmzzCYlQX8sVHIsE4p+Qe7vt0kwodupw0kwL4y9tcgcN6uj5V1D4AwNB6xaFVoL9pQ==
    AWS_ENDPOINTS: AgC6tBJgyd8BMqzKeKoi3Mvr2Tig0bObZwev2loaZ1vIQSkqZchHyut6V3zfT3HVo3zijdlAu35488PdPrNIlFJgcw2HhlOaO5j7jAT50PmjyPJsIIrJyXyhgF+53YRfC2L6/CRjdUdGjtCcSVCkSBnj7F7oJBM56zTYXe76vloBCdB5TI1hLr+oVIZghYO/etVKwLkVwN+gYsHqGxtO+ieyJj/IIgD65agxaEbkH/KB75O30Asjg0jwryk01QqzhYIpfmGEKsxaZ0W8es3+LdR5ivGNsLY/Lhb2M2tVoFYDVF+iutwHsBAzMazORRZJyQDmsouuOmllxsRKQPalvZMf5bDiVIKtq5cvDJPE3yguCDl65wx5swG2oLQSl39tziaxVRZY5CK1W0QLEzRSjh1Tpmc+0s1Lq+2OyE9FD6tS28Y+/QOHag2roqolEq4R8VvfR44n5xd4/3fY/Uf079l2P17rLioI2OXxEaAs6i/oAP6/EgcUp5nBPu85nz3kgfQVREjupKUooAj60nNFVlnzAiXW6gZui/rrG4ANjrDq7dy9kPEM8qaI3WBxT8pjrogTHm8drALKOu0Cfk3s39hPO0xx96ON4RIv3GKbKm2P8EJeMRVG8rUt6wPqkcaL98RYSfZ40AX8zrJ/Qr4JdBc73PEjdxqVKIV/AIxJj8wEy3IyLqD7YDkd1YiiI0luYmmf+fEgPcKG/oX2rNRK4Z/aGf6ATa6wiaPCox7xQANE/RRr+Duzvw63If3F
    AWS_SECRET_ACCESS_KEY: AgDTGt0SqdnDa02s8KDUWZrbqlTMFn/TNIwYCjpbHFQ2LFF4FNy9iMmt20IPrm/pKIdDR4MseCEzx38fRvMsg7tesFG17drRvBFvuIunx0bUOsi+/nUWrCbhG6W45oAHQlTTZShw5jUIwWCyn7b1GLLLYDgAUGu2k+OKjH8TPTt83n+bHo0NmjK8nAjQyii44DTdEZchnF2qGxlILZCzLfZQOTjUwXfoBeQWbIkW2H30KsoNBcqcDZj92kAHzKggPF1P2tTRxZ04QD0+3qWdBonbQ6//uHT/c7ZoGMcS4uZjO4+spxXg+Wp9isrXyGJuZYYolNmkpX/c3fJ4hPpBc2ryThRsbTYCHEwvY0oGLupAtjD4lVsZxCBVWm39H2evw2d5uvWxCdT2X52mNuQKCu4gW+C3IzycmhzKJGQYsR0Wxwc6tH/+dCPe70sowKuP7ASkbggYm/DmMq5wP47qSirGYeSg5nQJekB6i1QIjtugbtHucP3uiPOihVhnSEJbIV/H3tQxRTQ+L/2UC+Z9oqRtcbP6ltCcB+7KSv1qF8TP2CkTJzcR/kJlkA2XaZQKxY8AiKiqjZfuIUdmGrdf7ITc1ejTWxt0avQCAtg+TL6xjtB/sTUWF7j29tu+/VCw/3Z0Zs4d2q26viWifuRtFbr/5+Tp3YMuL/SvsFdFzcvivLNSHxFjYHvKYU2/vYZTV59EZYktVPf8zJmGa3VsbAc1ZrA4JREkqR3MkcOPqOhX4wwCTRUtGcZT71DOQbyQLkcpHFdgCcci0e262bWOC5jA
  template:
    metadata:
      name: longhorn-backup-secret
      namespace: longhorn-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-auth-secret
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgA/Nst47CKA3KdME8OkZgKlch7oPw9VcXuaOpF3ToNiuYACmrOXqfN0c8DZ5Cd/h1E/oekrvF4gt1Yi0NnemsB5ar772JbPXLBNUXJtvnsSpNvqqmKv0ptWSeP2cW69KYw8zDDkntsMRFVjxPb+Ui574yE6aEUVngNljSZu2Uz7FenGywOGKj6EJz020YuFudfaS1ZPs1X4U67WFQcWMYl8YCvFnqm+FQyVa98dJghR/15Tpy4R/QWEXMrF8TnPa5ZsUis6CB0qE3Xdq36vtn5+DFinBI7APIod9l51K/+Ylt4nIVxey+sYeGTX8sD7V6M6GNMRlyVztvm+Tw1vgxqYu4XHlTti1r06CasF/UOPd8eRhZmYWBNcx7oX1dzj3H9YgRCp920WyMsLAwpCtLLMG+aXlSjJXDT1F3zh5BYqlBFflwzgPW5kknHU144z+8U1dM7vUJUE7ldf9KSDghfKVPgPgsQ1N4lOgkyATU44XjmBTw2wtecKKMeL+y/cuIkMB1YQsIAOooTpAKQX1E531f0jkwBMqXCwOlkcEGxxH+No1vXp/wUGoLhFXzkrkcUd9EyctkbRLi0do5ilO7cKxf10P339PMeD9icBmwElsZVRuy/VmCg4VTt8a7H9QUq4xobREvTm6I60tgN982q5Iflp0+HAQ59wlXxJHDxqs4ZUKre3WEAYTAxrKatYqNbx5++AEKuQC10UbEBb486VxFgfssLp/ZCSxJuLJTecMj7eIO01RLPOTTgOq6A=
  template:
    metadata:
      name: longhorn-auth-secret
      namespace: longhorn-system
    type: Opaque
