---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-auth-secret
  namespace: traefik
spec:
  encryptedData:
    users: AgDAW6IhNgloi8NUY1xlracdzkDJKBAKXCeM9fxZhBPYhckcZKqnMId1+Zl0JpSrxJ9Rlcu4BfTAkfBzuzZ9KS7GrYvGv3xYkGnhQlpDr+R8GTkawZR9tRfbY9o+pmTgPSkrI5RDka0YeH1KSHHq5uXlq6Jq3KmkVYqIOrfq402D/8FxO6P1RLEk2+RE8/U0bOv7Ch4svZMsppVj5TxSMi2f8n5a8CtPo+2sC0ihnfkoC0LTiXR58KVaOh1dsgKgLfeqg8zFMuLQEc2gfKVBMxNLBYMFPk/htpGtdFe23S3fcDX8da8jb6KYov1XbMNIoko+3dv71MLH0Rd/+VMDEXAfajjwtpFl01aKi2F3UZ/pNLO8ivqql9XUH5YXSsYG4qrltVJABdsbutrOVvQpZDPt1w8RUew5CdIotmJQo3AK0vi3qy5g4/Oh2qUjC43T5aTsI9APBDSAqJKIJ28xNTUa65E4t4SkikhxmxKvovQ7LtoQAHJCdxGrvESk4YGZe/yYbCuxT/8lwYIVw0VGeQVB9LFECjqVvjec1GwBT8G9M3tzs5XXvuNdbhywR08PGNiAps7uzVnOSTU09YFDb1KEV6ZgkuBaxBfZ6BLcIyxRuPfk1pLDz367+tzFN1TBk325Znn9a6Fg21Nq5lIuwnrJX1+hQE9wDSdfFx1KN6kPHJp5Z8nEg2ud/U90yQmIbHkbgtDDHVJn2AS7ZiEga8isy4zR+CtntMZ8wg4FVnPVCg+TQREvsAmjpdifVpFstl9vKQSWe3Ut6TfReltQXcsfTnw=
  template:
    metadata:
      name: traefik-auth-secret
      namespace: traefik
    type: Opaque
