---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-auth-secret
  namespace: traefik
spec:
  encryptedData:
    users: AgCrwrubSyG/J3cAZJViCHp908IN6XxPASf2MtIwSnv5CF8v6/URBD6YLshf015NpmC43yRG9OX8JHWkIo9PNlyYzBTrcfIbZHUeQcSFkw9ybpUcub1b35LkEYRkwzSxNQUU+4F5zSLWQfzZol7hTzD6LJuXK2ctBMLfgzg9uKA+xsWZu8IvyKxh5q/n22kWqQR3V1iYdxsbmsmMoAAJ3oozddXKTRKAljxuk5fRYx5VK06wp7oWKzR4XRvRXmj4TLXmGf8w9IsXH6se/7yhjKlMBfISqT/VwI0US7UqsHfAhImPmqnCGMdKH5mPh/QU57FMY4Og7EHt5VnNcu0SN9ROkmNB1QeWUxfR4geYmf0gwnyq4v4qjbuu0iJmX6NEf1J5HNbqzciKooojbkK0Rn9TYd5ht4JuujpMIfQSgc7BTkPmL1/6evk/LLfJOSCcZ0O2qDCMTvajqpvgVSj6bjibA0UIzg7BheEp2nQvPRPU0P828J8usu3fpmyjjp7YYJteZoaOgezg85/VMxUxnjQuBRAWMilADhz7IoYhtm+GYkTA39gIs7KxaVna+mwD17jHHhLGjXTD/d/onsKOk02No0bpHSB7xV3XFcB0sz6D6ps8oZslLXnIUb/ZOVR8Nqn4RqNvJWWhf6lVDMVkqSVHgmdkZh8xyAVqAMPQJQxCa/ecU73MyG3aNWIeiMYbR+Xf6s9MmulLHq6kzT88VIERTAk5eXnAZgtD9hFOls0bWVaQUJqQ1Y+xZ1S8G+kWpMKBvI3b5wpW/Ln+Rx4sE+4BD6I=
  template:
    metadata:
      name: traefik-auth-secret
      namespace: traefik
    type: Opaque
