oauth:
  existingSecret: "operator-oauth"
  clientIdKey: "client_id"
  clientSecretKey: "client_secret"

operatorConfig:
  image:
    repository: tailscale/k8s-operator
    tag: "v1.102.2"
  hostname: "tailscale-operator"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

proxyConfig:
  image:
    repository: tailscale/tailscale
    tag: "v1.102.2"
  defaultProxyClass: "worker-only"
